// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/common.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes: numbering authority is this enum. Codes 1..112 enumerate every
// code in errors.md section Canonical Codes in order of first appearance,
// fenced blocks in document order, each block row-major. New codes append only;
// numbers are never reused or reordered.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED                      ErrorCode = 0
	ErrorCode_ERROR_CODE_PROTOCOL_MALFORMED               ErrorCode = 1
	ErrorCode_ERROR_CODE_PROTOCOL_UNSUPPORTED             ErrorCode = 2
	ErrorCode_ERROR_CODE_PROTOCOL_VIOLATION               ErrorCode = 3
	ErrorCode_ERROR_CODE_MESSAGE_UNKNOWN                  ErrorCode = 4
	ErrorCode_ERROR_CODE_MESSAGE_TOO_LARGE                ErrorCode = 5
	ErrorCode_ERROR_CODE_MESSAGE_NOT_ALLOWED_IN_STATE     ErrorCode = 6
	ErrorCode_ERROR_CODE_CLIENT_UPDATE_REQUIRED           ErrorCode = 7
	ErrorCode_ERROR_CODE_CONTENT_INCOMPATIBLE             ErrorCode = 8
	ErrorCode_ERROR_CODE_RATE_LIMITED                     ErrorCode = 9
	ErrorCode_ERROR_CODE_SERVER_OVERLOADED                ErrorCode = 10
	ErrorCode_ERROR_CODE_SERVER_DRAINING                  ErrorCode = 11
	ErrorCode_ERROR_CODE_AUTH_REQUIRED                    ErrorCode = 12
	ErrorCode_ERROR_CODE_AUTH_INVALID                     ErrorCode = 13
	ErrorCode_ERROR_CODE_AUTH_EXPIRED                     ErrorCode = 14
	ErrorCode_ERROR_CODE_SESSION_EPOCH_STALE              ErrorCode = 15
	ErrorCode_ERROR_CODE_SESSION_REPLACED                 ErrorCode = 16
	ErrorCode_ERROR_CODE_CHARACTER_ALREADY_ACTIVE         ErrorCode = 17
	ErrorCode_ERROR_CODE_RESUME_EXPIRED                   ErrorCode = 18
	ErrorCode_ERROR_CODE_ACCOUNT_BANNED                   ErrorCode = 19
	ErrorCode_ERROR_CODE_ACCOUNT_PENDING_DELETION         ErrorCode = 20
	ErrorCode_ERROR_CODE_ACCOUNT_SUSPENDED                ErrorCode = 21
	ErrorCode_ERROR_CODE_ENTITLEMENT_REVOKED              ErrorCode = 22
	ErrorCode_ERROR_CODE_USERNAME_INVALID                 ErrorCode = 23
	ErrorCode_ERROR_CODE_EMAIL_INVALID                    ErrorCode = 24
	ErrorCode_ERROR_CODE_PASSWORD_INVALID                 ErrorCode = 25
	ErrorCode_ERROR_CODE_USERNAME_TAKEN                   ErrorCode = 26
	ErrorCode_ERROR_CODE_EMAIL_TAKEN                      ErrorCode = 27
	ErrorCode_ERROR_CODE_PROVIDER_ALREADY_LINKED          ErrorCode = 28
	ErrorCode_ERROR_CODE_LAST_LOGIN_METHOD                ErrorCode = 29
	ErrorCode_ERROR_CODE_CREDENTIAL_CHANGE_LOCKED         ErrorCode = 30
	ErrorCode_ERROR_CODE_CHARACTER_NAME_INVALID           ErrorCode = 31
	ErrorCode_ERROR_CODE_CHARACTER_NAME_TAKEN             ErrorCode = 32
	ErrorCode_ERROR_CODE_CHARACTER_SLOTS_FULL             ErrorCode = 33
	ErrorCode_ERROR_CODE_OWNER_NOT_FOUND                  ErrorCode = 34
	ErrorCode_ERROR_CODE_OWNER_CHANGED                    ErrorCode = 35
	ErrorCode_ERROR_CODE_TRANSFER_IN_PROGRESS             ErrorCode = 36
	ErrorCode_ERROR_CODE_TRANSFER_FAILED                  ErrorCode = 37
	ErrorCode_ERROR_CODE_STALE_INPUT                      ErrorCode = 38
	ErrorCode_ERROR_CODE_INVALID_TARGET                   ErrorCode = 39
	ErrorCode_ERROR_CODE_INVALID_STATE                    ErrorCode = 40
	ErrorCode_ERROR_CODE_MAP_CAPACITY_FULL                ErrorCode = 41
	ErrorCode_ERROR_CODE_OPERATION_CONFLICT               ErrorCode = 42
	ErrorCode_ERROR_CODE_OPERATION_IN_PROGRESS            ErrorCode = 43
	ErrorCode_ERROR_CODE_OPERATION_REJECTED               ErrorCode = 44
	ErrorCode_ERROR_CODE_TEMPORARY_DEPENDENCY_FAILURE     ErrorCode = 45
	ErrorCode_ERROR_CODE_IAP_RECEIPT_ACCOUNT_MISMATCH     ErrorCode = 46
	ErrorCode_ERROR_CODE_IAP_PRODUCT_MISMATCH             ErrorCode = 47
	ErrorCode_ERROR_CODE_IAP_RECEIPT_INVALID              ErrorCode = 48
	ErrorCode_ERROR_CODE_IAP_SEASON_TRACK_DUPLICATE       ErrorCode = 49
	ErrorCode_ERROR_CODE_IAP_VERIFICATION_PENDING         ErrorCode = 50
	ErrorCode_ERROR_CODE_CHEST_ELIGIBILITY_INVALID        ErrorCode = 51
	ErrorCode_ERROR_CODE_TRADE_PARTNER_DISCONNECTED       ErrorCode = 52
	ErrorCode_ERROR_CODE_TRADE_ELIGIBILITY_LEVEL_REQUIRED ErrorCode = 53
	ErrorCode_ERROR_CODE_TRADE_ELIGIBILITY_AGE_REQUIRED   ErrorCode = 54
	ErrorCode_ERROR_CODE_AH_ELIGIBILITY_LEVEL_REQUIRED    ErrorCode = 55
	ErrorCode_ERROR_CODE_AH_ELIGIBILITY_AGE_REQUIRED      ErrorCode = 56
	ErrorCode_ERROR_CODE_TRADE_COMMON_BOTH_SIDES          ErrorCode = 57
	ErrorCode_ERROR_CODE_TRADE_PRICE_FLOOR_NOT_MET        ErrorCode = 58
	ErrorCode_ERROR_CODE_AH_PRICE_FLOOR_NOT_MET           ErrorCode = 59
	ErrorCode_ERROR_CODE_SAME_ACCOUNT_FORBIDDEN           ErrorCode = 60
	ErrorCode_ERROR_CODE_INVENTORY_FULL                   ErrorCode = 61
	ErrorCode_ERROR_CODE_INSUFFICIENT_CURRENCY            ErrorCode = 62
	ErrorCode_ERROR_CODE_CURRENCY_CAP_EXCEEDED            ErrorCode = 63
	ErrorCode_ERROR_CODE_COOLDOWN_ACTIVE                  ErrorCode = 64
	ErrorCode_ERROR_CODE_ITEM_NOT_FOUND                   ErrorCode = 65
	ErrorCode_ERROR_CODE_ITEM_LOCKED                      ErrorCode = 66
	ErrorCode_ERROR_CODE_NOT_OWNER                        ErrorCode = 67
	ErrorCode_ERROR_CODE_PERMISSION_DENIED                ErrorCode = 68
	ErrorCode_ERROR_CODE_TARGET_INVALID                   ErrorCode = 69
	ErrorCode_ERROR_CODE_OUT_OF_RANGE                     ErrorCode = 70
	ErrorCode_ERROR_CODE_IN_COMBAT                        ErrorCode = 71
	ErrorCode_ERROR_CODE_LEVEL_TOO_LOW                    ErrorCode = 72
	ErrorCode_ERROR_CODE_CAPACITY_FULL                    ErrorCode = 73
	ErrorCode_ERROR_CODE_ALREADY_OWNED                    ErrorCode = 74
	ErrorCode_ERROR_CODE_EXPIRED                          ErrorCode = 75
	ErrorCode_ERROR_CODE_STATE_CONFLICT                   ErrorCode = 76
	ErrorCode_ERROR_CODE_NOT_IN_SAFE_ANCHOR               ErrorCode = 77
	ErrorCode_ERROR_CODE_DAILY_LIMIT_REACHED              ErrorCode = 78
	ErrorCode_ERROR_CODE_GUILD_DISBAND_BLOCKED            ErrorCode = 79
	ErrorCode_ERROR_CODE_GUILD_STORAGE_SAME_ACCOUNT       ErrorCode = 80
	ErrorCode_ERROR_CODE_GUILD_MEMBERSHIP_TOO_NEW         ErrorCode = 81
	ErrorCode_ERROR_CODE_AUCTION_LISTING_NOT_ACTIVE       ErrorCode = 82
	ErrorCode_ERROR_CODE_CLAIM_WINDOW_CLOSED              ErrorCode = 83
	ErrorCode_ERROR_CODE_DURABLE_BACKPRESSURE             ErrorCode = 84
	ErrorCode_ERROR_CODE_BEAST_NOT_OWNED                  ErrorCode = 85
	ErrorCode_ERROR_CODE_SLOT_MISMATCH                    ErrorCode = 86
	ErrorCode_ERROR_CODE_SLOT_EMPTY                       ErrorCode = 87
	ErrorCode_ERROR_CODE_INSUFFICIENT_ITEM                ErrorCode = 88
	ErrorCode_ERROR_CODE_DAILY_FOOD_CAP_REACHED           ErrorCode = 89
	ErrorCode_ERROR_CODE_MAX_BOND_REACHED                 ErrorCode = 90
	ErrorCode_ERROR_CODE_FRIEND_LIMIT_REACHED             ErrorCode = 91
	ErrorCode_ERROR_CODE_TARGET_BLOCKED                   ErrorCode = 92
	ErrorCode_ERROR_CODE_ALREADY_FRIENDS                  ErrorCode = 93
	ErrorCode_ERROR_CODE_PENDING_REQUEST_EXISTS           ErrorCode = 94
	ErrorCode_ERROR_CODE_CLAIM_CAP_REACHED                ErrorCode = 95
	ErrorCode_ERROR_CODE_CHARM_INELIGIBLE                 ErrorCode = 96
	ErrorCode_ERROR_CODE_SKILL_NOT_LEARNED                ErrorCode = 97
	ErrorCode_ERROR_CODE_SKILL_MAX_LEVEL                  ErrorCode = 98
	ErrorCode_ERROR_CODE_SKILL_POINTS_INSUFFICIENT        ErrorCode = 99
	ErrorCode_ERROR_CODE_SKILL_LOADOUT_INVALID            ErrorCode = 100
	ErrorCode_ERROR_CODE_POTENTIAL_POINTS_INSUFFICIENT    ErrorCode = 101
	ErrorCode_ERROR_CODE_POTENTIAL_CAP_EXCEEDED           ErrorCode = 102
	ErrorCode_ERROR_CODE_INSUFFICIENT_MP                  ErrorCode = 103
	ErrorCode_ERROR_CODE_SOUL_CONTRACT_LIMIT_REACHED      ErrorCode = 104
	ErrorCode_ERROR_CODE_STORY_CHOICE_REQUIRED            ErrorCode = 105
	ErrorCode_ERROR_CODE_NOT_DISCOVERED                   ErrorCode = 106
	ErrorCode_ERROR_CODE_GUILD_NAME_TAKEN                 ErrorCode = 107
	ErrorCode_ERROR_CODE_GUILD_NAME_INVALID               ErrorCode = 108
	ErrorCode_ERROR_CODE_ATLAS_TIER_NOT_REACHED           ErrorCode = 109
	ErrorCode_ERROR_CODE_CHAT_TEXT_INVALID                ErrorCode = 110
	ErrorCode_ERROR_CODE_OPERATION_EXPIRED                ErrorCode = 111
	ErrorCode_ERROR_CODE_REQUEST_TOO_LARGE                ErrorCode = 112
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNSPECIFIED",
		1:   "ERROR_CODE_PROTOCOL_MALFORMED",
		2:   "ERROR_CODE_PROTOCOL_UNSUPPORTED",
		3:   "ERROR_CODE_PROTOCOL_VIOLATION",
		4:   "ERROR_CODE_MESSAGE_UNKNOWN",
		5:   "ERROR_CODE_MESSAGE_TOO_LARGE",
		6:   "ERROR_CODE_MESSAGE_NOT_ALLOWED_IN_STATE",
		7:   "ERROR_CODE_CLIENT_UPDATE_REQUIRED",
		8:   "ERROR_CODE_CONTENT_INCOMPATIBLE",
		9:   "ERROR_CODE_RATE_LIMITED",
		10:  "ERROR_CODE_SERVER_OVERLOADED",
		11:  "ERROR_CODE_SERVER_DRAINING",
		12:  "ERROR_CODE_AUTH_REQUIRED",
		13:  "ERROR_CODE_AUTH_INVALID",
		14:  "ERROR_CODE_AUTH_EXPIRED",
		15:  "ERROR_CODE_SESSION_EPOCH_STALE",
		16:  "ERROR_CODE_SESSION_REPLACED",
		17:  "ERROR_CODE_CHARACTER_ALREADY_ACTIVE",
		18:  "ERROR_CODE_RESUME_EXPIRED",
		19:  "ERROR_CODE_ACCOUNT_BANNED",
		20:  "ERROR_CODE_ACCOUNT_PENDING_DELETION",
		21:  "ERROR_CODE_ACCOUNT_SUSPENDED",
		22:  "ERROR_CODE_ENTITLEMENT_REVOKED",
		23:  "ERROR_CODE_USERNAME_INVALID",
		24:  "ERROR_CODE_EMAIL_INVALID",
		25:  "ERROR_CODE_PASSWORD_INVALID",
		26:  "ERROR_CODE_USERNAME_TAKEN",
		27:  "ERROR_CODE_EMAIL_TAKEN",
		28:  "ERROR_CODE_PROVIDER_ALREADY_LINKED",
		29:  "ERROR_CODE_LAST_LOGIN_METHOD",
		30:  "ERROR_CODE_CREDENTIAL_CHANGE_LOCKED",
		31:  "ERROR_CODE_CHARACTER_NAME_INVALID",
		32:  "ERROR_CODE_CHARACTER_NAME_TAKEN",
		33:  "ERROR_CODE_CHARACTER_SLOTS_FULL",
		34:  "ERROR_CODE_OWNER_NOT_FOUND",
		35:  "ERROR_CODE_OWNER_CHANGED",
		36:  "ERROR_CODE_TRANSFER_IN_PROGRESS",
		37:  "ERROR_CODE_TRANSFER_FAILED",
		38:  "ERROR_CODE_STALE_INPUT",
		39:  "ERROR_CODE_INVALID_TARGET",
		40:  "ERROR_CODE_INVALID_STATE",
		41:  "ERROR_CODE_MAP_CAPACITY_FULL",
		42:  "ERROR_CODE_OPERATION_CONFLICT",
		43:  "ERROR_CODE_OPERATION_IN_PROGRESS",
		44:  "ERROR_CODE_OPERATION_REJECTED",
		45:  "ERROR_CODE_TEMPORARY_DEPENDENCY_FAILURE",
		46:  "ERROR_CODE_IAP_RECEIPT_ACCOUNT_MISMATCH",
		47:  "ERROR_CODE_IAP_PRODUCT_MISMATCH",
		48:  "ERROR_CODE_IAP_RECEIPT_INVALID",
		49:  "ERROR_CODE_IAP_SEASON_TRACK_DUPLICATE",
		50:  "ERROR_CODE_IAP_VERIFICATION_PENDING",
		51:  "ERROR_CODE_CHEST_ELIGIBILITY_INVALID",
		52:  "ERROR_CODE_TRADE_PARTNER_DISCONNECTED",
		53:  "ERROR_CODE_TRADE_ELIGIBILITY_LEVEL_REQUIRED",
		54:  "ERROR_CODE_TRADE_ELIGIBILITY_AGE_REQUIRED",
		55:  "ERROR_CODE_AH_ELIGIBILITY_LEVEL_REQUIRED",
		56:  "ERROR_CODE_AH_ELIGIBILITY_AGE_REQUIRED",
		57:  "ERROR_CODE_TRADE_COMMON_BOTH_SIDES",
		58:  "ERROR_CODE_TRADE_PRICE_FLOOR_NOT_MET",
		59:  "ERROR_CODE_AH_PRICE_FLOOR_NOT_MET",
		60:  "ERROR_CODE_SAME_ACCOUNT_FORBIDDEN",
		61:  "ERROR_CODE_INVENTORY_FULL",
		62:  "ERROR_CODE_INSUFFICIENT_CURRENCY",
		63:  "ERROR_CODE_CURRENCY_CAP_EXCEEDED",
		64:  "ERROR_CODE_COOLDOWN_ACTIVE",
		65:  "ERROR_CODE_ITEM_NOT_FOUND",
		66:  "ERROR_CODE_ITEM_LOCKED",
		67:  "ERROR_CODE_NOT_OWNER",
		68:  "ERROR_CODE_PERMISSION_DENIED",
		69:  "ERROR_CODE_TARGET_INVALID",
		70:  "ERROR_CODE_OUT_OF_RANGE",
		71:  "ERROR_CODE_IN_COMBAT",
		72:  "ERROR_CODE_LEVEL_TOO_LOW",
		73:  "ERROR_CODE_CAPACITY_FULL",
		74:  "ERROR_CODE_ALREADY_OWNED",
		75:  "ERROR_CODE_EXPIRED",
		76:  "ERROR_CODE_STATE_CONFLICT",
		77:  "ERROR_CODE_NOT_IN_SAFE_ANCHOR",
		78:  "ERROR_CODE_DAILY_LIMIT_REACHED",
		79:  "ERROR_CODE_GUILD_DISBAND_BLOCKED",
		80:  "ERROR_CODE_GUILD_STORAGE_SAME_ACCOUNT",
		81:  "ERROR_CODE_GUILD_MEMBERSHIP_TOO_NEW",
		82:  "ERROR_CODE_AUCTION_LISTING_NOT_ACTIVE",
		83:  "ERROR_CODE_CLAIM_WINDOW_CLOSED",
		84:  "ERROR_CODE_DURABLE_BACKPRESSURE",
		85:  "ERROR_CODE_BEAST_NOT_OWNED",
		86:  "ERROR_CODE_SLOT_MISMATCH",
		87:  "ERROR_CODE_SLOT_EMPTY",
		88:  "ERROR_CODE_INSUFFICIENT_ITEM",
		89:  "ERROR_CODE_DAILY_FOOD_CAP_REACHED",
		90:  "ERROR_CODE_MAX_BOND_REACHED",
		91:  "ERROR_CODE_FRIEND_LIMIT_REACHED",
		92:  "ERROR_CODE_TARGET_BLOCKED",
		93:  "ERROR_CODE_ALREADY_FRIENDS",
		94:  "ERROR_CODE_PENDING_REQUEST_EXISTS",
		95:  "ERROR_CODE_CLAIM_CAP_REACHED",
		96:  "ERROR_CODE_CHARM_INELIGIBLE",
		97:  "ERROR_CODE_SKILL_NOT_LEARNED",
		98:  "ERROR_CODE_SKILL_MAX_LEVEL",
		99:  "ERROR_CODE_SKILL_POINTS_INSUFFICIENT",
		100: "ERROR_CODE_SKILL_LOADOUT_INVALID",
		101: "ERROR_CODE_POTENTIAL_POINTS_INSUFFICIENT",
		102: "ERROR_CODE_POTENTIAL_CAP_EXCEEDED",
		103: "ERROR_CODE_INSUFFICIENT_MP",
		104: "ERROR_CODE_SOUL_CONTRACT_LIMIT_REACHED",
		105: "ERROR_CODE_STORY_CHOICE_REQUIRED",
		106: "ERROR_CODE_NOT_DISCOVERED",
		107: "ERROR_CODE_GUILD_NAME_TAKEN",
		108: "ERROR_CODE_GUILD_NAME_INVALID",
		109: "ERROR_CODE_ATLAS_TIER_NOT_REACHED",
		110: "ERROR_CODE_CHAT_TEXT_INVALID",
		111: "ERROR_CODE_OPERATION_EXPIRED",
		112: "ERROR_CODE_REQUEST_TOO_LARGE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                      0,
		"ERROR_CODE_PROTOCOL_MALFORMED":               1,
		"ERROR_CODE_PROTOCOL_UNSUPPORTED":             2,
		"ERROR_CODE_PROTOCOL_VIOLATION":               3,
		"ERROR_CODE_MESSAGE_UNKNOWN":                  4,
		"ERROR_CODE_MESSAGE_TOO_LARGE":                5,
		"ERROR_CODE_MESSAGE_NOT_ALLOWED_IN_STATE":     6,
		"ERROR_CODE_CLIENT_UPDATE_REQUIRED":           7,
		"ERROR_CODE_CONTENT_INCOMPATIBLE":             8,
		"ERROR_CODE_RATE_LIMITED":                     9,
		"ERROR_CODE_SERVER_OVERLOADED":                10,
		"ERROR_CODE_SERVER_DRAINING":                  11,
		"ERROR_CODE_AUTH_REQUIRED":                    12,
		"ERROR_CODE_AUTH_INVALID":                     13,
		"ERROR_CODE_AUTH_EXPIRED":                     14,
		"ERROR_CODE_SESSION_EPOCH_STALE":              15,
		"ERROR_CODE_SESSION_REPLACED":                 16,
		"ERROR_CODE_CHARACTER_ALREADY_ACTIVE":         17,
		"ERROR_CODE_RESUME_EXPIRED":                   18,
		"ERROR_CODE_ACCOUNT_BANNED":                   19,
		"ERROR_CODE_ACCOUNT_PENDING_DELETION":         20,
		"ERROR_CODE_ACCOUNT_SUSPENDED":                21,
		"ERROR_CODE_ENTITLEMENT_REVOKED":              22,
		"ERROR_CODE_USERNAME_INVALID":                 23,
		"ERROR_CODE_EMAIL_INVALID":                    24,
		"ERROR_CODE_PASSWORD_INVALID":                 25,
		"ERROR_CODE_USERNAME_TAKEN":                   26,
		"ERROR_CODE_EMAIL_TAKEN":                      27,
		"ERROR_CODE_PROVIDER_ALREADY_LINKED":          28,
		"ERROR_CODE_LAST_LOGIN_METHOD":                29,
		"ERROR_CODE_CREDENTIAL_CHANGE_LOCKED":         30,
		"ERROR_CODE_CHARACTER_NAME_INVALID":           31,
		"ERROR_CODE_CHARACTER_NAME_TAKEN":             32,
		"ERROR_CODE_CHARACTER_SLOTS_FULL":             33,
		"ERROR_CODE_OWNER_NOT_FOUND":                  34,
		"ERROR_CODE_OWNER_CHANGED":                    35,
		"ERROR_CODE_TRANSFER_IN_PROGRESS":             36,
		"ERROR_CODE_TRANSFER_FAILED":                  37,
		"ERROR_CODE_STALE_INPUT":                      38,
		"ERROR_CODE_INVALID_TARGET":                   39,
		"ERROR_CODE_INVALID_STATE":                    40,
		"ERROR_CODE_MAP_CAPACITY_FULL":                41,
		"ERROR_CODE_OPERATION_CONFLICT":               42,
		"ERROR_CODE_OPERATION_IN_PROGRESS":            43,
		"ERROR_CODE_OPERATION_REJECTED":               44,
		"ERROR_CODE_TEMPORARY_DEPENDENCY_FAILURE":     45,
		"ERROR_CODE_IAP_RECEIPT_ACCOUNT_MISMATCH":     46,
		"ERROR_CODE_IAP_PRODUCT_MISMATCH":             47,
		"ERROR_CODE_IAP_RECEIPT_INVALID":              48,
		"ERROR_CODE_IAP_SEASON_TRACK_DUPLICATE":       49,
		"ERROR_CODE_IAP_VERIFICATION_PENDING":         50,
		"ERROR_CODE_CHEST_ELIGIBILITY_INVALID":        51,
		"ERROR_CODE_TRADE_PARTNER_DISCONNECTED":       52,
		"ERROR_CODE_TRADE_ELIGIBILITY_LEVEL_REQUIRED": 53,
		"ERROR_CODE_TRADE_ELIGIBILITY_AGE_REQUIRED":   54,
		"ERROR_CODE_AH_ELIGIBILITY_LEVEL_REQUIRED":    55,
		"ERROR_CODE_AH_ELIGIBILITY_AGE_REQUIRED":      56,
		"ERROR_CODE_TRADE_COMMON_BOTH_SIDES":          57,
		"ERROR_CODE_TRADE_PRICE_FLOOR_NOT_MET":        58,
		"ERROR_CODE_AH_PRICE_FLOOR_NOT_MET":           59,
		"ERROR_CODE_SAME_ACCOUNT_FORBIDDEN":           60,
		"ERROR_CODE_INVENTORY_FULL":                   61,
		"ERROR_CODE_INSUFFICIENT_CURRENCY":            62,
		"ERROR_CODE_CURRENCY_CAP_EXCEEDED":            63,
		"ERROR_CODE_COOLDOWN_ACTIVE":                  64,
		"ERROR_CODE_ITEM_NOT_FOUND":                   65,
		"ERROR_CODE_ITEM_LOCKED":                      66,
		"ERROR_CODE_NOT_OWNER":                        67,
		"ERROR_CODE_PERMISSION_DENIED":                68,
		"ERROR_CODE_TARGET_INVALID":                   69,
		"ERROR_CODE_OUT_OF_RANGE":                     70,
		"ERROR_CODE_IN_COMBAT":                        71,
		"ERROR_CODE_LEVEL_TOO_LOW":                    72,
		"ERROR_CODE_CAPACITY_FULL":                    73,
		"ERROR_CODE_ALREADY_OWNED":                    74,
		"ERROR_CODE_EXPIRED":                          75,
		"ERROR_CODE_STATE_CONFLICT":                   76,
		"ERROR_CODE_NOT_IN_SAFE_ANCHOR":               77,
		"ERROR_CODE_DAILY_LIMIT_REACHED":              78,
		"ERROR_CODE_GUILD_DISBAND_BLOCKED":            79,
		"ERROR_CODE_GUILD_STORAGE_SAME_ACCOUNT":       80,
		"ERROR_CODE_GUILD_MEMBERSHIP_TOO_NEW":         81,
		"ERROR_CODE_AUCTION_LISTING_NOT_ACTIVE":       82,
		"ERROR_CODE_CLAIM_WINDOW_CLOSED":              83,
		"ERROR_CODE_DURABLE_BACKPRESSURE":             84,
		"ERROR_CODE_BEAST_NOT_OWNED":                  85,
		"ERROR_CODE_SLOT_MISMATCH":                    86,
		"ERROR_CODE_SLOT_EMPTY":                       87,
		"ERROR_CODE_INSUFFICIENT_ITEM":                88,
		"ERROR_CODE_DAILY_FOOD_CAP_REACHED":           89,
		"ERROR_CODE_MAX_BOND_REACHED":                 90,
		"ERROR_CODE_FRIEND_LIMIT_REACHED":             91,
		"ERROR_CODE_TARGET_BLOCKED":                   92,
		"ERROR_CODE_ALREADY_FRIENDS":                  93,
		"ERROR_CODE_PENDING_REQUEST_EXISTS":           94,
		"ERROR_CODE_CLAIM_CAP_REACHED":                95,
		"ERROR_CODE_CHARM_INELIGIBLE":                 96,
		"ERROR_CODE_SKILL_NOT_LEARNED":                97,
		"ERROR_CODE_SKILL_MAX_LEVEL":                  98,
		"ERROR_CODE_SKILL_POINTS_INSUFFICIENT":        99,
		"ERROR_CODE_SKILL_LOADOUT_INVALID":            100,
		"ERROR_CODE_POTENTIAL_POINTS_INSUFFICIENT":    101,
		"ERROR_CODE_POTENTIAL_CAP_EXCEEDED":           102,
		"ERROR_CODE_INSUFFICIENT_MP":                  103,
		"ERROR_CODE_SOUL_CONTRACT_LIMIT_REACHED":      104,
		"ERROR_CODE_STORY_CHOICE_REQUIRED":            105,
		"ERROR_CODE_NOT_DISCOVERED":                   106,
		"ERROR_CODE_GUILD_NAME_TAKEN":                 107,
		"ERROR_CODE_GUILD_NAME_INVALID":               108,
		"ERROR_CODE_ATLAS_TIER_NOT_REACHED":           109,
		"ERROR_CODE_CHAT_TEXT_INVALID":                110,
		"ERROR_CODE_OPERATION_EXPIRED":                111,
		"ERROR_CODE_REQUEST_TOO_LARGE":                112,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{0}
}

type Retryability int32

const (
	Retryability_RETRYABILITY_UNSPECIFIED          Retryability = 0
	Retryability_RETRYABILITY_NEVER                Retryability = 1
	Retryability_RETRYABILITY_RETRY_SAME_OPERATION Retryability = 2
	Retryability_RETRYABILITY_RECONNECT            Retryability = 3
	Retryability_RETRYABILITY_UPDATE_REQUIRED      Retryability = 4
	Retryability_RETRYABILITY_REAUTHENTICATE       Retryability = 5
	Retryability_RETRYABILITY_BACKOFF              Retryability = 6
)

// Enum value maps for Retryability.
var (
	Retryability_name = map[int32]string{
		0: "RETRYABILITY_UNSPECIFIED",
		1: "RETRYABILITY_NEVER",
		2: "RETRYABILITY_RETRY_SAME_OPERATION",
		3: "RETRYABILITY_RECONNECT",
		4: "RETRYABILITY_UPDATE_REQUIRED",
		5: "RETRYABILITY_REAUTHENTICATE",
		6: "RETRYABILITY_BACKOFF",
	}
	Retryability_value = map[string]int32{
		"RETRYABILITY_UNSPECIFIED":          0,
		"RETRYABILITY_NEVER":                1,
		"RETRYABILITY_RETRY_SAME_OPERATION": 2,
		"RETRYABILITY_RECONNECT":            3,
		"RETRYABILITY_UPDATE_REQUIRED":      4,
		"RETRYABILITY_REAUTHENTICATE":       5,
		"RETRYABILITY_BACKOFF":              6,
	}
)

func (x Retryability) Enum() *Retryability {
	p := new(Retryability)
	*p = x
	return p
}

func (x Retryability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retryability) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[1].Descriptor()
}

func (Retryability) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[1]
}

func (x Retryability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retryability.Descriptor instead.
func (Retryability) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{1}
}

type ResultStatus int32

const (
	ResultStatus_RESULT_STATUS_UNSPECIFIED ResultStatus = 0
	ResultStatus_RESULT_STATUS_SUCCESS     ResultStatus = 1
	ResultStatus_RESULT_STATUS_ERROR       ResultStatus = 2
)

// Enum value maps for ResultStatus.
var (
	ResultStatus_name = map[int32]string{
		0: "RESULT_STATUS_UNSPECIFIED",
		1: "RESULT_STATUS_SUCCESS",
		2: "RESULT_STATUS_ERROR",
	}
	ResultStatus_value = map[string]int32{
		"RESULT_STATUS_UNSPECIFIED": 0,
		"RESULT_STATUS_SUCCESS":     1,
		"RESULT_STATUS_ERROR":       2,
	}
)

func (x ResultStatus) Enum() *ResultStatus {
	p := new(ResultStatus)
	*p = x
	return p
}

func (x ResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[2].Descriptor()
}

func (ResultStatus) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[2]
}

func (x ResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultStatus.Descriptor instead.
func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{2}
}

type Element int32

const (
	Element_ELEMENT_UNSPECIFIED Element = 0
	Element_ELEMENT_KIM         Element = 1
	Element_ELEMENT_THUY        Element = 2
	Element_ELEMENT_MOC         Element = 3
	Element_ELEMENT_HOA         Element = 4
	Element_ELEMENT_THO         Element = 5
	Element_ELEMENT_PHYSICAL    Element = 6
)

// Enum value maps for Element.
var (
	Element_name = map[int32]string{
		0: "ELEMENT_UNSPECIFIED",
		1: "ELEMENT_KIM",
		2: "ELEMENT_THUY",
		3: "ELEMENT_MOC",
		4: "ELEMENT_HOA",
		5: "ELEMENT_THO",
		6: "ELEMENT_PHYSICAL",
	}
	Element_value = map[string]int32{
		"ELEMENT_UNSPECIFIED": 0,
		"ELEMENT_KIM":         1,
		"ELEMENT_THUY":        2,
		"ELEMENT_MOC":         3,
		"ELEMENT_HOA":         4,
		"ELEMENT_THO":         5,
		"ELEMENT_PHYSICAL":    6,
	}
)

func (x Element) Enum() *Element {
	p := new(Element)
	*p = x
	return p
}

func (x Element) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Element) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[3].Descriptor()
}

func (Element) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[3]
}

func (x Element) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Element.Descriptor instead.
func (Element) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{3}
}

type EntityKind int32

const (
	EntityKind_ENTITY_KIND_UNSPECIFIED EntityKind = 0
	EntityKind_ENTITY_KIND_PLAYER      EntityKind = 1
	EntityKind_ENTITY_KIND_MONSTER     EntityKind = 2
	EntityKind_ENTITY_KIND_NPC         EntityKind = 3
	EntityKind_ENTITY_KIND_BEAST       EntityKind = 4
	EntityKind_ENTITY_KIND_OBJECT      EntityKind = 5
	EntityKind_ENTITY_KIND_PROJECTILE  EntityKind = 6
)

// Enum value maps for EntityKind.
var (
	EntityKind_name = map[int32]string{
		0: "ENTITY_KIND_UNSPECIFIED",
		1: "ENTITY_KIND_PLAYER",
		2: "ENTITY_KIND_MONSTER",
		3: "ENTITY_KIND_NPC",
		4: "ENTITY_KIND_BEAST",
		5: "ENTITY_KIND_OBJECT",
		6: "ENTITY_KIND_PROJECTILE",
	}
	EntityKind_value = map[string]int32{
		"ENTITY_KIND_UNSPECIFIED": 0,
		"ENTITY_KIND_PLAYER":      1,
		"ENTITY_KIND_MONSTER":     2,
		"ENTITY_KIND_NPC":         3,
		"ENTITY_KIND_BEAST":       4,
		"ENTITY_KIND_OBJECT":      5,
		"ENTITY_KIND_PROJECTILE":  6,
	}
)

func (x EntityKind) Enum() *EntityKind {
	p := new(EntityKind)
	*p = x
	return p
}

func (x EntityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[4].Descriptor()
}

func (EntityKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[4]
}

func (x EntityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityKind.Descriptor instead.
func (EntityKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{4}
}

type Facing int32

const (
	Facing_FACING_UNSPECIFIED Facing = 0
	Facing_FACING_LEFT        Facing = 1
	Facing_FACING_RIGHT       Facing = 2
)

// Enum value maps for Facing.
var (
	Facing_name = map[int32]string{
		0: "FACING_UNSPECIFIED",
		1: "FACING_LEFT",
		2: "FACING_RIGHT",
	}
	Facing_value = map[string]int32{
		"FACING_UNSPECIFIED": 0,
		"FACING_LEFT":        1,
		"FACING_RIGHT":       2,
	}
)

func (x Facing) Enum() *Facing {
	p := new(Facing)
	*p = x
	return p
}

func (x Facing) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Facing) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[5].Descriptor()
}

func (Facing) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[5]
}

func (x Facing) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Facing.Descriptor instead.
func (Facing) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{5}
}

type MovementState int32

const (
	MovementState_MOVEMENT_STATE_UNSPECIFIED MovementState = 0
	MovementState_MOVEMENT_STATE_IDLE        MovementState = 1
	MovementState_MOVEMENT_STATE_RUN         MovementState = 2
	MovementState_MOVEMENT_STATE_JUMP        MovementState = 3
	MovementState_MOVEMENT_STATE_FALL        MovementState = 4
	MovementState_MOVEMENT_STATE_KNOCKBACK   MovementState = 5
)

// Enum value maps for MovementState.
var (
	MovementState_name = map[int32]string{
		0: "MOVEMENT_STATE_UNSPECIFIED",
		1: "MOVEMENT_STATE_IDLE",
		2: "MOVEMENT_STATE_RUN",
		3: "MOVEMENT_STATE_JUMP",
		4: "MOVEMENT_STATE_FALL",
		5: "MOVEMENT_STATE_KNOCKBACK",
	}
	MovementState_value = map[string]int32{
		"MOVEMENT_STATE_UNSPECIFIED": 0,
		"MOVEMENT_STATE_IDLE":        1,
		"MOVEMENT_STATE_RUN":         2,
		"MOVEMENT_STATE_JUMP":        3,
		"MOVEMENT_STATE_FALL":        4,
		"MOVEMENT_STATE_KNOCKBACK":   5,
	}
)

func (x MovementState) Enum() *MovementState {
	p := new(MovementState)
	*p = x
	return p
}

func (x MovementState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[6].Descriptor()
}

func (MovementState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[6]
}

func (x MovementState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementState.Descriptor instead.
func (MovementState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{6}
}

type HeldHorizontalIntent int32

const (
	HeldHorizontalIntent_HELD_HORIZONTAL_INTENT_NONE  HeldHorizontalIntent = 0
	HeldHorizontalIntent_HELD_HORIZONTAL_INTENT_LEFT  HeldHorizontalIntent = 1
	HeldHorizontalIntent_HELD_HORIZONTAL_INTENT_RIGHT HeldHorizontalIntent = 2
)

// Enum value maps for HeldHorizontalIntent.
var (
	HeldHorizontalIntent_name = map[int32]string{
		0: "HELD_HORIZONTAL_INTENT_NONE",
		1: "HELD_HORIZONTAL_INTENT_LEFT",
		2: "HELD_HORIZONTAL_INTENT_RIGHT",
	}
	HeldHorizontalIntent_value = map[string]int32{
		"HELD_HORIZONTAL_INTENT_NONE":  0,
		"HELD_HORIZONTAL_INTENT_LEFT":  1,
		"HELD_HORIZONTAL_INTENT_RIGHT": 2,
	}
)

func (x HeldHorizontalIntent) Enum() *HeldHorizontalIntent {
	p := new(HeldHorizontalIntent)
	*p = x
	return p
}

func (x HeldHorizontalIntent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeldHorizontalIntent) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[7].Descriptor()
}

func (HeldHorizontalIntent) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[7]
}

func (x HeldHorizontalIntent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeldHorizontalIntent.Descriptor instead.
func (HeldHorizontalIntent) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{7}
}

type CosmeticSlot int32

const (
	CosmeticSlot_COSMETIC_SLOT_UNSPECIFIED             CosmeticSlot = 0
	CosmeticSlot_COSMETIC_SLOT_TITLE                   CosmeticSlot = 1
	CosmeticSlot_COSMETIC_SLOT_TITLE_GLOW              CosmeticSlot = 2
	CosmeticSlot_COSMETIC_SLOT_FRAME                   CosmeticSlot = 3
	CosmeticSlot_COSMETIC_SLOT_NAMEPLATE               CosmeticSlot = 4
	CosmeticSlot_COSMETIC_SLOT_APPEARANCE              CosmeticSlot = 5
	CosmeticSlot_COSMETIC_SLOT_WEAPON_TRAIL            CosmeticSlot = 6
	CosmeticSlot_COSMETIC_SLOT_AURA                    CosmeticSlot = 7
	CosmeticSlot_COSMETIC_SLOT_CHARACTER_SHRINE        CosmeticSlot = 8
	CosmeticSlot_COSMETIC_SLOT_GUILD_STONE_INSCRIPTION CosmeticSlot = 9
)

// Enum value maps for CosmeticSlot.
var (
	CosmeticSlot_name = map[int32]string{
		0: "COSMETIC_SLOT_UNSPECIFIED",
		1: "COSMETIC_SLOT_TITLE",
		2: "COSMETIC_SLOT_TITLE_GLOW",
		3: "COSMETIC_SLOT_FRAME",
		4: "COSMETIC_SLOT_NAMEPLATE",
		5: "COSMETIC_SLOT_APPEARANCE",
		6: "COSMETIC_SLOT_WEAPON_TRAIL",
		7: "COSMETIC_SLOT_AURA",
		8: "COSMETIC_SLOT_CHARACTER_SHRINE",
		9: "COSMETIC_SLOT_GUILD_STONE_INSCRIPTION",
	}
	CosmeticSlot_value = map[string]int32{
		"COSMETIC_SLOT_UNSPECIFIED":             0,
		"COSMETIC_SLOT_TITLE":                   1,
		"COSMETIC_SLOT_TITLE_GLOW":              2,
		"COSMETIC_SLOT_FRAME":                   3,
		"COSMETIC_SLOT_NAMEPLATE":               4,
		"COSMETIC_SLOT_APPEARANCE":              5,
		"COSMETIC_SLOT_WEAPON_TRAIL":            6,
		"COSMETIC_SLOT_AURA":                    7,
		"COSMETIC_SLOT_CHARACTER_SHRINE":        8,
		"COSMETIC_SLOT_GUILD_STONE_INSCRIPTION": 9,
	}
)

func (x CosmeticSlot) Enum() *CosmeticSlot {
	p := new(CosmeticSlot)
	*p = x
	return p
}

func (x CosmeticSlot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CosmeticSlot) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[8].Descriptor()
}

func (CosmeticSlot) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[8]
}

func (x CosmeticSlot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CosmeticSlot.Descriptor instead.
func (CosmeticSlot) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{8}
}

type RewardClaimState int32

const (
	RewardClaimState_REWARD_CLAIM_STATE_UNSPECIFIED RewardClaimState = 0
	RewardClaimState_REWARD_CLAIM_STATE_PENDING     RewardClaimState = 1
	RewardClaimState_REWARD_CLAIM_STATE_CLAIMED     RewardClaimState = 2
)

// Enum value maps for RewardClaimState.
var (
	RewardClaimState_name = map[int32]string{
		0: "REWARD_CLAIM_STATE_UNSPECIFIED",
		1: "REWARD_CLAIM_STATE_PENDING",
		2: "REWARD_CLAIM_STATE_CLAIMED",
	}
	RewardClaimState_value = map[string]int32{
		"REWARD_CLAIM_STATE_UNSPECIFIED": 0,
		"REWARD_CLAIM_STATE_PENDING":     1,
		"REWARD_CLAIM_STATE_CLAIMED":     2,
	}
)

func (x RewardClaimState) Enum() *RewardClaimState {
	p := new(RewardClaimState)
	*p = x
	return p
}

func (x RewardClaimState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RewardClaimState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_common_proto_enumTypes[9].Descriptor()
}

func (RewardClaimState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_common_proto_enumTypes[9]
}

func (x RewardClaimState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RewardClaimState.Descriptor instead.
func (RewardClaimState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{9}
}

type OperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	Status        ResultStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=thinhthan.v1.ResultStatus" json:"status,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *OperationResult) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *OperationResult) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_RESULT_STATUS_UNSPECIFIED
}

func (x *OperationResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

type ItemQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemQuantity) Reset() {
	*x = ItemQuantity{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemQuantity) ProtoMessage() {}

func (x *ItemQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemQuantity.ProtoReflect.Descriptor instead.
func (*ItemQuantity) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ItemQuantity) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemQuantity) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ItemGrant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemInstanceId []byte                 `protobuf:"bytes,1,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"` // UUID, 16 bytes
	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity       uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ItemGrant) Reset() {
	*x = ItemGrant{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGrant) ProtoMessage() {}

func (x *ItemGrant) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGrant.ProtoReflect.Descriptor instead.
func (*ItemGrant) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ItemGrant) GetItemInstanceId() []byte {
	if x != nil {
		return x.ItemInstanceId
	}
	return nil
}

func (x *ItemGrant) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemGrant) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CurrencyDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyId    string                 `protobuf:"bytes,1,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyDelta) Reset() {
	*x = CurrencyDelta{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyDelta) ProtoMessage() {}

func (x *CurrencyDelta) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyDelta.ProtoReflect.Descriptor instead.
func (*CurrencyDelta) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *CurrencyDelta) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *CurrencyDelta) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PositionMm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XMm           int32                  `protobuf:"zigzag32,1,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	YMm           int32                  `protobuf:"zigzag32,2,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionMm) Reset() {
	*x = PositionMm{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionMm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionMm) ProtoMessage() {}

func (x *PositionMm) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionMm.ProtoReflect.Descriptor instead.
func (*PositionMm) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PositionMm) GetXMm() int32 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *PositionMm) GetYMm() int32 {
	if x != nil {
		return x.YMm
	}
	return 0
}

type CharacterSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CharacterId    []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	CharacterName  string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	ClassId        string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Level          uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	MapId          string                 `protobuf:"bytes,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	LastOnlineAtMs int64                  `protobuf:"varint,6,opt,name=last_online_at_ms,json=lastOnlineAtMs,proto3" json:"last_online_at_ms,omitempty"`
	IsAttached     bool                   `protobuf:"varint,7,opt,name=is_attached,json=isAttached,proto3" json:"is_attached,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CharacterSummary) Reset() {
	*x = CharacterSummary{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSummary) ProtoMessage() {}

func (x *CharacterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSummary.ProtoReflect.Descriptor instead.
func (*CharacterSummary) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterSummary) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *CharacterSummary) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CharacterSummary) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *CharacterSummary) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterSummary) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *CharacterSummary) GetLastOnlineAtMs() int64 {
	if x != nil {
		return x.LastOnlineAtMs
	}
	return 0
}

func (x *CharacterSummary) GetIsAttached() bool {
	if x != nil {
		return x.IsAttached
	}
	return false
}

type EntityStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EffectId       string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	SourceEntityId uint64                 `protobuf:"varint,2,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	Stacks         uint32                 `protobuf:"varint,3,opt,name=stacks,proto3" json:"stacks,omitempty"`
	ExpiresAtTick  uint64                 `protobuf:"varint,4,opt,name=expires_at_tick,json=expiresAtTick,proto3" json:"expires_at_tick,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityStatus) Reset() {
	*x = EntityStatus{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStatus) ProtoMessage() {}

func (x *EntityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStatus.ProtoReflect.Descriptor instead.
func (*EntityStatus) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *EntityStatus) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *EntityStatus) GetSourceEntityId() uint64 {
	if x != nil {
		return x.SourceEntityId
	}
	return 0
}

func (x *EntityStatus) GetStacks() uint32 {
	if x != nil {
		return x.Stacks
	}
	return 0
}

func (x *EntityStatus) GetExpiresAtTick() uint64 {
	if x != nil {
		return x.ExpiresAtTick
	}
	return 0
}

type EquippedCosmetic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          CosmeticSlot           `protobuf:"varint,1,opt,name=slot,proto3,enum=thinhthan.v1.CosmeticSlot" json:"slot,omitempty"`
	CosmeticId    string                 `protobuf:"bytes,2,opt,name=cosmetic_id,json=cosmeticId,proto3" json:"cosmetic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquippedCosmetic) Reset() {
	*x = EquippedCosmetic{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquippedCosmetic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquippedCosmetic) ProtoMessage() {}

func (x *EquippedCosmetic) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquippedCosmetic.ProtoReflect.Descriptor instead.
func (*EquippedCosmetic) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *EquippedCosmetic) GetSlot() CosmeticSlot {
	if x != nil {
		return x.Slot
	}
	return CosmeticSlot_COSMETIC_SLOT_UNSPECIFIED
}

func (x *EquippedCosmetic) GetCosmeticId() string {
	if x != nil {
		return x.CosmeticId
	}
	return ""
}

type EntityState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EntityId            uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityKind          EntityKind             `protobuf:"varint,2,opt,name=entity_kind,json=entityKind,proto3,enum=thinhthan.v1.EntityKind" json:"entity_kind,omitempty"`
	ContentId           string                 `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	CharacterId         []byte                 `protobuf:"bytes,4,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	DisplayName         string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Level               uint32                 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	OwnerEntityId       uint64                 `protobuf:"varint,7,opt,name=owner_entity_id,json=ownerEntityId,proto3" json:"owner_entity_id,omitempty"`
	XMm                 int32                  `protobuf:"zigzag32,8,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	YMm                 int32                  `protobuf:"zigzag32,9,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	VxMmS               int32                  `protobuf:"zigzag32,10,opt,name=vx_mm_s,json=vxMmS,proto3" json:"vx_mm_s,omitempty"`
	VyMmS               int32                  `protobuf:"zigzag32,11,opt,name=vy_mm_s,json=vyMmS,proto3" json:"vy_mm_s,omitempty"`
	Facing              Facing                 `protobuf:"varint,12,opt,name=facing,proto3,enum=thinhthan.v1.Facing" json:"facing,omitempty"`
	MovementState       MovementState          `protobuf:"varint,13,opt,name=movement_state,json=movementState,proto3,enum=thinhthan.v1.MovementState" json:"movement_state,omitempty"`
	Hp                  int64                  `protobuf:"varint,14,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp               int64                  `protobuf:"varint,15,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Shield              int64                  `protobuf:"varint,16,opt,name=shield,proto3" json:"shield,omitempty"`
	Flags               uint32                 `protobuf:"varint,17,opt,name=flags,proto3" json:"flags,omitempty"`
	Statuses            []*EntityStatus        `protobuf:"bytes,18,rep,name=statuses,proto3" json:"statuses,omitempty"`
	EquippedCosmetics   []*EquippedCosmetic    `protobuf:"bytes,19,rep,name=equipped_cosmetics,json=equippedCosmetics,proto3" json:"equipped_cosmetics,omitempty"`
	EncounterId         uint64                 `protobuf:"varint,20,opt,name=encounter_id,json=encounterId,proto3" json:"encounter_id,omitempty"`
	StatLifesteal       uint32                 `protobuf:"varint,21,opt,name=stat_lifesteal,json=statLifesteal,proto3" json:"stat_lifesteal,omitempty"`
	StatReflect         uint32                 `protobuf:"varint,22,opt,name=stat_reflect,json=statReflect,proto3" json:"stat_reflect,omitempty"`
	StatAbsorb          uint32                 `protobuf:"varint,23,opt,name=stat_absorb,json=statAbsorb,proto3" json:"stat_absorb,omitempty"`
	StatHealReduction   uint32                 `protobuf:"varint,24,opt,name=stat_heal_reduction,json=statHealReduction,proto3" json:"stat_heal_reduction,omitempty"`
	StatHealingReceived uint32                 `protobuf:"varint,25,opt,name=stat_healing_received,json=statHealingReceived,proto3" json:"stat_healing_received,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *EntityState) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetEntityKind() EntityKind {
	if x != nil {
		return x.EntityKind
	}
	return EntityKind_ENTITY_KIND_UNSPECIFIED
}

func (x *EntityState) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *EntityState) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *EntityState) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EntityState) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EntityState) GetOwnerEntityId() uint64 {
	if x != nil {
		return x.OwnerEntityId
	}
	return 0
}

func (x *EntityState) GetXMm() int32 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *EntityState) GetYMm() int32 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *EntityState) GetVxMmS() int32 {
	if x != nil {
		return x.VxMmS
	}
	return 0
}

func (x *EntityState) GetVyMmS() int32 {
	if x != nil {
		return x.VyMmS
	}
	return 0
}

func (x *EntityState) GetFacing() Facing {
	if x != nil {
		return x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *EntityState) GetMovementState() MovementState {
	if x != nil {
		return x.MovementState
	}
	return MovementState_MOVEMENT_STATE_UNSPECIFIED
}

func (x *EntityState) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityState) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EntityState) GetShield() int64 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *EntityState) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *EntityState) GetStatuses() []*EntityStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *EntityState) GetEquippedCosmetics() []*EquippedCosmetic {
	if x != nil {
		return x.EquippedCosmetics
	}
	return nil
}

func (x *EntityState) GetEncounterId() uint64 {
	if x != nil {
		return x.EncounterId
	}
	return 0
}

func (x *EntityState) GetStatLifesteal() uint32 {
	if x != nil {
		return x.StatLifesteal
	}
	return 0
}

func (x *EntityState) GetStatReflect() uint32 {
	if x != nil {
		return x.StatReflect
	}
	return 0
}

func (x *EntityState) GetStatAbsorb() uint32 {
	if x != nil {
		return x.StatAbsorb
	}
	return 0
}

func (x *EntityState) GetStatHealReduction() uint32 {
	if x != nil {
		return x.StatHealReduction
	}
	return 0
}

func (x *EntityState) GetStatHealingReceived() uint32 {
	if x != nil {
		return x.StatHealingReceived
	}
	return 0
}

type RewardClaimLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Grant:
	//
	//	*RewardClaimLine_ItemId
	//	*RewardClaimLine_CurrencyId
	Grant         isRewardClaimLine_Grant `protobuf_oneof:"grant"`
	Quantity      uint32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardClaimLine) Reset() {
	*x = RewardClaimLine{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardClaimLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardClaimLine) ProtoMessage() {}

func (x *RewardClaimLine) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardClaimLine.ProtoReflect.Descriptor instead.
func (*RewardClaimLine) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *RewardClaimLine) GetGrant() isRewardClaimLine_Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *RewardClaimLine) GetItemId() string {
	if x != nil {
		if x, ok := x.Grant.(*RewardClaimLine_ItemId); ok {
			return x.ItemId
		}
	}
	return ""
}

func (x *RewardClaimLine) GetCurrencyId() string {
	if x != nil {
		if x, ok := x.Grant.(*RewardClaimLine_CurrencyId); ok {
			return x.CurrencyId
		}
	}
	return ""
}

func (x *RewardClaimLine) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type isRewardClaimLine_Grant interface {
	isRewardClaimLine_Grant()
}

type RewardClaimLine_ItemId struct {
	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3,oneof"`
}

type RewardClaimLine_CurrencyId struct {
	CurrencyId string `protobuf:"bytes,2,opt,name=currency_id,json=currencyId,proto3,oneof"`
}

func (*RewardClaimLine_ItemId) isRewardClaimLine_Grant() {}

func (*RewardClaimLine_CurrencyId) isRewardClaimLine_Grant() {}

type RewardClaimView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RewardClaimId   []byte                 `protobuf:"bytes,1,opt,name=reward_claim_id,json=rewardClaimId,proto3" json:"reward_claim_id,omitempty"` // UUID, 16 bytes
	SourceType      string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceReference string                 `protobuf:"bytes,3,opt,name=source_reference,json=sourceReference,proto3" json:"source_reference,omitempty"`
	RewardSlot      string                 `protobuf:"bytes,4,opt,name=reward_slot,json=rewardSlot,proto3" json:"reward_slot,omitempty"`
	State           RewardClaimState       `protobuf:"varint,5,opt,name=state,proto3,enum=thinhthan.v1.RewardClaimState" json:"state,omitempty"`
	Lines           []*RewardClaimLine     `protobuf:"bytes,6,rep,name=lines,proto3" json:"lines,omitempty"`
	CreatedAtMs     int64                  `protobuf:"varint,7,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	ExpiresAtMs     int64                  `protobuf:"varint,8,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RewardClaimView) Reset() {
	*x = RewardClaimView{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardClaimView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardClaimView) ProtoMessage() {}

func (x *RewardClaimView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardClaimView.ProtoReflect.Descriptor instead.
func (*RewardClaimView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *RewardClaimView) GetRewardClaimId() []byte {
	if x != nil {
		return x.RewardClaimId
	}
	return nil
}

func (x *RewardClaimView) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *RewardClaimView) GetSourceReference() string {
	if x != nil {
		return x.SourceReference
	}
	return ""
}

func (x *RewardClaimView) GetRewardSlot() string {
	if x != nil {
		return x.RewardSlot
	}
	return ""
}

func (x *RewardClaimView) GetState() RewardClaimState {
	if x != nil {
		return x.State
	}
	return RewardClaimState_REWARD_CLAIM_STATE_UNSPECIFIED
}

func (x *RewardClaimView) GetLines() []*RewardClaimLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *RewardClaimView) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *RewardClaimView) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

type EffectiveMovementParameters struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunSpeedMmS     uint32                 `protobuf:"varint,1,opt,name=run_speed_mm_s,json=runSpeedMmS,proto3" json:"run_speed_mm_s,omitempty"`
	FirstJumpMmS    uint32                 `protobuf:"varint,2,opt,name=first_jump_mm_s,json=firstJumpMmS,proto3" json:"first_jump_mm_s,omitempty"`
	SecondJumpMmS   uint32                 `protobuf:"varint,3,opt,name=second_jump_mm_s,json=secondJumpMmS,proto3" json:"second_jump_mm_s,omitempty"`
	GravityMmS2     uint32                 `protobuf:"varint,4,opt,name=gravity_mm_s2,json=gravityMmS2,proto3" json:"gravity_mm_s2,omitempty"`
	MaxFallMmS      uint32                 `protobuf:"varint,5,opt,name=max_fall_mm_s,json=maxFallMmS,proto3" json:"max_fall_mm_s,omitempty"`
	AirControlBp    uint32                 `protobuf:"varint,6,opt,name=air_control_bp,json=airControlBp,proto3" json:"air_control_bp,omitempty"`
	MaxStepHeightMm uint32                 `protobuf:"varint,7,opt,name=max_step_height_mm,json=maxStepHeightMm,proto3" json:"max_step_height_mm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EffectiveMovementParameters) Reset() {
	*x = EffectiveMovementParameters{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveMovementParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveMovementParameters) ProtoMessage() {}

func (x *EffectiveMovementParameters) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveMovementParameters.ProtoReflect.Descriptor instead.
func (*EffectiveMovementParameters) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *EffectiveMovementParameters) GetRunSpeedMmS() uint32 {
	if x != nil {
		return x.RunSpeedMmS
	}
	return 0
}

func (x *EffectiveMovementParameters) GetFirstJumpMmS() uint32 {
	if x != nil {
		return x.FirstJumpMmS
	}
	return 0
}

func (x *EffectiveMovementParameters) GetSecondJumpMmS() uint32 {
	if x != nil {
		return x.SecondJumpMmS
	}
	return 0
}

func (x *EffectiveMovementParameters) GetGravityMmS2() uint32 {
	if x != nil {
		return x.GravityMmS2
	}
	return 0
}

func (x *EffectiveMovementParameters) GetMaxFallMmS() uint32 {
	if x != nil {
		return x.MaxFallMmS
	}
	return 0
}

func (x *EffectiveMovementParameters) GetAirControlBp() uint32 {
	if x != nil {
		return x.AirControlBp
	}
	return 0
}

func (x *EffectiveMovementParameters) GetMaxStepHeightMm() uint32 {
	if x != nil {
		return x.MaxStepHeightMm
	}
	return 0
}

type MovementCheckpoint struct {
	state                protoimpl.MessageState       `protogen:"open.v1"`
	XMm                  int32                        `protobuf:"zigzag32,1,opt,name=x_mm,json=xMm,proto3" json:"x_mm,omitempty"`
	YMm                  int32                        `protobuf:"zigzag32,2,opt,name=y_mm,json=yMm,proto3" json:"y_mm,omitempty"`
	VxMmS                int32                        `protobuf:"zigzag32,3,opt,name=vx_mm_s,json=vxMmS,proto3" json:"vx_mm_s,omitempty"`
	VyMmS                int32                        `protobuf:"zigzag32,4,opt,name=vy_mm_s,json=vyMmS,proto3" json:"vy_mm_s,omitempty"`
	Facing               Facing                       `protobuf:"varint,5,opt,name=facing,proto3,enum=thinhthan.v1.Facing" json:"facing,omitempty"`
	MovementState        MovementState                `protobuf:"varint,6,opt,name=movement_state,json=movementState,proto3,enum=thinhthan.v1.MovementState" json:"movement_state,omitempty"`
	PlatformId           uint64                       `protobuf:"varint,7,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // 0 = none
	IsGrounded           bool                         `protobuf:"varint,8,opt,name=is_grounded,json=isGrounded,proto3" json:"is_grounded,omitempty"`
	JumpCount            uint32                       `protobuf:"varint,9,opt,name=jump_count,json=jumpCount,proto3" json:"jump_count,omitempty"`                                       // 0..2
	DropIgnorePlatformId uint64                       `protobuf:"varint,10,opt,name=drop_ignore_platform_id,json=dropIgnorePlatformId,proto3" json:"drop_ignore_platform_id,omitempty"` // 0 = none
	DropIgnoreUntilTick  uint64                       `protobuf:"varint,11,opt,name=drop_ignore_until_tick,json=dropIgnoreUntilTick,proto3" json:"drop_ignore_until_tick,omitempty"`    // 0 = none
	HeldHorizontalIntent HeldHorizontalIntent         `protobuf:"varint,12,opt,name=held_horizontal_intent,json=heldHorizontalIntent,proto3,enum=thinhthan.v1.HeldHorizontalIntent" json:"held_horizontal_intent,omitempty"`
	EffectiveParameters  *EffectiveMovementParameters `protobuf:"bytes,13,opt,name=effective_parameters,json=effectiveParameters,proto3" json:"effective_parameters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MovementCheckpoint) Reset() {
	*x = MovementCheckpoint{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementCheckpoint) ProtoMessage() {}

func (x *MovementCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementCheckpoint.ProtoReflect.Descriptor instead.
func (*MovementCheckpoint) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *MovementCheckpoint) GetXMm() int32 {
	if x != nil {
		return x.XMm
	}
	return 0
}

func (x *MovementCheckpoint) GetYMm() int32 {
	if x != nil {
		return x.YMm
	}
	return 0
}

func (x *MovementCheckpoint) GetVxMmS() int32 {
	if x != nil {
		return x.VxMmS
	}
	return 0
}

func (x *MovementCheckpoint) GetVyMmS() int32 {
	if x != nil {
		return x.VyMmS
	}
	return 0
}

func (x *MovementCheckpoint) GetFacing() Facing {
	if x != nil {
		return x.Facing
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *MovementCheckpoint) GetMovementState() MovementState {
	if x != nil {
		return x.MovementState
	}
	return MovementState_MOVEMENT_STATE_UNSPECIFIED
}

func (x *MovementCheckpoint) GetPlatformId() uint64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *MovementCheckpoint) GetIsGrounded() bool {
	if x != nil {
		return x.IsGrounded
	}
	return false
}

func (x *MovementCheckpoint) GetJumpCount() uint32 {
	if x != nil {
		return x.JumpCount
	}
	return 0
}

func (x *MovementCheckpoint) GetDropIgnorePlatformId() uint64 {
	if x != nil {
		return x.DropIgnorePlatformId
	}
	return 0
}

func (x *MovementCheckpoint) GetDropIgnoreUntilTick() uint64 {
	if x != nil {
		return x.DropIgnoreUntilTick
	}
	return 0
}

func (x *MovementCheckpoint) GetHeldHorizontalIntent() HeldHorizontalIntent {
	if x != nil {
		return x.HeldHorizontalIntent
	}
	return HeldHorizontalIntent_HELD_HORIZONTAL_INTENT_NONE
}

func (x *MovementCheckpoint) GetEffectiveParameters() *EffectiveMovementParameters {
	if x != nil {
		return x.EffectiveParameters
	}
	return nil
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor uint32                 `protobuf:"varint,2,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	MessageId     uint32                 `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SessionEpoch  uint64                 `protobuf:"varint,4,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	ClientSeq     uint64                 `protobuf:"varint,5,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	ServerSeq     uint64                 `protobuf:"varint,6,opt,name=server_seq,json=serverSeq,proto3" json:"server_seq,omitempty"`
	CorrelationId uint64                 `protobuf:"varint,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_thinhthan_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_common_proto_rawDescGZIP(), []int{13}
}

func (x *Envelope) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *Envelope) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *Envelope) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Envelope) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *Envelope) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *Envelope) GetServerSeq() uint64 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

func (x *Envelope) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_thinhthan_v1_common_proto protoreflect.FileDescriptor

const file_thinhthan_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19thinhthan/v1/common.proto\x12\fthinhthan.v1\"\xa0\x01\n" +
	"\x0fOperationResult\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.thinhthan.v1.ResultStatusR\x06status\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"C\n" +
	"\fItemQuantity\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"j\n" +
	"\tItemGrant\x12(\n" +
	"\x10item_instance_id\x18\x01 \x01(\fR\x0eitemInstanceId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"H\n" +
	"\rCurrencyDelta\x12\x1f\n" +
	"\vcurrency_id\x18\x01 \x01(\tR\n" +
	"currencyId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"2\n" +
	"\n" +
	"PositionMm\x12\x11\n" +
	"\x04x_mm\x18\x01 \x01(\x11R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x02 \x01(\x11R\x03yMm\"\xf0\x01\n" +
	"\x10CharacterSummary\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x15\n" +
	"\x06map_id\x18\x05 \x01(\tR\x05mapId\x12)\n" +
	"\x11last_online_at_ms\x18\x06 \x01(\x03R\x0elastOnlineAtMs\x12\x1f\n" +
	"\vis_attached\x18\a \x01(\bR\n" +
	"isAttached\"\x95\x01\n" +
	"\fEntityStatus\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12(\n" +
	"\x10source_entity_id\x18\x02 \x01(\x04R\x0esourceEntityId\x12\x16\n" +
	"\x06stacks\x18\x03 \x01(\rR\x06stacks\x12&\n" +
	"\x0fexpires_at_tick\x18\x04 \x01(\x04R\rexpiresAtTick\"c\n" +
	"\x10EquippedCosmetic\x12.\n" +
	"\x04slot\x18\x01 \x01(\x0e2\x1a.thinhthan.v1.CosmeticSlotR\x04slot\x12\x1f\n" +
	"\vcosmetic_id\x18\x02 \x01(\tR\n" +
	"cosmeticId\"\x9e\a\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x129\n" +
	"\ventity_kind\x18\x02 \x01(\x0e2\x18.thinhthan.v1.EntityKindR\n" +
	"entityKind\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\x12!\n" +
	"\fcharacter_id\x18\x04 \x01(\fR\vcharacterId\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05level\x18\x06 \x01(\rR\x05level\x12&\n" +
	"\x0fowner_entity_id\x18\a \x01(\x04R\rownerEntityId\x12\x11\n" +
	"\x04x_mm\x18\b \x01(\x11R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\t \x01(\x11R\x03yMm\x12\x16\n" +
	"\avx_mm_s\x18\n" +
	" \x01(\x11R\x05vxMmS\x12\x16\n" +
	"\avy_mm_s\x18\v \x01(\x11R\x05vyMmS\x12,\n" +
	"\x06facing\x18\f \x01(\x0e2\x14.thinhthan.v1.FacingR\x06facing\x12B\n" +
	"\x0emovement_state\x18\r \x01(\x0e2\x1b.thinhthan.v1.MovementStateR\rmovementState\x12\x0e\n" +
	"\x02hp\x18\x0e \x01(\x03R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x0f \x01(\x03R\x05maxHp\x12\x16\n" +
	"\x06shield\x18\x10 \x01(\x03R\x06shield\x12\x14\n" +
	"\x05flags\x18\x11 \x01(\rR\x05flags\x126\n" +
	"\bstatuses\x18\x12 \x03(\v2\x1a.thinhthan.v1.EntityStatusR\bstatuses\x12M\n" +
	"\x12equipped_cosmetics\x18\x13 \x03(\v2\x1e.thinhthan.v1.EquippedCosmeticR\x11equippedCosmetics\x12!\n" +
	"\fencounter_id\x18\x14 \x01(\x04R\vencounterId\x12%\n" +
	"\x0estat_lifesteal\x18\x15 \x01(\rR\rstatLifesteal\x12!\n" +
	"\fstat_reflect\x18\x16 \x01(\rR\vstatReflect\x12\x1f\n" +
	"\vstat_absorb\x18\x17 \x01(\rR\n" +
	"statAbsorb\x12.\n" +
	"\x13stat_heal_reduction\x18\x18 \x01(\rR\x11statHealReduction\x122\n" +
	"\x15stat_healing_received\x18\x19 \x01(\rR\x13statHealingReceived\"t\n" +
	"\x0fRewardClaimLine\x12\x19\n" +
	"\aitem_id\x18\x01 \x01(\tH\x00R\x06itemId\x12!\n" +
	"\vcurrency_id\x18\x02 \x01(\tH\x00R\n" +
	"currencyId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantityB\a\n" +
	"\x05grant\"\xd9\x02\n" +
	"\x0fRewardClaimView\x12&\n" +
	"\x0freward_claim_id\x18\x01 \x01(\fR\rrewardClaimId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12)\n" +
	"\x10source_reference\x18\x03 \x01(\tR\x0fsourceReference\x12\x1f\n" +
	"\vreward_slot\x18\x04 \x01(\tR\n" +
	"rewardSlot\x124\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1e.thinhthan.v1.RewardClaimStateR\x05state\x123\n" +
	"\x05lines\x18\x06 \x03(\v2\x1d.thinhthan.v1.RewardClaimLineR\x05lines\x12\"\n" +
	"\rcreated_at_ms\x18\a \x01(\x03R\vcreatedAtMs\x12\"\n" +
	"\rexpires_at_ms\x18\b \x01(\x03R\vexpiresAtMs\"\xac\x02\n" +
	"\x1bEffectiveMovementParameters\x12#\n" +
	"\x0erun_speed_mm_s\x18\x01 \x01(\rR\vrunSpeedMmS\x12%\n" +
	"\x0ffirst_jump_mm_s\x18\x02 \x01(\rR\ffirstJumpMmS\x12'\n" +
	"\x10second_jump_mm_s\x18\x03 \x01(\rR\rsecondJumpMmS\x12\"\n" +
	"\rgravity_mm_s2\x18\x04 \x01(\rR\vgravityMmS2\x12!\n" +
	"\rmax_fall_mm_s\x18\x05 \x01(\rR\n" +
	"maxFallMmS\x12$\n" +
	"\x0eair_control_bp\x18\x06 \x01(\rR\fairControlBp\x12+\n" +
	"\x12max_step_height_mm\x18\a \x01(\rR\x0fmaxStepHeightMm\"\xe1\x04\n" +
	"\x12MovementCheckpoint\x12\x11\n" +
	"\x04x_mm\x18\x01 \x01(\x11R\x03xMm\x12\x11\n" +
	"\x04y_mm\x18\x02 \x01(\x11R\x03yMm\x12\x16\n" +
	"\avx_mm_s\x18\x03 \x01(\x11R\x05vxMmS\x12\x16\n" +
	"\avy_mm_s\x18\x04 \x01(\x11R\x05vyMmS\x12,\n" +
	"\x06facing\x18\x05 \x01(\x0e2\x14.thinhthan.v1.FacingR\x06facing\x12B\n" +
	"\x0emovement_state\x18\x06 \x01(\x0e2\x1b.thinhthan.v1.MovementStateR\rmovementState\x12\x1f\n" +
	"\vplatform_id\x18\a \x01(\x04R\n" +
	"platformId\x12\x1f\n" +
	"\vis_grounded\x18\b \x01(\bR\n" +
	"isGrounded\x12\x1d\n" +
	"\n" +
	"jump_count\x18\t \x01(\rR\tjumpCount\x125\n" +
	"\x17drop_ignore_platform_id\x18\n" +
	" \x01(\x04R\x14dropIgnorePlatformId\x123\n" +
	"\x16drop_ignore_until_tick\x18\v \x01(\x04R\x13dropIgnoreUntilTick\x12X\n" +
	"\x16held_horizontal_intent\x18\f \x01(\x0e2\".thinhthan.v1.HeldHorizontalIntentR\x14heldHorizontalIntent\x12\\\n" +
	"\x14effective_parameters\x18\r \x01(\v2).thinhthan.v1.EffectiveMovementParametersR\x13effectiveParameters\"\x9b\x02\n" +
	"\bEnvelope\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x02 \x01(\rR\rprotocolMinor\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\rR\tmessageId\x12#\n" +
	"\rsession_epoch\x18\x04 \x01(\x04R\fsessionEpoch\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x05 \x01(\x04R\tclientSeq\x12\x1d\n" +
	"\n" +
	"server_seq\x18\x06 \x01(\x04R\tserverSeq\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\x04R\rcorrelationId\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload*\xa6\x1f\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dERROR_CODE_PROTOCOL_MALFORMED\x10\x01\x12#\n" +
	"\x1fERROR_CODE_PROTOCOL_UNSUPPORTED\x10\x02\x12!\n" +
	"\x1dERROR_CODE_PROTOCOL_VIOLATION\x10\x03\x12\x1e\n" +
	"\x1aERROR_CODE_MESSAGE_UNKNOWN\x10\x04\x12 \n" +
	"\x1cERROR_CODE_MESSAGE_TOO_LARGE\x10\x05\x12+\n" +
	"'ERROR_CODE_MESSAGE_NOT_ALLOWED_IN_STATE\x10\x06\x12%\n" +
	"!ERROR_CODE_CLIENT_UPDATE_REQUIRED\x10\a\x12#\n" +
	"\x1fERROR_CODE_CONTENT_INCOMPATIBLE\x10\b\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\t\x12 \n" +
	"\x1cERROR_CODE_SERVER_OVERLOADED\x10\n" +
	"\x12\x1e\n" +
	"\x1aERROR_CODE_SERVER_DRAINING\x10\v\x12\x1c\n" +
	"\x18ERROR_CODE_AUTH_REQUIRED\x10\f\x12\x1b\n" +
	"\x17ERROR_CODE_AUTH_INVALID\x10\r\x12\x1b\n" +
	"\x17ERROR_CODE_AUTH_EXPIRED\x10\x0e\x12\"\n" +
	"\x1eERROR_CODE_SESSION_EPOCH_STALE\x10\x0f\x12\x1f\n" +
	"\x1bERROR_CODE_SESSION_REPLACED\x10\x10\x12'\n" +
	"#ERROR_CODE_CHARACTER_ALREADY_ACTIVE\x10\x11\x12\x1d\n" +
	"\x19ERROR_CODE_RESUME_EXPIRED\x10\x12\x12\x1d\n" +
	"\x19ERROR_CODE_ACCOUNT_BANNED\x10\x13\x12'\n" +
	"#ERROR_CODE_ACCOUNT_PENDING_DELETION\x10\x14\x12 \n" +
	"\x1cERROR_CODE_ACCOUNT_SUSPENDED\x10\x15\x12\"\n" +
	"\x1eERROR_CODE_ENTITLEMENT_REVOKED\x10\x16\x12\x1f\n" +
	"\x1bERROR_CODE_USERNAME_INVALID\x10\x17\x12\x1c\n" +
	"\x18ERROR_CODE_EMAIL_INVALID\x10\x18\x12\x1f\n" +
	"\x1bERROR_CODE_PASSWORD_INVALID\x10\x19\x12\x1d\n" +
	"\x19ERROR_CODE_USERNAME_TAKEN\x10\x1a\x12\x1a\n" +
	"\x16ERROR_CODE_EMAIL_TAKEN\x10\x1b\x12&\n" +
	"\"ERROR_CODE_PROVIDER_ALREADY_LINKED\x10\x1c\x12 \n" +
	"\x1cERROR_CODE_LAST_LOGIN_METHOD\x10\x1d\x12'\n" +
	"#ERROR_CODE_CREDENTIAL_CHANGE_LOCKED\x10\x1e\x12%\n" +
	"!ERROR_CODE_CHARACTER_NAME_INVALID\x10\x1f\x12#\n" +
	"\x1fERROR_CODE_CHARACTER_NAME_TAKEN\x10 \x12#\n" +
	"\x1fERROR_CODE_CHARACTER_SLOTS_FULL\x10!\x12\x1e\n" +
	"\x1aERROR_CODE_OWNER_NOT_FOUND\x10\"\x12\x1c\n" +
	"\x18ERROR_CODE_OWNER_CHANGED\x10#\x12#\n" +
	"\x1fERROR_CODE_TRANSFER_IN_PROGRESS\x10$\x12\x1e\n" +
	"\x1aERROR_CODE_TRANSFER_FAILED\x10%\x12\x1a\n" +
	"\x16ERROR_CODE_STALE_INPUT\x10&\x12\x1d\n" +
	"\x19ERROR_CODE_INVALID_TARGET\x10'\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_STATE\x10(\x12 \n" +
	"\x1cERROR_CODE_MAP_CAPACITY_FULL\x10)\x12!\n" +
	"\x1dERROR_CODE_OPERATION_CONFLICT\x10*\x12$\n" +
	" ERROR_CODE_OPERATION_IN_PROGRESS\x10+\x12!\n" +
	"\x1dERROR_CODE_OPERATION_REJECTED\x10,\x12+\n" +
	"'ERROR_CODE_TEMPORARY_DEPENDENCY_FAILURE\x10-\x12+\n" +
	"'ERROR_CODE_IAP_RECEIPT_ACCOUNT_MISMATCH\x10.\x12#\n" +
	"\x1fERROR_CODE_IAP_PRODUCT_MISMATCH\x10/\x12\"\n" +
	"\x1eERROR_CODE_IAP_RECEIPT_INVALID\x100\x12)\n" +
	"%ERROR_CODE_IAP_SEASON_TRACK_DUPLICATE\x101\x12'\n" +
	"#ERROR_CODE_IAP_VERIFICATION_PENDING\x102\x12(\n" +
	"$ERROR_CODE_CHEST_ELIGIBILITY_INVALID\x103\x12)\n" +
	"%ERROR_CODE_TRADE_PARTNER_DISCONNECTED\x104\x12/\n" +
	"+ERROR_CODE_TRADE_ELIGIBILITY_LEVEL_REQUIRED\x105\x12-\n" +
	")ERROR_CODE_TRADE_ELIGIBILITY_AGE_REQUIRED\x106\x12,\n" +
	"(ERROR_CODE_AH_ELIGIBILITY_LEVEL_REQUIRED\x107\x12*\n" +
	"&ERROR_CODE_AH_ELIGIBILITY_AGE_REQUIRED\x108\x12&\n" +
	"\"ERROR_CODE_TRADE_COMMON_BOTH_SIDES\x109\x12(\n" +
	"$ERROR_CODE_TRADE_PRICE_FLOOR_NOT_MET\x10:\x12%\n" +
	"!ERROR_CODE_AH_PRICE_FLOOR_NOT_MET\x10;\x12%\n" +
	"!ERROR_CODE_SAME_ACCOUNT_FORBIDDEN\x10<\x12\x1d\n" +
	"\x19ERROR_CODE_INVENTORY_FULL\x10=\x12$\n" +
	" ERROR_CODE_INSUFFICIENT_CURRENCY\x10>\x12$\n" +
	" ERROR_CODE_CURRENCY_CAP_EXCEEDED\x10?\x12\x1e\n" +
	"\x1aERROR_CODE_COOLDOWN_ACTIVE\x10@\x12\x1d\n" +
	"\x19ERROR_CODE_ITEM_NOT_FOUND\x10A\x12\x1a\n" +
	"\x16ERROR_CODE_ITEM_LOCKED\x10B\x12\x18\n" +
	"\x14ERROR_CODE_NOT_OWNER\x10C\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10D\x12\x1d\n" +
	"\x19ERROR_CODE_TARGET_INVALID\x10E\x12\x1b\n" +
	"\x17ERROR_CODE_OUT_OF_RANGE\x10F\x12\x18\n" +
	"\x14ERROR_CODE_IN_COMBAT\x10G\x12\x1c\n" +
	"\x18ERROR_CODE_LEVEL_TOO_LOW\x10H\x12\x1c\n" +
	"\x18ERROR_CODE_CAPACITY_FULL\x10I\x12\x1c\n" +
	"\x18ERROR_CODE_ALREADY_OWNED\x10J\x12\x16\n" +
	"\x12ERROR_CODE_EXPIRED\x10K\x12\x1d\n" +
	"\x19ERROR_CODE_STATE_CONFLICT\x10L\x12!\n" +
	"\x1dERROR_CODE_NOT_IN_SAFE_ANCHOR\x10M\x12\"\n" +
	"\x1eERROR_CODE_DAILY_LIMIT_REACHED\x10N\x12$\n" +
	" ERROR_CODE_GUILD_DISBAND_BLOCKED\x10O\x12)\n" +
	"%ERROR_CODE_GUILD_STORAGE_SAME_ACCOUNT\x10P\x12'\n" +
	"#ERROR_CODE_GUILD_MEMBERSHIP_TOO_NEW\x10Q\x12)\n" +
	"%ERROR_CODE_AUCTION_LISTING_NOT_ACTIVE\x10R\x12\"\n" +
	"\x1eERROR_CODE_CLAIM_WINDOW_CLOSED\x10S\x12#\n" +
	"\x1fERROR_CODE_DURABLE_BACKPRESSURE\x10T\x12\x1e\n" +
	"\x1aERROR_CODE_BEAST_NOT_OWNED\x10U\x12\x1c\n" +
	"\x18ERROR_CODE_SLOT_MISMATCH\x10V\x12\x19\n" +
	"\x15ERROR_CODE_SLOT_EMPTY\x10W\x12 \n" +
	"\x1cERROR_CODE_INSUFFICIENT_ITEM\x10X\x12%\n" +
	"!ERROR_CODE_DAILY_FOOD_CAP_REACHED\x10Y\x12\x1f\n" +
	"\x1bERROR_CODE_MAX_BOND_REACHED\x10Z\x12#\n" +
	"\x1fERROR_CODE_FRIEND_LIMIT_REACHED\x10[\x12\x1d\n" +
	"\x19ERROR_CODE_TARGET_BLOCKED\x10\\\x12\x1e\n" +
	"\x1aERROR_CODE_ALREADY_FRIENDS\x10]\x12%\n" +
	"!ERROR_CODE_PENDING_REQUEST_EXISTS\x10^\x12 \n" +
	"\x1cERROR_CODE_CLAIM_CAP_REACHED\x10_\x12\x1f\n" +
	"\x1bERROR_CODE_CHARM_INELIGIBLE\x10`\x12 \n" +
	"\x1cERROR_CODE_SKILL_NOT_LEARNED\x10a\x12\x1e\n" +
	"\x1aERROR_CODE_SKILL_MAX_LEVEL\x10b\x12(\n" +
	"$ERROR_CODE_SKILL_POINTS_INSUFFICIENT\x10c\x12$\n" +
	" ERROR_CODE_SKILL_LOADOUT_INVALID\x10d\x12,\n" +
	"(ERROR_CODE_POTENTIAL_POINTS_INSUFFICIENT\x10e\x12%\n" +
	"!ERROR_CODE_POTENTIAL_CAP_EXCEEDED\x10f\x12\x1e\n" +
	"\x1aERROR_CODE_INSUFFICIENT_MP\x10g\x12*\n" +
	"&ERROR_CODE_SOUL_CONTRACT_LIMIT_REACHED\x10h\x12$\n" +
	" ERROR_CODE_STORY_CHOICE_REQUIRED\x10i\x12\x1d\n" +
	"\x19ERROR_CODE_NOT_DISCOVERED\x10j\x12\x1f\n" +
	"\x1bERROR_CODE_GUILD_NAME_TAKEN\x10k\x12!\n" +
	"\x1dERROR_CODE_GUILD_NAME_INVALID\x10l\x12%\n" +
	"!ERROR_CODE_ATLAS_TIER_NOT_REACHED\x10m\x12 \n" +
	"\x1cERROR_CODE_CHAT_TEXT_INVALID\x10n\x12 \n" +
	"\x1cERROR_CODE_OPERATION_EXPIRED\x10o\x12 \n" +
	"\x1cERROR_CODE_REQUEST_TOO_LARGE\x10p*\xe4\x01\n" +
	"\fRetryability\x12\x1c\n" +
	"\x18RETRYABILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RETRYABILITY_NEVER\x10\x01\x12%\n" +
	"!RETRYABILITY_RETRY_SAME_OPERATION\x10\x02\x12\x1a\n" +
	"\x16RETRYABILITY_RECONNECT\x10\x03\x12 \n" +
	"\x1cRETRYABILITY_UPDATE_REQUIRED\x10\x04\x12\x1f\n" +
	"\x1bRETRYABILITY_REAUTHENTICATE\x10\x05\x12\x18\n" +
	"\x14RETRYABILITY_BACKOFF\x10\x06*a\n" +
	"\fResultStatus\x12\x1d\n" +
	"\x19RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESULT_STATUS_SUCCESS\x10\x01\x12\x17\n" +
	"\x13RESULT_STATUS_ERROR\x10\x02*\x8e\x01\n" +
	"\aElement\x12\x17\n" +
	"\x13ELEMENT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vELEMENT_KIM\x10\x01\x12\x10\n" +
	"\fELEMENT_THUY\x10\x02\x12\x0f\n" +
	"\vELEMENT_MOC\x10\x03\x12\x0f\n" +
	"\vELEMENT_HOA\x10\x04\x12\x0f\n" +
	"\vELEMENT_THO\x10\x05\x12\x14\n" +
	"\x10ELEMENT_PHYSICAL\x10\x06*\xba\x01\n" +
	"\n" +
	"EntityKind\x12\x1b\n" +
	"\x17ENTITY_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENTITY_KIND_PLAYER\x10\x01\x12\x17\n" +
	"\x13ENTITY_KIND_MONSTER\x10\x02\x12\x13\n" +
	"\x0fENTITY_KIND_NPC\x10\x03\x12\x15\n" +
	"\x11ENTITY_KIND_BEAST\x10\x04\x12\x16\n" +
	"\x12ENTITY_KIND_OBJECT\x10\x05\x12\x1a\n" +
	"\x16ENTITY_KIND_PROJECTILE\x10\x06*C\n" +
	"\x06Facing\x12\x16\n" +
	"\x12FACING_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vFACING_LEFT\x10\x01\x12\x10\n" +
	"\fFACING_RIGHT\x10\x02*\xb0\x01\n" +
	"\rMovementState\x12\x1e\n" +
	"\x1aMOVEMENT_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MOVEMENT_STATE_IDLE\x10\x01\x12\x16\n" +
	"\x12MOVEMENT_STATE_RUN\x10\x02\x12\x17\n" +
	"\x13MOVEMENT_STATE_JUMP\x10\x03\x12\x17\n" +
	"\x13MOVEMENT_STATE_FALL\x10\x04\x12\x1c\n" +
	"\x18MOVEMENT_STATE_KNOCKBACK\x10\x05*z\n" +
	"\x14HeldHorizontalIntent\x12\x1f\n" +
	"\x1bHELD_HORIZONTAL_INTENT_NONE\x10\x00\x12\x1f\n" +
	"\x1bHELD_HORIZONTAL_INTENT_LEFT\x10\x01\x12 \n" +
	"\x1cHELD_HORIZONTAL_INTENT_RIGHT\x10\x02*\xbf\x02\n" +
	"\fCosmeticSlot\x12\x1d\n" +
	"\x19COSMETIC_SLOT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COSMETIC_SLOT_TITLE\x10\x01\x12\x1c\n" +
	"\x18COSMETIC_SLOT_TITLE_GLOW\x10\x02\x12\x17\n" +
	"\x13COSMETIC_SLOT_FRAME\x10\x03\x12\x1b\n" +
	"\x17COSMETIC_SLOT_NAMEPLATE\x10\x04\x12\x1c\n" +
	"\x18COSMETIC_SLOT_APPEARANCE\x10\x05\x12\x1e\n" +
	"\x1aCOSMETIC_SLOT_WEAPON_TRAIL\x10\x06\x12\x16\n" +
	"\x12COSMETIC_SLOT_AURA\x10\a\x12\"\n" +
	"\x1eCOSMETIC_SLOT_CHARACTER_SHRINE\x10\b\x12)\n" +
	"%COSMETIC_SLOT_GUILD_STONE_INSCRIPTION\x10\t*v\n" +
	"\x10RewardClaimState\x12\"\n" +
	"\x1eREWARD_CLAIM_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREWARD_CLAIM_STATE_PENDING\x10\x01\x12\x1e\n" +
	"\x1aREWARD_CLAIM_STATE_CLAIMED\x10\x02BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_common_proto_rawDescOnce sync.Once
	file_thinhthan_v1_common_proto_rawDescData []byte
)

func file_thinhthan_v1_common_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_common_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_common_proto_rawDesc), len(file_thinhthan_v1_common_proto_rawDesc)))
	})
	return file_thinhthan_v1_common_proto_rawDescData
}

var file_thinhthan_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_thinhthan_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_thinhthan_v1_common_proto_goTypes = []any{
	(ErrorCode)(0),                      // 0: thinhthan.v1.ErrorCode
	(Retryability)(0),                   // 1: thinhthan.v1.Retryability
	(ResultStatus)(0),                   // 2: thinhthan.v1.ResultStatus
	(Element)(0),                        // 3: thinhthan.v1.Element
	(EntityKind)(0),                     // 4: thinhthan.v1.EntityKind
	(Facing)(0),                         // 5: thinhthan.v1.Facing
	(MovementState)(0),                  // 6: thinhthan.v1.MovementState
	(HeldHorizontalIntent)(0),           // 7: thinhthan.v1.HeldHorizontalIntent
	(CosmeticSlot)(0),                   // 8: thinhthan.v1.CosmeticSlot
	(RewardClaimState)(0),               // 9: thinhthan.v1.RewardClaimState
	(*OperationResult)(nil),             // 10: thinhthan.v1.OperationResult
	(*ItemQuantity)(nil),                // 11: thinhthan.v1.ItemQuantity
	(*ItemGrant)(nil),                   // 12: thinhthan.v1.ItemGrant
	(*CurrencyDelta)(nil),               // 13: thinhthan.v1.CurrencyDelta
	(*PositionMm)(nil),                  // 14: thinhthan.v1.PositionMm
	(*CharacterSummary)(nil),            // 15: thinhthan.v1.CharacterSummary
	(*EntityStatus)(nil),                // 16: thinhthan.v1.EntityStatus
	(*EquippedCosmetic)(nil),            // 17: thinhthan.v1.EquippedCosmetic
	(*EntityState)(nil),                 // 18: thinhthan.v1.EntityState
	(*RewardClaimLine)(nil),             // 19: thinhthan.v1.RewardClaimLine
	(*RewardClaimView)(nil),             // 20: thinhthan.v1.RewardClaimView
	(*EffectiveMovementParameters)(nil), // 21: thinhthan.v1.EffectiveMovementParameters
	(*MovementCheckpoint)(nil),          // 22: thinhthan.v1.MovementCheckpoint
	(*Envelope)(nil),                    // 23: thinhthan.v1.Envelope
}
var file_thinhthan_v1_common_proto_depIdxs = []int32{
	2,  // 0: thinhthan.v1.OperationResult.status:type_name -> thinhthan.v1.ResultStatus
	0,  // 1: thinhthan.v1.OperationResult.error_code:type_name -> thinhthan.v1.ErrorCode
	8,  // 2: thinhthan.v1.EquippedCosmetic.slot:type_name -> thinhthan.v1.CosmeticSlot
	4,  // 3: thinhthan.v1.EntityState.entity_kind:type_name -> thinhthan.v1.EntityKind
	5,  // 4: thinhthan.v1.EntityState.facing:type_name -> thinhthan.v1.Facing
	6,  // 5: thinhthan.v1.EntityState.movement_state:type_name -> thinhthan.v1.MovementState
	16, // 6: thinhthan.v1.EntityState.statuses:type_name -> thinhthan.v1.EntityStatus
	17, // 7: thinhthan.v1.EntityState.equipped_cosmetics:type_name -> thinhthan.v1.EquippedCosmetic
	9,  // 8: thinhthan.v1.RewardClaimView.state:type_name -> thinhthan.v1.RewardClaimState
	19, // 9: thinhthan.v1.RewardClaimView.lines:type_name -> thinhthan.v1.RewardClaimLine
	5,  // 10: thinhthan.v1.MovementCheckpoint.facing:type_name -> thinhthan.v1.Facing
	6,  // 11: thinhthan.v1.MovementCheckpoint.movement_state:type_name -> thinhthan.v1.MovementState
	7,  // 12: thinhthan.v1.MovementCheckpoint.held_horizontal_intent:type_name -> thinhthan.v1.HeldHorizontalIntent
	21, // 13: thinhthan.v1.MovementCheckpoint.effective_parameters:type_name -> thinhthan.v1.EffectiveMovementParameters
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_common_proto_init() }
func file_thinhthan_v1_common_proto_init() {
	if File_thinhthan_v1_common_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_msgTypes[9].OneofWrappers = []any{
		(*RewardClaimLine_ItemId)(nil),
		(*RewardClaimLine_CurrencyId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_common_proto_rawDesc), len(file_thinhthan_v1_common_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_common_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_common_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_common_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_common_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_common_proto = out.File
	file_thinhthan_v1_common_proto_goTypes = nil
	file_thinhthan_v1_common_proto_depIdxs = nil
}
