// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/content.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestState int32

const (
	QuestState_QUEST_STATE_UNSPECIFIED       QuestState = 0
	QuestState_QUEST_STATE_LOCKED            QuestState = 1
	QuestState_QUEST_STATE_AVAILABLE         QuestState = 2
	QuestState_QUEST_STATE_ACTIVE            QuestState = 3
	QuestState_QUEST_STATE_READY_TO_COMPLETE QuestState = 4
	QuestState_QUEST_STATE_COMPLETED         QuestState = 5
	QuestState_QUEST_STATE_FAILED            QuestState = 6
	QuestState_QUEST_STATE_EXPIRED           QuestState = 7
)

// Enum value maps for QuestState.
var (
	QuestState_name = map[int32]string{
		0: "QUEST_STATE_UNSPECIFIED",
		1: "QUEST_STATE_LOCKED",
		2: "QUEST_STATE_AVAILABLE",
		3: "QUEST_STATE_ACTIVE",
		4: "QUEST_STATE_READY_TO_COMPLETE",
		5: "QUEST_STATE_COMPLETED",
		6: "QUEST_STATE_FAILED",
		7: "QUEST_STATE_EXPIRED",
	}
	QuestState_value = map[string]int32{
		"QUEST_STATE_UNSPECIFIED":       0,
		"QUEST_STATE_LOCKED":            1,
		"QUEST_STATE_AVAILABLE":         2,
		"QUEST_STATE_ACTIVE":            3,
		"QUEST_STATE_READY_TO_COMPLETE": 4,
		"QUEST_STATE_COMPLETED":         5,
		"QUEST_STATE_FAILED":            6,
		"QUEST_STATE_EXPIRED":           7,
	}
)

func (x QuestState) Enum() *QuestState {
	p := new(QuestState)
	*p = x
	return p
}

func (x QuestState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_content_proto_enumTypes[0].Descriptor()
}

func (QuestState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_content_proto_enumTypes[0]
}

func (x QuestState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestState.Descriptor instead.
func (QuestState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{0}
}

type ProgressionEventKind int32

const (
	ProgressionEventKind_PROGRESSION_EVENT_KIND_UNSPECIFIED    ProgressionEventKind = 0
	ProgressionEventKind_PROGRESSION_EVENT_KIND_EXP_GAINED     ProgressionEventKind = 1
	ProgressionEventKind_PROGRESSION_EVENT_KIND_LEVEL_UP       ProgressionEventKind = 2
	ProgressionEventKind_PROGRESSION_EVENT_KIND_SKILL_UNLOCKED ProgressionEventKind = 3
	ProgressionEventKind_PROGRESSION_EVENT_KIND_POINTS_GRANTED ProgressionEventKind = 4
	ProgressionEventKind_PROGRESSION_EVENT_KIND_FEAT_COMPLETED ProgressionEventKind = 5
	ProgressionEventKind_PROGRESSION_EVENT_KIND_ATLAS_TIER     ProgressionEventKind = 6
	ProgressionEventKind_PROGRESSION_EVENT_KIND_STORY_FLAG_SET ProgressionEventKind = 7
	ProgressionEventKind_PROGRESSION_EVENT_KIND_DISCOVERY      ProgressionEventKind = 8
)

// Enum value maps for ProgressionEventKind.
var (
	ProgressionEventKind_name = map[int32]string{
		0: "PROGRESSION_EVENT_KIND_UNSPECIFIED",
		1: "PROGRESSION_EVENT_KIND_EXP_GAINED",
		2: "PROGRESSION_EVENT_KIND_LEVEL_UP",
		3: "PROGRESSION_EVENT_KIND_SKILL_UNLOCKED",
		4: "PROGRESSION_EVENT_KIND_POINTS_GRANTED",
		5: "PROGRESSION_EVENT_KIND_FEAT_COMPLETED",
		6: "PROGRESSION_EVENT_KIND_ATLAS_TIER",
		7: "PROGRESSION_EVENT_KIND_STORY_FLAG_SET",
		8: "PROGRESSION_EVENT_KIND_DISCOVERY",
	}
	ProgressionEventKind_value = map[string]int32{
		"PROGRESSION_EVENT_KIND_UNSPECIFIED":    0,
		"PROGRESSION_EVENT_KIND_EXP_GAINED":     1,
		"PROGRESSION_EVENT_KIND_LEVEL_UP":       2,
		"PROGRESSION_EVENT_KIND_SKILL_UNLOCKED": 3,
		"PROGRESSION_EVENT_KIND_POINTS_GRANTED": 4,
		"PROGRESSION_EVENT_KIND_FEAT_COMPLETED": 5,
		"PROGRESSION_EVENT_KIND_ATLAS_TIER":     6,
		"PROGRESSION_EVENT_KIND_STORY_FLAG_SET": 7,
		"PROGRESSION_EVENT_KIND_DISCOVERY":      8,
	}
)

func (x ProgressionEventKind) Enum() *ProgressionEventKind {
	p := new(ProgressionEventKind)
	*p = x
	return p
}

func (x ProgressionEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressionEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_content_proto_enumTypes[1].Descriptor()
}

func (ProgressionEventKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_content_proto_enumTypes[1]
}

func (x ProgressionEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressionEventKind.Descriptor instead.
func (ProgressionEventKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{1}
}

type RespecKind int32

const (
	RespecKind_RESPEC_KIND_UNSPECIFIED RespecKind = 0
	RespecKind_RESPEC_KIND_SKILL       RespecKind = 1
	RespecKind_RESPEC_KIND_POTENTIAL   RespecKind = 2
)

// Enum value maps for RespecKind.
var (
	RespecKind_name = map[int32]string{
		0: "RESPEC_KIND_UNSPECIFIED",
		1: "RESPEC_KIND_SKILL",
		2: "RESPEC_KIND_POTENTIAL",
	}
	RespecKind_value = map[string]int32{
		"RESPEC_KIND_UNSPECIFIED": 0,
		"RESPEC_KIND_SKILL":       1,
		"RESPEC_KIND_POTENTIAL":   2,
	}
)

func (x RespecKind) Enum() *RespecKind {
	p := new(RespecKind)
	*p = x
	return p
}

func (x RespecKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespecKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_content_proto_enumTypes[2].Descriptor()
}

func (RespecKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_content_proto_enumTypes[2]
}

func (x RespecKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespecKind.Descriptor instead.
func (RespecKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{2}
}

type QuestObjectiveView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ObjectiveIndex uint32                 `protobuf:"varint,1,opt,name=objective_index,json=objectiveIndex,proto3" json:"objective_index,omitempty"`
	Current        uint32                 `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Required       uint32                 `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuestObjectiveView) Reset() {
	*x = QuestObjectiveView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestObjectiveView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestObjectiveView) ProtoMessage() {}

func (x *QuestObjectiveView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestObjectiveView.ProtoReflect.Descriptor instead.
func (*QuestObjectiveView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *QuestObjectiveView) GetObjectiveIndex() uint32 {
	if x != nil {
		return x.ObjectiveIndex
	}
	return 0
}

func (x *QuestObjectiveView) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *QuestObjectiveView) GetRequired() uint32 {
	if x != nil {
		return x.Required
	}
	return 0
}

type PotentialDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           uint32                 `protobuf:"varint,1,opt,name=str,proto3" json:"str,omitempty"`
	Vit           uint32                 `protobuf:"varint,2,opt,name=vit,proto3" json:"vit,omitempty"`
	Int           uint32                 `protobuf:"varint,3,opt,name=int,proto3" json:"int,omitempty"`
	Agi           uint32                 `protobuf:"varint,4,opt,name=agi,proto3" json:"agi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PotentialDelta) Reset() {
	*x = PotentialDelta{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PotentialDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PotentialDelta) ProtoMessage() {}

func (x *PotentialDelta) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PotentialDelta.ProtoReflect.Descriptor instead.
func (*PotentialDelta) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *PotentialDelta) GetStr() uint32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *PotentialDelta) GetVit() uint32 {
	if x != nil {
		return x.Vit
	}
	return 0
}

func (x *PotentialDelta) GetInt() uint32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *PotentialDelta) GetAgi() uint32 {
	if x != nil {
		return x.Agi
	}
	return 0
}

type SkillView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillView) Reset() {
	*x = SkillView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillView) ProtoMessage() {}

func (x *SkillView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillView.ProtoReflect.Descriptor instead.
func (*SkillView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *SkillView) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillView) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SkillLoadoutView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicSkillId  string                 `protobuf:"bytes,1,opt,name=basic_skill_id,json=basicSkillId,proto3" json:"basic_skill_id,omitempty"`
	ActiveSlots   []string               `protobuf:"bytes,2,rep,name=active_slots,json=activeSlots,proto3" json:"active_slots,omitempty"` // exactly 5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillLoadoutView) Reset() {
	*x = SkillLoadoutView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillLoadoutView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillLoadoutView) ProtoMessage() {}

func (x *SkillLoadoutView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillLoadoutView.ProtoReflect.Descriptor instead.
func (*SkillLoadoutView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *SkillLoadoutView) GetBasicSkillId() string {
	if x != nil {
		return x.BasicSkillId
	}
	return ""
}

func (x *SkillLoadoutView) GetActiveSlots() []string {
	if x != nil {
		return x.ActiveSlots
	}
	return nil
}

type MysteryBoardPlaceholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SafeAreaId    string                 `protobuf:"bytes,1,opt,name=safe_area_id,json=safeAreaId,proto3" json:"safe_area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysteryBoardPlaceholder) Reset() {
	*x = MysteryBoardPlaceholder{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysteryBoardPlaceholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysteryBoardPlaceholder) ProtoMessage() {}

func (x *MysteryBoardPlaceholder) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysteryBoardPlaceholder.ProtoReflect.Descriptor instead.
func (*MysteryBoardPlaceholder) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *MysteryBoardPlaceholder) GetSafeAreaId() string {
	if x != nil {
		return x.SafeAreaId
	}
	return ""
}

type DailyQuestView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       string                 `protobuf:"bytes,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	TitleKey      string                 `protobuf:"bytes,2,opt,name=title_key,json=titleKey,proto3" json:"title_key,omitempty"`
	Objectives    []*QuestObjectiveView  `protobuf:"bytes,3,rep,name=objectives,proto3" json:"objectives,omitempty"`
	RewardPreview []*ItemQuantity        `protobuf:"bytes,4,rep,name=reward_preview,json=rewardPreview,proto3" json:"reward_preview,omitempty"`
	StarterNpcId  string                 `protobuf:"bytes,5,opt,name=starter_npc_id,json=starterNpcId,proto3" json:"starter_npc_id,omitempty"`
	AreaId        string                 `protobuf:"bytes,6,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyQuestView) Reset() {
	*x = DailyQuestView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyQuestView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyQuestView) ProtoMessage() {}

func (x *DailyQuestView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyQuestView.ProtoReflect.Descriptor instead.
func (*DailyQuestView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *DailyQuestView) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *DailyQuestView) GetTitleKey() string {
	if x != nil {
		return x.TitleKey
	}
	return ""
}

func (x *DailyQuestView) GetObjectives() []*QuestObjectiveView {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *DailyQuestView) GetRewardPreview() []*ItemQuantity {
	if x != nil {
		return x.RewardPreview
	}
	return nil
}

func (x *DailyQuestView) GetStarterNpcId() string {
	if x != nil {
		return x.StarterNpcId
	}
	return ""
}

func (x *DailyQuestView) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type DailyBoardEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	BoardSlot uint32                 `protobuf:"varint,1,opt,name=board_slot,json=boardSlot,proto3" json:"board_slot,omitempty"` // 1..6
	State     QuestState             `protobuf:"varint,2,opt,name=state,proto3,enum=thinhthan.v1.QuestState" json:"state,omitempty"`
	IsMystery bool                   `protobuf:"varint,3,opt,name=is_mystery,json=isMystery,proto3" json:"is_mystery,omitempty"`
	// Types that are valid to be assigned to View:
	//
	//	*DailyBoardEntry_Hidden
	//	*DailyBoardEntry_Revealed
	View          isDailyBoardEntry_View `protobuf_oneof:"view"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyBoardEntry) Reset() {
	*x = DailyBoardEntry{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyBoardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyBoardEntry) ProtoMessage() {}

func (x *DailyBoardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyBoardEntry.ProtoReflect.Descriptor instead.
func (*DailyBoardEntry) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *DailyBoardEntry) GetBoardSlot() uint32 {
	if x != nil {
		return x.BoardSlot
	}
	return 0
}

func (x *DailyBoardEntry) GetState() QuestState {
	if x != nil {
		return x.State
	}
	return QuestState_QUEST_STATE_UNSPECIFIED
}

func (x *DailyBoardEntry) GetIsMystery() bool {
	if x != nil {
		return x.IsMystery
	}
	return false
}

func (x *DailyBoardEntry) GetView() isDailyBoardEntry_View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *DailyBoardEntry) GetHidden() *MysteryBoardPlaceholder {
	if x != nil {
		if x, ok := x.View.(*DailyBoardEntry_Hidden); ok {
			return x.Hidden
		}
	}
	return nil
}

func (x *DailyBoardEntry) GetRevealed() *DailyQuestView {
	if x != nil {
		if x, ok := x.View.(*DailyBoardEntry_Revealed); ok {
			return x.Revealed
		}
	}
	return nil
}

type isDailyBoardEntry_View interface {
	isDailyBoardEntry_View()
}

type DailyBoardEntry_Hidden struct {
	Hidden *MysteryBoardPlaceholder `protobuf:"bytes,4,opt,name=hidden,proto3,oneof"`
}

type DailyBoardEntry_Revealed struct {
	Revealed *DailyQuestView `protobuf:"bytes,5,opt,name=revealed,proto3,oneof"`
}

func (*DailyBoardEntry_Hidden) isDailyBoardEntry_View() {}

func (*DailyBoardEntry_Revealed) isDailyBoardEntry_View() {}

type AtlasGrantView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Exp            int64                  `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	CurrencyDelta  []*CurrencyDelta       `protobuf:"bytes,2,rep,name=currency_delta,json=currencyDelta,proto3" json:"currency_delta,omitempty"`
	RewardClaimIds [][]byte               `protobuf:"bytes,3,rep,name=reward_claim_ids,json=rewardClaimIds,proto3" json:"reward_claim_ids,omitempty"` // UUID, 16 bytes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AtlasGrantView) Reset() {
	*x = AtlasGrantView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtlasGrantView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasGrantView) ProtoMessage() {}

func (x *AtlasGrantView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasGrantView.ProtoReflect.Descriptor instead.
func (*AtlasGrantView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *AtlasGrantView) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *AtlasGrantView) GetCurrencyDelta() []*CurrencyDelta {
	if x != nil {
		return x.CurrencyDelta
	}
	return nil
}

func (x *AtlasGrantView) GetRewardClaimIds() [][]byte {
	if x != nil {
		return x.RewardClaimIds
	}
	return nil
}

type AtlasTierView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tier              uint32                 `protobuf:"varint,1,opt,name=tier,proto3" json:"tier,omitempty"`
	RewardOperationId []byte                 `protobuf:"bytes,2,opt,name=reward_operation_id,json=rewardOperationId,proto3" json:"reward_operation_id,omitempty"` // UUID, 16 bytes
	AcknowledgedAtMs  int64                  `protobuf:"varint,3,opt,name=acknowledged_at_ms,json=acknowledgedAtMs,proto3" json:"acknowledged_at_ms,omitempty"`
	SettledGrant      *AtlasGrantView        `protobuf:"bytes,4,opt,name=settled_grant,json=settledGrant,proto3" json:"settled_grant,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AtlasTierView) Reset() {
	*x = AtlasTierView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtlasTierView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasTierView) ProtoMessage() {}

func (x *AtlasTierView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasTierView.ProtoReflect.Descriptor instead.
func (*AtlasTierView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{8}
}

func (x *AtlasTierView) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *AtlasTierView) GetRewardOperationId() []byte {
	if x != nil {
		return x.RewardOperationId
	}
	return nil
}

func (x *AtlasTierView) GetAcknowledgedAtMs() int64 {
	if x != nil {
		return x.AcknowledgedAtMs
	}
	return 0
}

func (x *AtlasTierView) GetSettledGrant() *AtlasGrantView {
	if x != nil {
		return x.SettledGrant
	}
	return nil
}

type AtlasPageView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtlasPageId   string                 `protobuf:"bytes,1,opt,name=atlas_page_id,json=atlasPageId,proto3" json:"atlas_page_id,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	ReachedTier   uint32                 `protobuf:"varint,3,opt,name=reached_tier,json=reachedTier,proto3" json:"reached_tier,omitempty"`
	Tiers         []*AtlasTierView       `protobuf:"bytes,4,rep,name=tiers,proto3" json:"tiers,omitempty"` // settled tiers only, sorted by tier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtlasPageView) Reset() {
	*x = AtlasPageView{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtlasPageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasPageView) ProtoMessage() {}

func (x *AtlasPageView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasPageView.ProtoReflect.Descriptor instead.
func (*AtlasPageView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{9}
}

func (x *AtlasPageView) GetAtlasPageId() string {
	if x != nil {
		return x.AtlasPageId
	}
	return ""
}

func (x *AtlasPageView) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *AtlasPageView) GetReachedTier() uint32 {
	if x != nil {
		return x.ReachedTier
	}
	return 0
}

func (x *AtlasPageView) GetTiers() []*AtlasTierView {
	if x != nil {
		return x.Tiers
	}
	return nil
}

// ID 500
type C2SQuestAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`      // UUID, 16 bytes
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`                  // empty only for unrevealed DAILY choice
	NpcId         string                 `protobuf:"bytes,3,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`                        // empty for DAILY board / auto-offered
	BoardSlot     uint32                 `protobuf:"varint,4,opt,name=board_slot,json=boardSlot,proto3" json:"board_slot,omitempty"`           // 1..6 for DAILY
	BoardCycleId  string                 `protobuf:"bytes,5,opt,name=board_cycle_id,json=boardCycleId,proto3" json:"board_cycle_id,omitempty"` // DAILY only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SQuestAccept) Reset() {
	*x = C2SQuestAccept{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SQuestAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQuestAccept) ProtoMessage() {}

func (x *C2SQuestAccept) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQuestAccept.ProtoReflect.Descriptor instead.
func (*C2SQuestAccept) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{10}
}

func (x *C2SQuestAccept) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SQuestAccept) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *C2SQuestAccept) GetNpcId() string {
	if x != nil {
		return x.NpcId
	}
	return ""
}

func (x *C2SQuestAccept) GetBoardSlot() uint32 {
	if x != nil {
		return x.BoardSlot
	}
	return 0
}

func (x *C2SQuestAccept) GetBoardCycleId() string {
	if x != nil {
		return x.BoardCycleId
	}
	return ""
}

// ID 501
type S2CQuestAcceptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CQuestAcceptResult) Reset() {
	*x = S2CQuestAcceptResult{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CQuestAcceptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CQuestAcceptResult) ProtoMessage() {}

func (x *S2CQuestAcceptResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CQuestAcceptResult.ProtoReflect.Descriptor instead.
func (*S2CQuestAcceptResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{11}
}

func (x *S2CQuestAcceptResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CQuestAcceptResult) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

// ID 502
type C2SQuestTurnIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	NpcId         string                 `protobuf:"bytes,3,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"` // empty for AUTO completion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SQuestTurnIn) Reset() {
	*x = C2SQuestTurnIn{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SQuestTurnIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQuestTurnIn) ProtoMessage() {}

func (x *C2SQuestTurnIn) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQuestTurnIn.ProtoReflect.Descriptor instead.
func (*C2SQuestTurnIn) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{12}
}

func (x *C2SQuestTurnIn) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SQuestTurnIn) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *C2SQuestTurnIn) GetNpcId() string {
	if x != nil {
		return x.NpcId
	}
	return ""
}

// ID 503
type S2CQuestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3,oneof" json:"result,omitempty"` // present only when answering 502
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	State         QuestState             `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.QuestState" json:"state,omitempty"`
	Objectives    []*QuestObjectiveView  `protobuf:"bytes,4,rep,name=objectives,proto3" json:"objectives,omitempty"`
	ExpiresAtMs   int64                  `protobuf:"varint,5,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`    // DAILY/EVENT; 0 = none
	ExpGained     int64                  `protobuf:"varint,6,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`            // turn-in only
	Granted       []*ItemGrant           `protobuf:"bytes,7,rep,name=granted,proto3" json:"granted,omitempty"`                                  // turn-in only
	CurrencyDelta []*CurrencyDelta       `protobuf:"bytes,8,rep,name=currency_delta,json=currencyDelta,proto3" json:"currency_delta,omitempty"` // turn-in only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CQuestUpdate) Reset() {
	*x = S2CQuestUpdate{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CQuestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CQuestUpdate) ProtoMessage() {}

func (x *S2CQuestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CQuestUpdate.ProtoReflect.Descriptor instead.
func (*S2CQuestUpdate) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{13}
}

func (x *S2CQuestUpdate) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CQuestUpdate) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *S2CQuestUpdate) GetState() QuestState {
	if x != nil {
		return x.State
	}
	return QuestState_QUEST_STATE_UNSPECIFIED
}

func (x *S2CQuestUpdate) GetObjectives() []*QuestObjectiveView {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *S2CQuestUpdate) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *S2CQuestUpdate) GetExpGained() int64 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

func (x *S2CQuestUpdate) GetGranted() []*ItemGrant {
	if x != nil {
		return x.Granted
	}
	return nil
}

func (x *S2CQuestUpdate) GetCurrencyDelta() []*CurrencyDelta {
	if x != nil {
		return x.CurrencyDelta
	}
	return nil
}

// ID 504
type C2SAtlasClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	AtlasPageId   string                 `protobuf:"bytes,2,opt,name=atlas_page_id,json=atlasPageId,proto3" json:"atlas_page_id,omitempty"`
	Tier          uint32                 `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAtlasClaim) Reset() {
	*x = C2SAtlasClaim{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAtlasClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAtlasClaim) ProtoMessage() {}

func (x *C2SAtlasClaim) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAtlasClaim.ProtoReflect.Descriptor instead.
func (*C2SAtlasClaim) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{14}
}

func (x *C2SAtlasClaim) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAtlasClaim) GetAtlasPageId() string {
	if x != nil {
		return x.AtlasPageId
	}
	return ""
}

func (x *C2SAtlasClaim) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

// ID 505
type S2CAtlasClaimResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	AtlasPageId   string                 `protobuf:"bytes,2,opt,name=atlas_page_id,json=atlasPageId,proto3" json:"atlas_page_id,omitempty"`
	Tier          uint32                 `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
	Granted       *AtlasGrantView        `protobuf:"bytes,4,opt,name=granted,proto3" json:"granted,omitempty"` // the settled grant
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAtlasClaimResult) Reset() {
	*x = S2CAtlasClaimResult{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAtlasClaimResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAtlasClaimResult) ProtoMessage() {}

func (x *S2CAtlasClaimResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAtlasClaimResult.ProtoReflect.Descriptor instead.
func (*S2CAtlasClaimResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{15}
}

func (x *S2CAtlasClaimResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAtlasClaimResult) GetAtlasPageId() string {
	if x != nil {
		return x.AtlasPageId
	}
	return ""
}

func (x *S2CAtlasClaimResult) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *S2CAtlasClaimResult) GetGranted() *AtlasGrantView {
	if x != nil {
		return x.Granted
	}
	return nil
}

// ID 506
type S2CProgressionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventKind     ProgressionEventKind   `protobuf:"varint,1,opt,name=event_kind,json=eventKind,proto3,enum=thinhthan.v1.ProgressionEventKind" json:"event_kind,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	LevelAfter    uint32                 `protobuf:"varint,3,opt,name=level_after,json=levelAfter,proto3" json:"level_after,omitempty"`
	SourceKind    string                 `protobuf:"bytes,4,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,6,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CProgressionEvent) Reset() {
	*x = S2CProgressionEvent{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CProgressionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CProgressionEvent) ProtoMessage() {}

func (x *S2CProgressionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CProgressionEvent.ProtoReflect.Descriptor instead.
func (*S2CProgressionEvent) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{16}
}

func (x *S2CProgressionEvent) GetEventKind() ProgressionEventKind {
	if x != nil {
		return x.EventKind
	}
	return ProgressionEventKind_PROGRESSION_EVENT_KIND_UNSPECIFIED
}

func (x *S2CProgressionEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *S2CProgressionEvent) GetLevelAfter() uint32 {
	if x != nil {
		return x.LevelAfter
	}
	return 0
}

func (x *S2CProgressionEvent) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *S2CProgressionEvent) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *S2CProgressionEvent) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

// ID 507
type C2SQuestAbandon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SQuestAbandon) Reset() {
	*x = C2SQuestAbandon{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SQuestAbandon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQuestAbandon) ProtoMessage() {}

func (x *C2SQuestAbandon) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQuestAbandon.ProtoReflect.Descriptor instead.
func (*C2SQuestAbandon) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{17}
}

func (x *C2SQuestAbandon) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SQuestAbandon) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

// ID 508
type S2CQuestAbandonResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	QuestId       string                 `protobuf:"bytes,2,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	RemovedItems  []*ItemQuantity        `protobuf:"bytes,3,rep,name=removed_items,json=removedItems,proto3" json:"removed_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CQuestAbandonResult) Reset() {
	*x = S2CQuestAbandonResult{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CQuestAbandonResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CQuestAbandonResult) ProtoMessage() {}

func (x *S2CQuestAbandonResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CQuestAbandonResult.ProtoReflect.Descriptor instead.
func (*S2CQuestAbandonResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{18}
}

func (x *S2CQuestAbandonResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CQuestAbandonResult) GetQuestId() string {
	if x != nil {
		return x.QuestId
	}
	return ""
}

func (x *S2CQuestAbandonResult) GetRemovedItems() []*ItemQuantity {
	if x != nil {
		return x.RemovedItems
	}
	return nil
}

// ID 509
type C2SStoryBranchChoose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	BranchFlag    string                 `protobuf:"bytes,2,opt,name=branch_flag,json=branchFlag,proto3" json:"branch_flag,omitempty"`
	Option        string                 `protobuf:"bytes,3,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SStoryBranchChoose) Reset() {
	*x = C2SStoryBranchChoose{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SStoryBranchChoose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SStoryBranchChoose) ProtoMessage() {}

func (x *C2SStoryBranchChoose) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SStoryBranchChoose.ProtoReflect.Descriptor instead.
func (*C2SStoryBranchChoose) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{19}
}

func (x *C2SStoryBranchChoose) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SStoryBranchChoose) GetBranchFlag() string {
	if x != nil {
		return x.BranchFlag
	}
	return ""
}

func (x *C2SStoryBranchChoose) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

// ID 510
type S2CStoryBranchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	BranchFlag    string                 `protobuf:"bytes,2,opt,name=branch_flag,json=branchFlag,proto3" json:"branch_flag,omitempty"`
	Option        string                 `protobuf:"bytes,3,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CStoryBranchResult) Reset() {
	*x = S2CStoryBranchResult{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CStoryBranchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CStoryBranchResult) ProtoMessage() {}

func (x *S2CStoryBranchResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CStoryBranchResult.ProtoReflect.Descriptor instead.
func (*S2CStoryBranchResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{20}
}

func (x *S2CStoryBranchResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CStoryBranchResult) GetBranchFlag() string {
	if x != nil {
		return x.BranchFlag
	}
	return ""
}

func (x *S2CStoryBranchResult) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

// ID 511
type C2SSkillUpgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	ExpectedLevel uint32                 `protobuf:"varint,3,opt,name=expected_level,json=expectedLevel,proto3" json:"expected_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SSkillUpgrade) Reset() {
	*x = C2SSkillUpgrade{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SSkillUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSkillUpgrade) ProtoMessage() {}

func (x *C2SSkillUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSkillUpgrade.ProtoReflect.Descriptor instead.
func (*C2SSkillUpgrade) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{21}
}

func (x *C2SSkillUpgrade) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SSkillUpgrade) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *C2SSkillUpgrade) GetExpectedLevel() uint32 {
	if x != nil {
		return x.ExpectedLevel
	}
	return 0
}

// ID 512
type C2SPotentialAllocate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	Deltas        *PotentialDelta        `protobuf:"bytes,2,opt,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPotentialAllocate) Reset() {
	*x = C2SPotentialAllocate{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPotentialAllocate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPotentialAllocate) ProtoMessage() {}

func (x *C2SPotentialAllocate) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPotentialAllocate.ProtoReflect.Descriptor instead.
func (*C2SPotentialAllocate) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{22}
}

func (x *C2SPotentialAllocate) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SPotentialAllocate) GetDeltas() *PotentialDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

// ID 513
type C2SRespec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	NpcId         string                 `protobuf:"bytes,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Kind          RespecKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=thinhthan.v1.RespecKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SRespec) Reset() {
	*x = C2SRespec{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SRespec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRespec) ProtoMessage() {}

func (x *C2SRespec) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRespec.ProtoReflect.Descriptor instead.
func (*C2SRespec) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{23}
}

func (x *C2SRespec) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SRespec) GetNpcId() string {
	if x != nil {
		return x.NpcId
	}
	return ""
}

func (x *C2SRespec) GetKind() RespecKind {
	if x != nil {
		return x.Kind
	}
	return RespecKind_RESPEC_KIND_UNSPECIFIED
}

// ID 514
type S2CProgressionMutateResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	RequestMessageId uint32                 `protobuf:"varint,2,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"` // 511 | 512 | 513
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2CProgressionMutateResult) Reset() {
	*x = S2CProgressionMutateResult{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CProgressionMutateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CProgressionMutateResult) ProtoMessage() {}

func (x *S2CProgressionMutateResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CProgressionMutateResult.ProtoReflect.Descriptor instead.
func (*S2CProgressionMutateResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{24}
}

func (x *S2CProgressionMutateResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CProgressionMutateResult) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

// ID 515
type S2CProgressionState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Level                  uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	CurrentExp             int64                  `protobuf:"varint,2,opt,name=current_exp,json=currentExp,proto3" json:"current_exp,omitempty"`
	UnspentSkillPoints     uint32                 `protobuf:"varint,3,opt,name=unspent_skill_points,json=unspentSkillPoints,proto3" json:"unspent_skill_points,omitempty"`
	UnspentPotentialPoints uint32                 `protobuf:"varint,4,opt,name=unspent_potential_points,json=unspentPotentialPoints,proto3" json:"unspent_potential_points,omitempty"`
	PotentialAllocated     *PotentialDelta        `protobuf:"bytes,5,opt,name=potential_allocated,json=potentialAllocated,proto3" json:"potential_allocated,omitempty"`
	PotentialEarnedTotal   uint32                 `protobuf:"varint,6,opt,name=potential_earned_total,json=potentialEarnedTotal,proto3" json:"potential_earned_total,omitempty"`
	Skills                 []*SkillView           `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	SkillLoadout           *SkillLoadoutView      `protobuf:"bytes,8,opt,name=skill_loadout,json=skillLoadout,proto3" json:"skill_loadout,omitempty"`
	ProgressionRevision    uint64                 `protobuf:"varint,9,opt,name=progression_revision,json=progressionRevision,proto3" json:"progression_revision,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *S2CProgressionState) Reset() {
	*x = S2CProgressionState{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CProgressionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CProgressionState) ProtoMessage() {}

func (x *S2CProgressionState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CProgressionState.ProtoReflect.Descriptor instead.
func (*S2CProgressionState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{25}
}

func (x *S2CProgressionState) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *S2CProgressionState) GetCurrentExp() int64 {
	if x != nil {
		return x.CurrentExp
	}
	return 0
}

func (x *S2CProgressionState) GetUnspentSkillPoints() uint32 {
	if x != nil {
		return x.UnspentSkillPoints
	}
	return 0
}

func (x *S2CProgressionState) GetUnspentPotentialPoints() uint32 {
	if x != nil {
		return x.UnspentPotentialPoints
	}
	return 0
}

func (x *S2CProgressionState) GetPotentialAllocated() *PotentialDelta {
	if x != nil {
		return x.PotentialAllocated
	}
	return nil
}

func (x *S2CProgressionState) GetPotentialEarnedTotal() uint32 {
	if x != nil {
		return x.PotentialEarnedTotal
	}
	return 0
}

func (x *S2CProgressionState) GetSkills() []*SkillView {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *S2CProgressionState) GetSkillLoadout() *SkillLoadoutView {
	if x != nil {
		return x.SkillLoadout
	}
	return nil
}

func (x *S2CProgressionState) GetProgressionRevision() uint64 {
	if x != nil {
		return x.ProgressionRevision
	}
	return 0
}

// ID 516
type C2SDailyBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // echo only
	BoardAnchorId string                 `protobuf:"bytes,2,opt,name=board_anchor_id,json=boardAnchorId,proto3" json:"board_anchor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDailyBoardRequest) Reset() {
	*x = C2SDailyBoardRequest{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDailyBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDailyBoardRequest) ProtoMessage() {}

func (x *C2SDailyBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDailyBoardRequest.ProtoReflect.Descriptor instead.
func (*C2SDailyBoardRequest) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{26}
}

func (x *C2SDailyBoardRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *C2SDailyBoardRequest) GetBoardAnchorId() string {
	if x != nil {
		return x.BoardAnchorId
	}
	return ""
}

// ID 517 (read-only request_id response)
type S2CDailyBoardState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status         ResultStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=thinhthan.v1.ResultStatus" json:"status,omitempty"`
	ErrorCode      ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	CycleId        string                 `protobuf:"bytes,4,opt,name=cycle_id,json=cycleId,proto3" json:"cycle_id,omitempty"` // UTC date
	BoardRevision  uint64                 `protobuf:"varint,5,opt,name=board_revision,json=boardRevision,proto3" json:"board_revision,omitempty"`
	CompletedCount uint32                 `protobuf:"varint,6,opt,name=completed_count,json=completedCount,proto3" json:"completed_count,omitempty"` // 0..3
	ResetAtMs      int64                  `protobuf:"varint,7,opt,name=reset_at_ms,json=resetAtMs,proto3" json:"reset_at_ms,omitempty"`
	Entries        []*DailyBoardEntry     `protobuf:"bytes,8,rep,name=entries,proto3" json:"entries,omitempty"` // exactly 6 on success
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CDailyBoardState) Reset() {
	*x = S2CDailyBoardState{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CDailyBoardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDailyBoardState) ProtoMessage() {}

func (x *S2CDailyBoardState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDailyBoardState.ProtoReflect.Descriptor instead.
func (*S2CDailyBoardState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{27}
}

func (x *S2CDailyBoardState) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *S2CDailyBoardState) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_RESULT_STATUS_UNSPECIFIED
}

func (x *S2CDailyBoardState) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *S2CDailyBoardState) GetCycleId() string {
	if x != nil {
		return x.CycleId
	}
	return ""
}

func (x *S2CDailyBoardState) GetBoardRevision() uint64 {
	if x != nil {
		return x.BoardRevision
	}
	return 0
}

func (x *S2CDailyBoardState) GetCompletedCount() uint32 {
	if x != nil {
		return x.CompletedCount
	}
	return 0
}

func (x *S2CDailyBoardState) GetResetAtMs() int64 {
	if x != nil {
		return x.ResetAtMs
	}
	return 0
}

func (x *S2CDailyBoardState) GetEntries() []*DailyBoardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ID 518
type S2CAtlasState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtlasRevision uint64                 `protobuf:"varint,1,opt,name=atlas_revision,json=atlasRevision,proto3" json:"atlas_revision,omitempty"`
	Pages         []*AtlasPageView       `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAtlasState) Reset() {
	*x = S2CAtlasState{}
	mi := &file_thinhthan_v1_content_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAtlasState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAtlasState) ProtoMessage() {}

func (x *S2CAtlasState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_content_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAtlasState.ProtoReflect.Descriptor instead.
func (*S2CAtlasState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_content_proto_rawDescGZIP(), []int{28}
}

func (x *S2CAtlasState) GetAtlasRevision() uint64 {
	if x != nil {
		return x.AtlasRevision
	}
	return 0
}

func (x *S2CAtlasState) GetPages() []*AtlasPageView {
	if x != nil {
		return x.Pages
	}
	return nil
}

var File_thinhthan_v1_content_proto protoreflect.FileDescriptor

const file_thinhthan_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1athinhthan/v1/content.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"s\n" +
	"\x12QuestObjectiveView\x12'\n" +
	"\x0fobjective_index\x18\x01 \x01(\rR\x0eobjectiveIndex\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\rR\acurrent\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\rR\brequired\"X\n" +
	"\x0ePotentialDelta\x12\x10\n" +
	"\x03str\x18\x01 \x01(\rR\x03str\x12\x10\n" +
	"\x03vit\x18\x02 \x01(\rR\x03vit\x12\x10\n" +
	"\x03int\x18\x03 \x01(\rR\x03int\x12\x10\n" +
	"\x03agi\x18\x04 \x01(\rR\x03agi\"<\n" +
	"\tSkillView\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\"[\n" +
	"\x10SkillLoadoutView\x12$\n" +
	"\x0ebasic_skill_id\x18\x01 \x01(\tR\fbasicSkillId\x12!\n" +
	"\factive_slots\x18\x02 \x03(\tR\vactiveSlots\";\n" +
	"\x17MysteryBoardPlaceholder\x12 \n" +
	"\fsafe_area_id\x18\x01 \x01(\tR\n" +
	"safeAreaId\"\x8c\x02\n" +
	"\x0eDailyQuestView\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\tR\aquestId\x12\x1b\n" +
	"\ttitle_key\x18\x02 \x01(\tR\btitleKey\x12@\n" +
	"\n" +
	"objectives\x18\x03 \x03(\v2 .thinhthan.v1.QuestObjectiveViewR\n" +
	"objectives\x12A\n" +
	"\x0ereward_preview\x18\x04 \x03(\v2\x1a.thinhthan.v1.ItemQuantityR\rrewardPreview\x12$\n" +
	"\x0estarter_npc_id\x18\x05 \x01(\tR\fstarterNpcId\x12\x17\n" +
	"\aarea_id\x18\x06 \x01(\tR\x06areaId\"\x84\x02\n" +
	"\x0fDailyBoardEntry\x12\x1d\n" +
	"\n" +
	"board_slot\x18\x01 \x01(\rR\tboardSlot\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.thinhthan.v1.QuestStateR\x05state\x12\x1d\n" +
	"\n" +
	"is_mystery\x18\x03 \x01(\bR\tisMystery\x12?\n" +
	"\x06hidden\x18\x04 \x01(\v2%.thinhthan.v1.MysteryBoardPlaceholderH\x00R\x06hidden\x12:\n" +
	"\brevealed\x18\x05 \x01(\v2\x1c.thinhthan.v1.DailyQuestViewH\x00R\brevealedB\x06\n" +
	"\x04view\"\x90\x01\n" +
	"\x0eAtlasGrantView\x12\x10\n" +
	"\x03exp\x18\x01 \x01(\x03R\x03exp\x12B\n" +
	"\x0ecurrency_delta\x18\x02 \x03(\v2\x1b.thinhthan.v1.CurrencyDeltaR\rcurrencyDelta\x12(\n" +
	"\x10reward_claim_ids\x18\x03 \x03(\fR\x0erewardClaimIds\"\xc4\x01\n" +
	"\rAtlasTierView\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\rR\x04tier\x12.\n" +
	"\x13reward_operation_id\x18\x02 \x01(\fR\x11rewardOperationId\x12,\n" +
	"\x12acknowledged_at_ms\x18\x03 \x01(\x03R\x10acknowledgedAtMs\x12A\n" +
	"\rsettled_grant\x18\x04 \x01(\v2\x1c.thinhthan.v1.AtlasGrantViewR\fsettledGrant\"\xa3\x01\n" +
	"\rAtlasPageView\x12\"\n" +
	"\ratlas_page_id\x18\x01 \x01(\tR\vatlasPageId\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\x12!\n" +
	"\freached_tier\x18\x03 \x01(\rR\vreachedTier\x121\n" +
	"\x05tiers\x18\x04 \x03(\v2\x1b.thinhthan.v1.AtlasTierViewR\x05tiers\"\xaa\x01\n" +
	"\x0eC2SQuestAccept\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\x12\x15\n" +
	"\x06npc_id\x18\x03 \x01(\tR\x05npcId\x12\x1d\n" +
	"\n" +
	"board_slot\x18\x04 \x01(\rR\tboardSlot\x12$\n" +
	"\x0eboard_cycle_id\x18\x05 \x01(\tR\fboardCycleId\"h\n" +
	"\x14S2CQuestAcceptResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\"e\n" +
	"\x0eC2SQuestTurnIn\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\x12\x15\n" +
	"\x06npc_id\x18\x03 \x01(\tR\x05npcId\"\x9e\x03\n" +
	"\x0eS2CQuestUpdate\x12:\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultH\x00R\x06result\x88\x01\x01\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.thinhthan.v1.QuestStateR\x05state\x12@\n" +
	"\n" +
	"objectives\x18\x04 \x03(\v2 .thinhthan.v1.QuestObjectiveViewR\n" +
	"objectives\x12\"\n" +
	"\rexpires_at_ms\x18\x05 \x01(\x03R\vexpiresAtMs\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x06 \x01(\x03R\texpGained\x121\n" +
	"\agranted\x18\a \x03(\v2\x17.thinhthan.v1.ItemGrantR\agranted\x12B\n" +
	"\x0ecurrency_delta\x18\b \x03(\v2\x1b.thinhthan.v1.CurrencyDeltaR\rcurrencyDeltaB\t\n" +
	"\a_result\"j\n" +
	"\rC2SAtlasClaim\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\"\n" +
	"\ratlas_page_id\x18\x02 \x01(\tR\vatlasPageId\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\rR\x04tier\"\xbc\x01\n" +
	"\x13S2CAtlasClaimResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\"\n" +
	"\ratlas_page_id\x18\x02 \x01(\tR\vatlasPageId\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\rR\x04tier\x126\n" +
	"\agranted\x18\x04 \x01(\v2\x1c.thinhthan.v1.AtlasGrantViewR\agranted\"\xfb\x01\n" +
	"\x13S2CProgressionEvent\x12A\n" +
	"\n" +
	"event_kind\x18\x01 \x01(\x0e2\".thinhthan.v1.ProgressionEventKindR\teventKind\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vlevel_after\x18\x03 \x01(\rR\n" +
	"levelAfter\x12\x1f\n" +
	"\vsource_kind\x18\x04 \x01(\tR\n" +
	"sourceKind\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\x12$\n" +
	"\x0eserver_time_ms\x18\x06 \x01(\x03R\fserverTimeMs\"O\n" +
	"\x0fC2SQuestAbandon\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\"\xaa\x01\n" +
	"\x15S2CQuestAbandonResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x19\n" +
	"\bquest_id\x18\x02 \x01(\tR\aquestId\x12?\n" +
	"\rremoved_items\x18\x03 \x03(\v2\x1a.thinhthan.v1.ItemQuantityR\fremovedItems\"r\n" +
	"\x14C2SStoryBranchChoose\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1f\n" +
	"\vbranch_flag\x18\x02 \x01(\tR\n" +
	"branchFlag\x12\x16\n" +
	"\x06option\x18\x03 \x01(\tR\x06option\"\x86\x01\n" +
	"\x14S2CStoryBranchResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1f\n" +
	"\vbranch_flag\x18\x02 \x01(\tR\n" +
	"branchFlag\x12\x16\n" +
	"\x06option\x18\x03 \x01(\tR\x06option\"v\n" +
	"\x0fC2SSkillUpgrade\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12%\n" +
	"\x0eexpected_level\x18\x03 \x01(\rR\rexpectedLevel\"o\n" +
	"\x14C2SPotentialAllocate\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x124\n" +
	"\x06deltas\x18\x02 \x01(\v2\x1c.thinhthan.v1.PotentialDeltaR\x06deltas\"s\n" +
	"\tC2SRespec\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\tR\x05npcId\x12,\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x18.thinhthan.v1.RespecKindR\x04kind\"\x81\x01\n" +
	"\x1aS2CProgressionMutateResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12,\n" +
	"\x12request_message_id\x18\x02 \x01(\rR\x10requestMessageId\"\xe6\x03\n" +
	"\x13S2CProgressionState\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x1f\n" +
	"\vcurrent_exp\x18\x02 \x01(\x03R\n" +
	"currentExp\x120\n" +
	"\x14unspent_skill_points\x18\x03 \x01(\rR\x12unspentSkillPoints\x128\n" +
	"\x18unspent_potential_points\x18\x04 \x01(\rR\x16unspentPotentialPoints\x12M\n" +
	"\x13potential_allocated\x18\x05 \x01(\v2\x1c.thinhthan.v1.PotentialDeltaR\x12potentialAllocated\x124\n" +
	"\x16potential_earned_total\x18\x06 \x01(\rR\x14potentialEarnedTotal\x12/\n" +
	"\x06skills\x18\a \x03(\v2\x17.thinhthan.v1.SkillViewR\x06skills\x12C\n" +
	"\rskill_loadout\x18\b \x01(\v2\x1e.thinhthan.v1.SkillLoadoutViewR\fskillLoadout\x121\n" +
	"\x14progression_revision\x18\t \x01(\x04R\x13progressionRevision\"]\n" +
	"\x14C2SDailyBoardRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12&\n" +
	"\x0fboard_anchor_id\x18\x02 \x01(\tR\rboardAnchorId\"\xe3\x02\n" +
	"\x12S2CDailyBoardState\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.thinhthan.v1.ResultStatusR\x06status\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\x12\x19\n" +
	"\bcycle_id\x18\x04 \x01(\tR\acycleId\x12%\n" +
	"\x0eboard_revision\x18\x05 \x01(\x04R\rboardRevision\x12'\n" +
	"\x0fcompleted_count\x18\x06 \x01(\rR\x0ecompletedCount\x12\x1e\n" +
	"\vreset_at_ms\x18\a \x01(\x03R\tresetAtMs\x127\n" +
	"\aentries\x18\b \x03(\v2\x1d.thinhthan.v1.DailyBoardEntryR\aentries\"i\n" +
	"\rS2CAtlasState\x12%\n" +
	"\x0eatlas_revision\x18\x01 \x01(\x04R\ratlasRevision\x121\n" +
	"\x05pages\x18\x02 \x03(\v2\x1b.thinhthan.v1.AtlasPageViewR\x05pages*\xe3\x01\n" +
	"\n" +
	"QuestState\x12\x1b\n" +
	"\x17QUEST_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12QUEST_STATE_LOCKED\x10\x01\x12\x19\n" +
	"\x15QUEST_STATE_AVAILABLE\x10\x02\x12\x16\n" +
	"\x12QUEST_STATE_ACTIVE\x10\x03\x12!\n" +
	"\x1dQUEST_STATE_READY_TO_COMPLETE\x10\x04\x12\x19\n" +
	"\x15QUEST_STATE_COMPLETED\x10\x05\x12\x16\n" +
	"\x12QUEST_STATE_FAILED\x10\x06\x12\x17\n" +
	"\x13QUEST_STATE_EXPIRED\x10\a*\x83\x03\n" +
	"\x14ProgressionEventKind\x12&\n" +
	"\"PROGRESSION_EVENT_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!PROGRESSION_EVENT_KIND_EXP_GAINED\x10\x01\x12#\n" +
	"\x1fPROGRESSION_EVENT_KIND_LEVEL_UP\x10\x02\x12)\n" +
	"%PROGRESSION_EVENT_KIND_SKILL_UNLOCKED\x10\x03\x12)\n" +
	"%PROGRESSION_EVENT_KIND_POINTS_GRANTED\x10\x04\x12)\n" +
	"%PROGRESSION_EVENT_KIND_FEAT_COMPLETED\x10\x05\x12%\n" +
	"!PROGRESSION_EVENT_KIND_ATLAS_TIER\x10\x06\x12)\n" +
	"%PROGRESSION_EVENT_KIND_STORY_FLAG_SET\x10\a\x12$\n" +
	" PROGRESSION_EVENT_KIND_DISCOVERY\x10\b*[\n" +
	"\n" +
	"RespecKind\x12\x1b\n" +
	"\x17RESPEC_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RESPEC_KIND_SKILL\x10\x01\x12\x19\n" +
	"\x15RESPEC_KIND_POTENTIAL\x10\x02BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_content_proto_rawDescOnce sync.Once
	file_thinhthan_v1_content_proto_rawDescData []byte
)

func file_thinhthan_v1_content_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_content_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_content_proto_rawDesc), len(file_thinhthan_v1_content_proto_rawDesc)))
	})
	return file_thinhthan_v1_content_proto_rawDescData
}

var file_thinhthan_v1_content_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_thinhthan_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_thinhthan_v1_content_proto_goTypes = []any{
	(QuestState)(0),                    // 0: thinhthan.v1.QuestState
	(ProgressionEventKind)(0),          // 1: thinhthan.v1.ProgressionEventKind
	(RespecKind)(0),                    // 2: thinhthan.v1.RespecKind
	(*QuestObjectiveView)(nil),         // 3: thinhthan.v1.QuestObjectiveView
	(*PotentialDelta)(nil),             // 4: thinhthan.v1.PotentialDelta
	(*SkillView)(nil),                  // 5: thinhthan.v1.SkillView
	(*SkillLoadoutView)(nil),           // 6: thinhthan.v1.SkillLoadoutView
	(*MysteryBoardPlaceholder)(nil),    // 7: thinhthan.v1.MysteryBoardPlaceholder
	(*DailyQuestView)(nil),             // 8: thinhthan.v1.DailyQuestView
	(*DailyBoardEntry)(nil),            // 9: thinhthan.v1.DailyBoardEntry
	(*AtlasGrantView)(nil),             // 10: thinhthan.v1.AtlasGrantView
	(*AtlasTierView)(nil),              // 11: thinhthan.v1.AtlasTierView
	(*AtlasPageView)(nil),              // 12: thinhthan.v1.AtlasPageView
	(*C2SQuestAccept)(nil),             // 13: thinhthan.v1.C2SQuestAccept
	(*S2CQuestAcceptResult)(nil),       // 14: thinhthan.v1.S2CQuestAcceptResult
	(*C2SQuestTurnIn)(nil),             // 15: thinhthan.v1.C2SQuestTurnIn
	(*S2CQuestUpdate)(nil),             // 16: thinhthan.v1.S2CQuestUpdate
	(*C2SAtlasClaim)(nil),              // 17: thinhthan.v1.C2SAtlasClaim
	(*S2CAtlasClaimResult)(nil),        // 18: thinhthan.v1.S2CAtlasClaimResult
	(*S2CProgressionEvent)(nil),        // 19: thinhthan.v1.S2CProgressionEvent
	(*C2SQuestAbandon)(nil),            // 20: thinhthan.v1.C2SQuestAbandon
	(*S2CQuestAbandonResult)(nil),      // 21: thinhthan.v1.S2CQuestAbandonResult
	(*C2SStoryBranchChoose)(nil),       // 22: thinhthan.v1.C2SStoryBranchChoose
	(*S2CStoryBranchResult)(nil),       // 23: thinhthan.v1.S2CStoryBranchResult
	(*C2SSkillUpgrade)(nil),            // 24: thinhthan.v1.C2SSkillUpgrade
	(*C2SPotentialAllocate)(nil),       // 25: thinhthan.v1.C2SPotentialAllocate
	(*C2SRespec)(nil),                  // 26: thinhthan.v1.C2SRespec
	(*S2CProgressionMutateResult)(nil), // 27: thinhthan.v1.S2CProgressionMutateResult
	(*S2CProgressionState)(nil),        // 28: thinhthan.v1.S2CProgressionState
	(*C2SDailyBoardRequest)(nil),       // 29: thinhthan.v1.C2SDailyBoardRequest
	(*S2CDailyBoardState)(nil),         // 30: thinhthan.v1.S2CDailyBoardState
	(*S2CAtlasState)(nil),              // 31: thinhthan.v1.S2CAtlasState
	(*ItemQuantity)(nil),               // 32: thinhthan.v1.ItemQuantity
	(*CurrencyDelta)(nil),              // 33: thinhthan.v1.CurrencyDelta
	(*OperationResult)(nil),            // 34: thinhthan.v1.OperationResult
	(*ItemGrant)(nil),                  // 35: thinhthan.v1.ItemGrant
	(ResultStatus)(0),                  // 36: thinhthan.v1.ResultStatus
	(ErrorCode)(0),                     // 37: thinhthan.v1.ErrorCode
}
var file_thinhthan_v1_content_proto_depIdxs = []int32{
	3,  // 0: thinhthan.v1.DailyQuestView.objectives:type_name -> thinhthan.v1.QuestObjectiveView
	32, // 1: thinhthan.v1.DailyQuestView.reward_preview:type_name -> thinhthan.v1.ItemQuantity
	0,  // 2: thinhthan.v1.DailyBoardEntry.state:type_name -> thinhthan.v1.QuestState
	7,  // 3: thinhthan.v1.DailyBoardEntry.hidden:type_name -> thinhthan.v1.MysteryBoardPlaceholder
	8,  // 4: thinhthan.v1.DailyBoardEntry.revealed:type_name -> thinhthan.v1.DailyQuestView
	33, // 5: thinhthan.v1.AtlasGrantView.currency_delta:type_name -> thinhthan.v1.CurrencyDelta
	10, // 6: thinhthan.v1.AtlasTierView.settled_grant:type_name -> thinhthan.v1.AtlasGrantView
	11, // 7: thinhthan.v1.AtlasPageView.tiers:type_name -> thinhthan.v1.AtlasTierView
	34, // 8: thinhthan.v1.S2CQuestAcceptResult.result:type_name -> thinhthan.v1.OperationResult
	34, // 9: thinhthan.v1.S2CQuestUpdate.result:type_name -> thinhthan.v1.OperationResult
	0,  // 10: thinhthan.v1.S2CQuestUpdate.state:type_name -> thinhthan.v1.QuestState
	3,  // 11: thinhthan.v1.S2CQuestUpdate.objectives:type_name -> thinhthan.v1.QuestObjectiveView
	35, // 12: thinhthan.v1.S2CQuestUpdate.granted:type_name -> thinhthan.v1.ItemGrant
	33, // 13: thinhthan.v1.S2CQuestUpdate.currency_delta:type_name -> thinhthan.v1.CurrencyDelta
	34, // 14: thinhthan.v1.S2CAtlasClaimResult.result:type_name -> thinhthan.v1.OperationResult
	10, // 15: thinhthan.v1.S2CAtlasClaimResult.granted:type_name -> thinhthan.v1.AtlasGrantView
	1,  // 16: thinhthan.v1.S2CProgressionEvent.event_kind:type_name -> thinhthan.v1.ProgressionEventKind
	34, // 17: thinhthan.v1.S2CQuestAbandonResult.result:type_name -> thinhthan.v1.OperationResult
	32, // 18: thinhthan.v1.S2CQuestAbandonResult.removed_items:type_name -> thinhthan.v1.ItemQuantity
	34, // 19: thinhthan.v1.S2CStoryBranchResult.result:type_name -> thinhthan.v1.OperationResult
	4,  // 20: thinhthan.v1.C2SPotentialAllocate.deltas:type_name -> thinhthan.v1.PotentialDelta
	2,  // 21: thinhthan.v1.C2SRespec.kind:type_name -> thinhthan.v1.RespecKind
	34, // 22: thinhthan.v1.S2CProgressionMutateResult.result:type_name -> thinhthan.v1.OperationResult
	4,  // 23: thinhthan.v1.S2CProgressionState.potential_allocated:type_name -> thinhthan.v1.PotentialDelta
	5,  // 24: thinhthan.v1.S2CProgressionState.skills:type_name -> thinhthan.v1.SkillView
	6,  // 25: thinhthan.v1.S2CProgressionState.skill_loadout:type_name -> thinhthan.v1.SkillLoadoutView
	36, // 26: thinhthan.v1.S2CDailyBoardState.status:type_name -> thinhthan.v1.ResultStatus
	37, // 27: thinhthan.v1.S2CDailyBoardState.error_code:type_name -> thinhthan.v1.ErrorCode
	9,  // 28: thinhthan.v1.S2CDailyBoardState.entries:type_name -> thinhthan.v1.DailyBoardEntry
	12, // 29: thinhthan.v1.S2CAtlasState.pages:type_name -> thinhthan.v1.AtlasPageView
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_content_proto_init() }
func file_thinhthan_v1_content_proto_init() {
	if File_thinhthan_v1_content_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	file_thinhthan_v1_content_proto_msgTypes[6].OneofWrappers = []any{
		(*DailyBoardEntry_Hidden)(nil),
		(*DailyBoardEntry_Revealed)(nil),
	}
	file_thinhthan_v1_content_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_content_proto_rawDesc), len(file_thinhthan_v1_content_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_content_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_content_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_content_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_content_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_content_proto = out.File
	file_thinhthan_v1_content_proto_goTypes = nil
	file_thinhthan_v1_content_proto_depIdxs = nil
}
