// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/market.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeCancelReason int32

const (
	TradeCancelReason_TRADE_CANCEL_REASON_UNSPECIFIED          TradeCancelReason = 0
	TradeCancelReason_TRADE_CANCEL_REASON_DECLINED             TradeCancelReason = 1
	TradeCancelReason_TRADE_CANCEL_REASON_CANCELLED            TradeCancelReason = 2
	TradeCancelReason_TRADE_CANCEL_REASON_EXPIRED              TradeCancelReason = 3
	TradeCancelReason_TRADE_CANCEL_REASON_INACTIVE_TIMEOUT     TradeCancelReason = 4
	TradeCancelReason_TRADE_CANCEL_REASON_PARTNER_DISCONNECTED TradeCancelReason = 5
	TradeCancelReason_TRADE_CANCEL_REASON_VALIDATION_FAILED    TradeCancelReason = 6
)

// Enum value maps for TradeCancelReason.
var (
	TradeCancelReason_name = map[int32]string{
		0: "TRADE_CANCEL_REASON_UNSPECIFIED",
		1: "TRADE_CANCEL_REASON_DECLINED",
		2: "TRADE_CANCEL_REASON_CANCELLED",
		3: "TRADE_CANCEL_REASON_EXPIRED",
		4: "TRADE_CANCEL_REASON_INACTIVE_TIMEOUT",
		5: "TRADE_CANCEL_REASON_PARTNER_DISCONNECTED",
		6: "TRADE_CANCEL_REASON_VALIDATION_FAILED",
	}
	TradeCancelReason_value = map[string]int32{
		"TRADE_CANCEL_REASON_UNSPECIFIED":          0,
		"TRADE_CANCEL_REASON_DECLINED":             1,
		"TRADE_CANCEL_REASON_CANCELLED":            2,
		"TRADE_CANCEL_REASON_EXPIRED":              3,
		"TRADE_CANCEL_REASON_INACTIVE_TIMEOUT":     4,
		"TRADE_CANCEL_REASON_PARTNER_DISCONNECTED": 5,
		"TRADE_CANCEL_REASON_VALIDATION_FAILED":    6,
	}
)

func (x TradeCancelReason) Enum() *TradeCancelReason {
	p := new(TradeCancelReason)
	*p = x
	return p
}

func (x TradeCancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeCancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[0].Descriptor()
}

func (TradeCancelReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[0]
}

func (x TradeCancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeCancelReason.Descriptor instead.
func (TradeCancelReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{0}
}

type TradeOfferState int32

const (
	TradeOfferState_TRADE_OFFER_STATE_UNSPECIFIED TradeOfferState = 0
	TradeOfferState_TRADE_OFFER_STATE_OPEN        TradeOfferState = 1
	TradeOfferState_TRADE_OFFER_STATE_LOCKED      TradeOfferState = 2
	TradeOfferState_TRADE_OFFER_STATE_COMMITTING  TradeOfferState = 3
)

// Enum value maps for TradeOfferState.
var (
	TradeOfferState_name = map[int32]string{
		0: "TRADE_OFFER_STATE_UNSPECIFIED",
		1: "TRADE_OFFER_STATE_OPEN",
		2: "TRADE_OFFER_STATE_LOCKED",
		3: "TRADE_OFFER_STATE_COMMITTING",
	}
	TradeOfferState_value = map[string]int32{
		"TRADE_OFFER_STATE_UNSPECIFIED": 0,
		"TRADE_OFFER_STATE_OPEN":        1,
		"TRADE_OFFER_STATE_LOCKED":      2,
		"TRADE_OFFER_STATE_COMMITTING":  3,
	}
)

func (x TradeOfferState) Enum() *TradeOfferState {
	p := new(TradeOfferState)
	*p = x
	return p
}

func (x TradeOfferState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeOfferState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[1].Descriptor()
}

func (TradeOfferState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[1]
}

func (x TradeOfferState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeOfferState.Descriptor instead.
func (TradeOfferState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{1}
}

type AuctionSort int32

const (
	AuctionSort_AUCTION_SORT_UNSPECIFIED AuctionSort = 0
	AuctionSort_AUCTION_SORT_PRICE_ASC   AuctionSort = 1
	AuctionSort_AUCTION_SORT_PRICE_DESC  AuctionSort = 2
	AuctionSort_AUCTION_SORT_NEWEST      AuctionSort = 3
)

// Enum value maps for AuctionSort.
var (
	AuctionSort_name = map[int32]string{
		0: "AUCTION_SORT_UNSPECIFIED",
		1: "AUCTION_SORT_PRICE_ASC",
		2: "AUCTION_SORT_PRICE_DESC",
		3: "AUCTION_SORT_NEWEST",
	}
	AuctionSort_value = map[string]int32{
		"AUCTION_SORT_UNSPECIFIED": 0,
		"AUCTION_SORT_PRICE_ASC":   1,
		"AUCTION_SORT_PRICE_DESC":  2,
		"AUCTION_SORT_NEWEST":      3,
	}
)

func (x AuctionSort) Enum() *AuctionSort {
	p := new(AuctionSort)
	*p = x
	return p
}

func (x AuctionSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionSort) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[2].Descriptor()
}

func (AuctionSort) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[2]
}

func (x AuctionSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionSort.Descriptor instead.
func (AuctionSort) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{2}
}

type AuctionListingState int32

const (
	AuctionListingState_AUCTION_LISTING_STATE_UNSPECIFIED AuctionListingState = 0
	AuctionListingState_AUCTION_LISTING_STATE_ACTIVE      AuctionListingState = 1
	AuctionListingState_AUCTION_LISTING_STATE_SETTLING    AuctionListingState = 2
	AuctionListingState_AUCTION_LISTING_STATE_SOLD        AuctionListingState = 3
	AuctionListingState_AUCTION_LISTING_STATE_CANCELLED   AuctionListingState = 4
	AuctionListingState_AUCTION_LISTING_STATE_EXPIRED     AuctionListingState = 5
)

// Enum value maps for AuctionListingState.
var (
	AuctionListingState_name = map[int32]string{
		0: "AUCTION_LISTING_STATE_UNSPECIFIED",
		1: "AUCTION_LISTING_STATE_ACTIVE",
		2: "AUCTION_LISTING_STATE_SETTLING",
		3: "AUCTION_LISTING_STATE_SOLD",
		4: "AUCTION_LISTING_STATE_CANCELLED",
		5: "AUCTION_LISTING_STATE_EXPIRED",
	}
	AuctionListingState_value = map[string]int32{
		"AUCTION_LISTING_STATE_UNSPECIFIED": 0,
		"AUCTION_LISTING_STATE_ACTIVE":      1,
		"AUCTION_LISTING_STATE_SETTLING":    2,
		"AUCTION_LISTING_STATE_SOLD":        3,
		"AUCTION_LISTING_STATE_CANCELLED":   4,
		"AUCTION_LISTING_STATE_EXPIRED":     5,
	}
)

func (x AuctionListingState) Enum() *AuctionListingState {
	p := new(AuctionListingState)
	*p = x
	return p
}

func (x AuctionListingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionListingState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[3].Descriptor()
}

func (AuctionListingState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[3]
}

func (x AuctionListingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionListingState.Descriptor instead.
func (AuctionListingState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{3}
}

type AuctionEscrowReason int32

const (
	AuctionEscrowReason_AUCTION_ESCROW_REASON_UNSPECIFIED AuctionEscrowReason = 0
	AuctionEscrowReason_AUCTION_ESCROW_REASON_CANCELLED   AuctionEscrowReason = 1
	AuctionEscrowReason_AUCTION_ESCROW_REASON_EXPIRED     AuctionEscrowReason = 2
)

// Enum value maps for AuctionEscrowReason.
var (
	AuctionEscrowReason_name = map[int32]string{
		0: "AUCTION_ESCROW_REASON_UNSPECIFIED",
		1: "AUCTION_ESCROW_REASON_CANCELLED",
		2: "AUCTION_ESCROW_REASON_EXPIRED",
	}
	AuctionEscrowReason_value = map[string]int32{
		"AUCTION_ESCROW_REASON_UNSPECIFIED": 0,
		"AUCTION_ESCROW_REASON_CANCELLED":   1,
		"AUCTION_ESCROW_REASON_EXPIRED":     2,
	}
)

func (x AuctionEscrowReason) Enum() *AuctionEscrowReason {
	p := new(AuctionEscrowReason)
	*p = x
	return p
}

func (x AuctionEscrowReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionEscrowReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[4].Descriptor()
}

func (AuctionEscrowReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[4]
}

func (x AuctionEscrowReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionEscrowReason.Descriptor instead.
func (AuctionEscrowReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{4}
}

type AuctionProceedsState int32

const (
	AuctionProceedsState_AUCTION_PROCEEDS_STATE_UNSPECIFIED AuctionProceedsState = 0
	AuctionProceedsState_AUCTION_PROCEEDS_STATE_PENDING     AuctionProceedsState = 1
	AuctionProceedsState_AUCTION_PROCEEDS_STATE_CLAIMED     AuctionProceedsState = 2
)

// Enum value maps for AuctionProceedsState.
var (
	AuctionProceedsState_name = map[int32]string{
		0: "AUCTION_PROCEEDS_STATE_UNSPECIFIED",
		1: "AUCTION_PROCEEDS_STATE_PENDING",
		2: "AUCTION_PROCEEDS_STATE_CLAIMED",
	}
	AuctionProceedsState_value = map[string]int32{
		"AUCTION_PROCEEDS_STATE_UNSPECIFIED": 0,
		"AUCTION_PROCEEDS_STATE_PENDING":     1,
		"AUCTION_PROCEEDS_STATE_CLAIMED":     2,
	}
)

func (x AuctionProceedsState) Enum() *AuctionProceedsState {
	p := new(AuctionProceedsState)
	*p = x
	return p
}

func (x AuctionProceedsState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuctionProceedsState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_market_proto_enumTypes[5].Descriptor()
}

func (AuctionProceedsState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_market_proto_enumTypes[5]
}

func (x AuctionProceedsState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuctionProceedsState.Descriptor instead.
func (AuctionProceedsState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{5}
}

// ID 700
type C2STradeInvite struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                     // UUID, 16 bytes
	TargetCharacterId []byte                 `protobuf:"bytes,2,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"` // UUID, 16 bytes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *C2STradeInvite) Reset() {
	*x = C2STradeInvite{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2STradeInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STradeInvite) ProtoMessage() {}

func (x *C2STradeInvite) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STradeInvite.ProtoReflect.Descriptor instead.
func (*C2STradeInvite) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *C2STradeInvite) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2STradeInvite) GetTargetCharacterId() []byte {
	if x != nil {
		return x.TargetCharacterId
	}
	return nil
}

// ID 701
type S2CTradeInvite struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TradeId            []byte                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                                    // UUID, 16 bytes
	InviterCharacterId []byte                 `protobuf:"bytes,2,opt,name=inviter_character_id,json=inviterCharacterId,proto3" json:"inviter_character_id,omitempty"` // UUID, 16 bytes
	InviterName        string                 `protobuf:"bytes,3,opt,name=inviter_name,json=inviterName,proto3" json:"inviter_name,omitempty"`
	ExpiresInSeconds   uint32                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2CTradeInvite) Reset() {
	*x = S2CTradeInvite{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CTradeInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTradeInvite) ProtoMessage() {}

func (x *S2CTradeInvite) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTradeInvite.ProtoReflect.Descriptor instead.
func (*S2CTradeInvite) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *S2CTradeInvite) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2CTradeInvite) GetInviterCharacterId() []byte {
	if x != nil {
		return x.InviterCharacterId
	}
	return nil
}

func (x *S2CTradeInvite) GetInviterName() string {
	if x != nil {
		return x.InviterName
	}
	return ""
}

func (x *S2CTradeInvite) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// ID 702
type C2STradeAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId       []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2STradeAccept) Reset() {
	*x = C2STradeAccept{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2STradeAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STradeAccept) ProtoMessage() {}

func (x *C2STradeAccept) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STradeAccept.ProtoReflect.Descriptor instead.
func (*C2STradeAccept) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *C2STradeAccept) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2STradeAccept) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

// ID 703
type C2STradeCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId       []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2STradeCancel) Reset() {
	*x = C2STradeCancel{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2STradeCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STradeCancel) ProtoMessage() {}

func (x *C2STradeCancel) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STradeCancel.ProtoReflect.Descriptor instead.
func (*C2STradeCancel) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *C2STradeCancel) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2STradeCancel) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

// ID 704
type S2CTradeCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       []byte                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // UUID, 16 bytes
	Reason        TradeCancelReason      `protobuf:"varint,2,opt,name=reason,proto3,enum=thinhthan.v1.TradeCancelReason" json:"reason,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CTradeCancelled) Reset() {
	*x = S2CTradeCancelled{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CTradeCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTradeCancelled) ProtoMessage() {}

func (x *S2CTradeCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTradeCancelled.ProtoReflect.Descriptor instead.
func (*S2CTradeCancelled) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *S2CTradeCancelled) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2CTradeCancelled) GetReason() TradeCancelReason {
	if x != nil {
		return x.Reason
	}
	return TradeCancelReason_TRADE_CANCEL_REASON_UNSPECIFIED
}

func (x *S2CTradeCancelled) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

type TradeOfferItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemInstanceId []byte                 `protobuf:"bytes,1,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"` // UUID, 16 bytes
	Quantity       uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeOfferItem) Reset() {
	*x = TradeOfferItem{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeOfferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOfferItem) ProtoMessage() {}

func (x *TradeOfferItem) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOfferItem.ProtoReflect.Descriptor instead.
func (*TradeOfferItem) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *TradeOfferItem) GetItemInstanceId() []byte {
	if x != nil {
		return x.ItemInstanceId
	}
	return nil
}

func (x *TradeOfferItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ID 705
type C2STradeOfferUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId          []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID, 16 bytes
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Items            []*TradeOfferItem      `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                    // full replacement of own offer
	CommonAmount     int64                  `protobuf:"varint,5,opt,name=common_amount,json=commonAmount,proto3" json:"common_amount,omitempty"` // >= 0
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2STradeOfferUpdate) Reset() {
	*x = C2STradeOfferUpdate{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2STradeOfferUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STradeOfferUpdate) ProtoMessage() {}

func (x *C2STradeOfferUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STradeOfferUpdate.ProtoReflect.Descriptor instead.
func (*C2STradeOfferUpdate) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{6}
}

func (x *C2STradeOfferUpdate) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2STradeOfferUpdate) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *C2STradeOfferUpdate) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *C2STradeOfferUpdate) GetItems() []*TradeOfferItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *C2STradeOfferUpdate) GetCommonAmount() int64 {
	if x != nil {
		return x.CommonAmount
	}
	return 0
}

type TradeSide struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	Items         []*ItemInstanceView    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CommonAmount  int64                  `protobuf:"varint,3,opt,name=common_amount,json=commonAmount,proto3" json:"common_amount,omitempty"`
	Confirmed     bool                   `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeSide) Reset() {
	*x = TradeSide{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeSide) ProtoMessage() {}

func (x *TradeSide) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeSide.ProtoReflect.Descriptor instead.
func (*TradeSide) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *TradeSide) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *TradeSide) GetItems() []*ItemInstanceView {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TradeSide) GetCommonAmount() int64 {
	if x != nil {
		return x.CommonAmount
	}
	return 0
}

func (x *TradeSide) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

// ID 706
type S2CTradeOfferState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       []byte                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"` // UUID, 16 bytes
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	State         TradeOfferState        `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.TradeOfferState" json:"state,omitempty"`
	Sides         []*TradeSide           `protobuf:"bytes,4,rep,name=sides,proto3" json:"sides,omitempty"` // exactly 2
	FeePreview    int64                  `protobuf:"varint,5,opt,name=fee_preview,json=feePreview,proto3" json:"fee_preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CTradeOfferState) Reset() {
	*x = S2CTradeOfferState{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CTradeOfferState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTradeOfferState) ProtoMessage() {}

func (x *S2CTradeOfferState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTradeOfferState.ProtoReflect.Descriptor instead.
func (*S2CTradeOfferState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{8}
}

func (x *S2CTradeOfferState) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2CTradeOfferState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *S2CTradeOfferState) GetState() TradeOfferState {
	if x != nil {
		return x.State
	}
	return TradeOfferState_TRADE_OFFER_STATE_UNSPECIFIED
}

func (x *S2CTradeOfferState) GetSides() []*TradeSide {
	if x != nil {
		return x.Sides
	}
	return nil
}

func (x *S2CTradeOfferState) GetFeePreview() int64 {
	if x != nil {
		return x.FeePreview
	}
	return 0
}

// ID 707
type C2STradeConfirm struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId          []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID, 16 bytes
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2STradeConfirm) Reset() {
	*x = C2STradeConfirm{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2STradeConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STradeConfirm) ProtoMessage() {}

func (x *C2STradeConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STradeConfirm.ProtoReflect.Descriptor instead.
func (*C2STradeConfirm) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{9}
}

func (x *C2STradeConfirm) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2STradeConfirm) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *C2STradeConfirm) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

// ID 708
type C2STradeFinalise struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	TradeId          []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`             // UUID, 16 bytes
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *C2STradeFinalise) Reset() {
	*x = C2STradeFinalise{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2STradeFinalise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2STradeFinalise) ProtoMessage() {}

func (x *C2STradeFinalise) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2STradeFinalise.ProtoReflect.Descriptor instead.
func (*C2STradeFinalise) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{10}
}

func (x *C2STradeFinalise) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2STradeFinalise) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *C2STradeFinalise) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

// ID 709
type S2CTradeResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                                 // operation_id empty when partner-triggered
	TradeId        []byte                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                // UUID, 16 bytes
	SettlementId   []byte                 `protobuf:"bytes,3,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"` // UUID, 16 bytes
	Received       []*ItemGrant           `protobuf:"bytes,4,rep,name=received,proto3" json:"received,omitempty"`
	CommonReceived int64                  `protobuf:"varint,5,opt,name=common_received,json=commonReceived,proto3" json:"common_received,omitempty"`
	Fee            int64                  `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CTradeResult) Reset() {
	*x = S2CTradeResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CTradeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTradeResult) ProtoMessage() {}

func (x *S2CTradeResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTradeResult.ProtoReflect.Descriptor instead.
func (*S2CTradeResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{11}
}

func (x *S2CTradeResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CTradeResult) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

func (x *S2CTradeResult) GetSettlementId() []byte {
	if x != nil {
		return x.SettlementId
	}
	return nil
}

func (x *S2CTradeResult) GetReceived() []*ItemGrant {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *S2CTradeResult) GetCommonReceived() int64 {
	if x != nil {
		return x.CommonReceived
	}
	return 0
}

func (x *S2CTradeResult) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// ID 710
type S2CTradeRequestResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	RequestMessageId uint32                 `protobuf:"varint,2,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"` // 700 | 702 | 703 | 705 | 707
	TradeId          []byte                 `protobuf:"bytes,3,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                               // UUID, 16 bytes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2CTradeRequestResult) Reset() {
	*x = S2CTradeRequestResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CTradeRequestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTradeRequestResult) ProtoMessage() {}

func (x *S2CTradeRequestResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTradeRequestResult.ProtoReflect.Descriptor instead.
func (*S2CTradeRequestResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{12}
}

func (x *S2CTradeRequestResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CTradeRequestResult) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2CTradeRequestResult) GetTradeId() []byte {
	if x != nil {
		return x.TradeId
	}
	return nil
}

// ID 730
type C2SAuctionList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`            // UUID, 16 bytes
	ItemInstanceId []byte                 `protobuf:"bytes,2,opt,name=item_instance_id,json=itemInstanceId,proto3" json:"item_instance_id,omitempty"` // UUID, 16 bytes
	Quantity       uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                    // whole lot
	PriceCommon    int64                  `protobuf:"varint,4,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`           // total lot price
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *C2SAuctionList) Reset() {
	*x = C2SAuctionList{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuctionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionList) ProtoMessage() {}

func (x *C2SAuctionList) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionList.ProtoReflect.Descriptor instead.
func (*C2SAuctionList) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{13}
}

func (x *C2SAuctionList) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAuctionList) GetItemInstanceId() []byte {
	if x != nil {
		return x.ItemInstanceId
	}
	return nil
}

func (x *C2SAuctionList) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *C2SAuctionList) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

// ID 731
type S2CAuctionListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ListingId     []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID, 16 bytes
	ListingFee    int64                  `protobuf:"varint,3,opt,name=listing_fee,json=listingFee,proto3" json:"listing_fee,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuctionListResult) Reset() {
	*x = S2CAuctionListResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionListResult) ProtoMessage() {}

func (x *S2CAuctionListResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionListResult.ProtoReflect.Descriptor instead.
func (*S2CAuctionListResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{14}
}

func (x *S2CAuctionListResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAuctionListResult) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2CAuctionListResult) GetListingFee() int64 {
	if x != nil {
		return x.ListingFee
	}
	return 0
}

func (x *S2CAuctionListResult) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ID 732
type C2SAuctionBuy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationId         []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ListingId           []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`       // UUID, 16 bytes
	ExpectedPriceCommon int64                  `protobuf:"varint,3,opt,name=expected_price_common,json=expectedPriceCommon,proto3" json:"expected_price_common,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *C2SAuctionBuy) Reset() {
	*x = C2SAuctionBuy{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuctionBuy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionBuy) ProtoMessage() {}

func (x *C2SAuctionBuy) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionBuy.ProtoReflect.Descriptor instead.
func (*C2SAuctionBuy) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{15}
}

func (x *C2SAuctionBuy) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAuctionBuy) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *C2SAuctionBuy) GetExpectedPriceCommon() int64 {
	if x != nil {
		return x.ExpectedPriceCommon
	}
	return 0
}

// ID 733
type S2CAuctionBuyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ListingId     []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID, 16 bytes
	PriceCommon   int64                  `protobuf:"varint,3,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	Received      *ItemInstanceView      `protobuf:"bytes,4,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuctionBuyResult) Reset() {
	*x = S2CAuctionBuyResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionBuyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionBuyResult) ProtoMessage() {}

func (x *S2CAuctionBuyResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionBuyResult.ProtoReflect.Descriptor instead.
func (*S2CAuctionBuyResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{16}
}

func (x *S2CAuctionBuyResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAuctionBuyResult) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2CAuctionBuyResult) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *S2CAuctionBuyResult) GetReceived() *ItemInstanceView {
	if x != nil {
		return x.Received
	}
	return nil
}

// ID 734
type C2SAuctionCancelListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ListingId     []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`       // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAuctionCancelListing) Reset() {
	*x = C2SAuctionCancelListing{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuctionCancelListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionCancelListing) ProtoMessage() {}

func (x *C2SAuctionCancelListing) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionCancelListing.ProtoReflect.Descriptor instead.
func (*C2SAuctionCancelListing) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{17}
}

func (x *C2SAuctionCancelListing) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAuctionCancelListing) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

// ID 735
type S2CAuctionCancelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ListingId     []byte                 `protobuf:"bytes,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`               // UUID, 16 bytes
	EscrowAssetId []byte                 `protobuf:"bytes,3,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuctionCancelResult) Reset() {
	*x = S2CAuctionCancelResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionCancelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionCancelResult) ProtoMessage() {}

func (x *S2CAuctionCancelResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionCancelResult.ProtoReflect.Descriptor instead.
func (*S2CAuctionCancelResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{18}
}

func (x *S2CAuctionCancelResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAuctionCancelResult) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2CAuctionCancelResult) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

// ID 736
type S2CAuctionSold struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ListingId      []byte                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID, 16 bytes
	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity       uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceCommon    int64                  `protobuf:"varint,4,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	Tax            int64                  `protobuf:"varint,5,opt,name=tax,proto3" json:"tax,omitempty"`
	ProceedsId     []byte                 `protobuf:"bytes,6,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"` // UUID, 16 bytes
	ProceedsAmount int64                  `protobuf:"varint,7,opt,name=proceeds_amount,json=proceedsAmount,proto3" json:"proceeds_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CAuctionSold) Reset() {
	*x = S2CAuctionSold{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionSold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionSold) ProtoMessage() {}

func (x *S2CAuctionSold) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionSold.ProtoReflect.Descriptor instead.
func (*S2CAuctionSold) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{19}
}

func (x *S2CAuctionSold) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *S2CAuctionSold) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *S2CAuctionSold) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *S2CAuctionSold) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *S2CAuctionSold) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *S2CAuctionSold) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

func (x *S2CAuctionSold) GetProceedsAmount() int64 {
	if x != nil {
		return x.ProceedsAmount
	}
	return 0
}

// ID 738
type C2SAuctionSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes; echo only
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Tier          uint32                 `protobuf:"varint,4,opt,name=tier,proto3" json:"tier,omitempty"`
	MinPrice      int64                  `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int64                  `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Sort          AuctionSort            `protobuf:"varint,7,opt,name=sort,proto3,enum=thinhthan.v1.AuctionSort" json:"sort,omitempty"`
	PageCursor    string                 `protobuf:"bytes,8,opt,name=page_cursor,json=pageCursor,proto3" json:"page_cursor,omitempty"` // opaque
	PageSize      uint32                 `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`      // 1..50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAuctionSearch) Reset() {
	*x = C2SAuctionSearch{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuctionSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionSearch) ProtoMessage() {}

func (x *C2SAuctionSearch) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionSearch.ProtoReflect.Descriptor instead.
func (*C2SAuctionSearch) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{20}
}

func (x *C2SAuctionSearch) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAuctionSearch) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *C2SAuctionSearch) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *C2SAuctionSearch) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *C2SAuctionSearch) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *C2SAuctionSearch) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *C2SAuctionSearch) GetSort() AuctionSort {
	if x != nil {
		return x.Sort
	}
	return AuctionSort_AUCTION_SORT_UNSPECIFIED
}

func (x *C2SAuctionSearch) GetPageCursor() string {
	if x != nil {
		return x.PageCursor
	}
	return ""
}

func (x *C2SAuctionSearch) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AuctionSearchRow struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ListingId         []byte                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID, 16 bytes
	Item              *ItemInstanceView      `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	PriceCommon       int64                  `protobuf:"varint,3,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	SellerDisplayName string                 `protobuf:"bytes,4,opt,name=seller_display_name,json=sellerDisplayName,proto3" json:"seller_display_name,omitempty"`
	ExpiresAt         int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuctionSearchRow) Reset() {
	*x = AuctionSearchRow{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionSearchRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionSearchRow) ProtoMessage() {}

func (x *AuctionSearchRow) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionSearchRow.ProtoReflect.Descriptor instead.
func (*AuctionSearchRow) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{21}
}

func (x *AuctionSearchRow) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *AuctionSearchRow) GetItem() *ItemInstanceView {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *AuctionSearchRow) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *AuctionSearchRow) GetSellerDisplayName() string {
	if x != nil {
		return x.SellerDisplayName
	}
	return ""
}

func (x *AuctionSearchRow) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ID 739
type S2CAuctionSearchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Rows           []*AuctionSearchRow    `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	NextPageCursor string                 `protobuf:"bytes,3,opt,name=next_page_cursor,json=nextPageCursor,proto3" json:"next_page_cursor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CAuctionSearchResult) Reset() {
	*x = S2CAuctionSearchResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionSearchResult) ProtoMessage() {}

func (x *S2CAuctionSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionSearchResult.ProtoReflect.Descriptor instead.
func (*S2CAuctionSearchResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{22}
}

func (x *S2CAuctionSearchResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAuctionSearchResult) GetRows() []*AuctionSearchRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *S2CAuctionSearchResult) GetNextPageCursor() string {
	if x != nil {
		return x.NextPageCursor
	}
	return ""
}

// ID 740
type C2SAuctionReclaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`         // UUID, 16 bytes
	EscrowAssetId []byte                 `protobuf:"bytes,2,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAuctionReclaim) Reset() {
	*x = C2SAuctionReclaim{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuctionReclaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionReclaim) ProtoMessage() {}

func (x *C2SAuctionReclaim) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionReclaim.ProtoReflect.Descriptor instead.
func (*C2SAuctionReclaim) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{23}
}

func (x *C2SAuctionReclaim) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAuctionReclaim) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

// ID 741
type S2CAuctionReclaimResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	EscrowAssetId []byte                 `protobuf:"bytes,2,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID, 16 bytes
	Received      *ItemInstanceView      `protobuf:"bytes,3,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuctionReclaimResult) Reset() {
	*x = S2CAuctionReclaimResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionReclaimResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionReclaimResult) ProtoMessage() {}

func (x *S2CAuctionReclaimResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionReclaimResult.ProtoReflect.Descriptor instead.
func (*S2CAuctionReclaimResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{24}
}

func (x *S2CAuctionReclaimResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAuctionReclaimResult) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

func (x *S2CAuctionReclaimResult) GetReceived() *ItemInstanceView {
	if x != nil {
		return x.Received
	}
	return nil
}

// ID 742
type C2SAuctionProceedsClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ProceedsId    []byte                 `protobuf:"bytes,2,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"`    // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAuctionProceedsClaim) Reset() {
	*x = C2SAuctionProceedsClaim{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuctionProceedsClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuctionProceedsClaim) ProtoMessage() {}

func (x *C2SAuctionProceedsClaim) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuctionProceedsClaim.ProtoReflect.Descriptor instead.
func (*C2SAuctionProceedsClaim) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{25}
}

func (x *C2SAuctionProceedsClaim) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SAuctionProceedsClaim) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

// ID 743
type S2CAuctionProceedsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ProceedsId    []byte                 `protobuf:"bytes,2,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"` // UUID, 16 bytes
	AmountCommon  int64                  `protobuf:"varint,3,opt,name=amount_common,json=amountCommon,proto3" json:"amount_common,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuctionProceedsResult) Reset() {
	*x = S2CAuctionProceedsResult{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionProceedsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionProceedsResult) ProtoMessage() {}

func (x *S2CAuctionProceedsResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionProceedsResult.ProtoReflect.Descriptor instead.
func (*S2CAuctionProceedsResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{26}
}

func (x *S2CAuctionProceedsResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CAuctionProceedsResult) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

func (x *S2CAuctionProceedsResult) GetAmountCommon() int64 {
	if x != nil {
		return x.AmountCommon
	}
	return 0
}

type AuctionListingView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     []byte                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"` // UUID, 16 bytes
	Item          *ItemInstanceView      `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	PriceCommon   int64                  `protobuf:"varint,3,opt,name=price_common,json=priceCommon,proto3" json:"price_common,omitempty"`
	State         AuctionListingState    `protobuf:"varint,4,opt,name=state,proto3,enum=thinhthan.v1.AuctionListingState" json:"state,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionListingView) Reset() {
	*x = AuctionListingView{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionListingView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionListingView) ProtoMessage() {}

func (x *AuctionListingView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionListingView.ProtoReflect.Descriptor instead.
func (*AuctionListingView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{27}
}

func (x *AuctionListingView) GetListingId() []byte {
	if x != nil {
		return x.ListingId
	}
	return nil
}

func (x *AuctionListingView) GetItem() *ItemInstanceView {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *AuctionListingView) GetPriceCommon() int64 {
	if x != nil {
		return x.PriceCommon
	}
	return 0
}

func (x *AuctionListingView) GetState() AuctionListingState {
	if x != nil {
		return x.State
	}
	return AuctionListingState_AUCTION_LISTING_STATE_UNSPECIFIED
}

func (x *AuctionListingView) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type AuctionEscrowAssetView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowAssetId []byte                 `protobuf:"bytes,1,opt,name=escrow_asset_id,json=escrowAssetId,proto3" json:"escrow_asset_id,omitempty"` // UUID, 16 bytes
	Item          *ItemInstanceView      `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Reason        AuctionEscrowReason    `protobuf:"varint,3,opt,name=reason,proto3,enum=thinhthan.v1.AuctionEscrowReason" json:"reason,omitempty"`
	AutoClaimAt   int64                  `protobuf:"varint,4,opt,name=auto_claim_at,json=autoClaimAt,proto3" json:"auto_claim_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionEscrowAssetView) Reset() {
	*x = AuctionEscrowAssetView{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionEscrowAssetView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionEscrowAssetView) ProtoMessage() {}

func (x *AuctionEscrowAssetView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionEscrowAssetView.ProtoReflect.Descriptor instead.
func (*AuctionEscrowAssetView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{28}
}

func (x *AuctionEscrowAssetView) GetEscrowAssetId() []byte {
	if x != nil {
		return x.EscrowAssetId
	}
	return nil
}

func (x *AuctionEscrowAssetView) GetItem() *ItemInstanceView {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *AuctionEscrowAssetView) GetReason() AuctionEscrowReason {
	if x != nil {
		return x.Reason
	}
	return AuctionEscrowReason_AUCTION_ESCROW_REASON_UNSPECIFIED
}

func (x *AuctionEscrowAssetView) GetAutoClaimAt() int64 {
	if x != nil {
		return x.AutoClaimAt
	}
	return 0
}

type AuctionProceedsView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProceedsId    []byte                 `protobuf:"bytes,1,opt,name=proceeds_id,json=proceedsId,proto3" json:"proceeds_id,omitempty"` // UUID, 16 bytes
	AmountCommon  int64                  `protobuf:"varint,2,opt,name=amount_common,json=amountCommon,proto3" json:"amount_common,omitempty"`
	State         AuctionProceedsState   `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.AuctionProceedsState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionProceedsView) Reset() {
	*x = AuctionProceedsView{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionProceedsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionProceedsView) ProtoMessage() {}

func (x *AuctionProceedsView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionProceedsView.ProtoReflect.Descriptor instead.
func (*AuctionProceedsView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{29}
}

func (x *AuctionProceedsView) GetProceedsId() []byte {
	if x != nil {
		return x.ProceedsId
	}
	return nil
}

func (x *AuctionProceedsView) GetAmountCommon() int64 {
	if x != nil {
		return x.AmountCommon
	}
	return 0
}

func (x *AuctionProceedsView) GetState() AuctionProceedsState {
	if x != nil {
		return x.State
	}
	return AuctionProceedsState_AUCTION_PROCEEDS_STATE_UNSPECIFIED
}

// ID 744
type S2CAuctionMyState struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Listings      []*AuctionListingView     `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	EscrowAssets  []*AuctionEscrowAssetView `protobuf:"bytes,2,rep,name=escrow_assets,json=escrowAssets,proto3" json:"escrow_assets,omitempty"`
	Proceeds      []*AuctionProceedsView    `protobuf:"bytes,3,rep,name=proceeds,proto3" json:"proceeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuctionMyState) Reset() {
	*x = S2CAuctionMyState{}
	mi := &file_thinhthan_v1_market_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuctionMyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuctionMyState) ProtoMessage() {}

func (x *S2CAuctionMyState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_market_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuctionMyState.ProtoReflect.Descriptor instead.
func (*S2CAuctionMyState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_market_proto_rawDescGZIP(), []int{30}
}

func (x *S2CAuctionMyState) GetListings() []*AuctionListingView {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *S2CAuctionMyState) GetEscrowAssets() []*AuctionEscrowAssetView {
	if x != nil {
		return x.EscrowAssets
	}
	return nil
}

func (x *S2CAuctionMyState) GetProceeds() []*AuctionProceedsView {
	if x != nil {
		return x.Proceeds
	}
	return nil
}

var File_thinhthan_v1_market_proto protoreflect.FileDescriptor

const file_thinhthan_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x19thinhthan/v1/market.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\x1a\x1athinhthan/v1/durable.proto\"c\n" +
	"\x0eC2STradeInvite\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12.\n" +
	"\x13target_character_id\x18\x02 \x01(\fR\x11targetCharacterId\"\xae\x01\n" +
	"\x0eS2CTradeInvite\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\fR\atradeId\x120\n" +
	"\x14inviter_character_id\x18\x02 \x01(\fR\x12inviterCharacterId\x12!\n" +
	"\finviter_name\x18\x03 \x01(\tR\vinviterName\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\rR\x10expiresInSeconds\"N\n" +
	"\x0eC2STradeAccept\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\"N\n" +
	"\x0eC2STradeCancel\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\"\x9f\x01\n" +
	"\x11S2CTradeCancelled\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\fR\atradeId\x127\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1f.thinhthan.v1.TradeCancelReasonR\x06reason\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"V\n" +
	"\x0eTradeOfferItem\x12(\n" +
	"\x10item_instance_id\x18\x01 \x01(\fR\x0eitemInstanceId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\xd9\x01\n" +
	"\x13C2STradeOfferUpdate\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.thinhthan.v1.TradeOfferItemR\x05items\x12#\n" +
	"\rcommon_amount\x18\x05 \x01(\x03R\fcommonAmount\"\xa7\x01\n" +
	"\tTradeSide\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x124\n" +
	"\x05items\x18\x02 \x03(\v2\x1e.thinhthan.v1.ItemInstanceViewR\x05items\x12#\n" +
	"\rcommon_amount\x18\x03 \x01(\x03R\fcommonAmount\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed\"\xd0\x01\n" +
	"\x12S2CTradeOfferState\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\fR\atradeId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.thinhthan.v1.TradeOfferStateR\x05state\x12-\n" +
	"\x05sides\x18\x04 \x03(\v2\x17.thinhthan.v1.TradeSideR\x05sides\x12\x1f\n" +
	"\vfee_preview\x18\x05 \x01(\x03R\n" +
	"feePreview\"|\n" +
	"\x0fC2STradeConfirm\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\"}\n" +
	"\x10C2STradeFinalise\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\"\xf7\x01\n" +
	"\x0eS2CTradeResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\fR\atradeId\x12#\n" +
	"\rsettlement_id\x18\x03 \x01(\fR\fsettlementId\x123\n" +
	"\breceived\x18\x04 \x03(\v2\x17.thinhthan.v1.ItemGrantR\breceived\x12'\n" +
	"\x0fcommon_received\x18\x05 \x01(\x03R\x0ecommonReceived\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x03R\x03fee\"\x97\x01\n" +
	"\x15S2CTradeRequestResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12,\n" +
	"\x12request_message_id\x18\x02 \x01(\rR\x10requestMessageId\x12\x19\n" +
	"\btrade_id\x18\x03 \x01(\fR\atradeId\"\x9c\x01\n" +
	"\x0eC2SAuctionList\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12(\n" +
	"\x10item_instance_id\x18\x02 \x01(\fR\x0eitemInstanceId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12!\n" +
	"\fprice_common\x18\x04 \x01(\x03R\vpriceCommon\"\xac\x01\n" +
	"\x14S2CAuctionListResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x12\x1f\n" +
	"\vlisting_fee\x18\x03 \x01(\x03R\n" +
	"listingFee\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\x85\x01\n" +
	"\rC2SAuctionBuy\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x122\n" +
	"\x15expected_price_common\x18\x03 \x01(\x03R\x13expectedPriceCommon\"\xca\x01\n" +
	"\x13S2CAuctionBuyResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x12!\n" +
	"\fprice_common\x18\x03 \x01(\x03R\vpriceCommon\x12:\n" +
	"\breceived\x18\x04 \x01(\v2\x1e.thinhthan.v1.ItemInstanceViewR\breceived\"[\n" +
	"\x17C2SAuctionCancelListing\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\"\x96\x01\n" +
	"\x16S2CAuctionCancelResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\fR\tlistingId\x12&\n" +
	"\x0fescrow_asset_id\x18\x03 \x01(\fR\rescrowAssetId\"\xe3\x01\n" +
	"\x0eS2CAuctionSold\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\fR\tlistingId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12!\n" +
	"\fprice_common\x18\x04 \x01(\x03R\vpriceCommon\x12\x10\n" +
	"\x03tax\x18\x05 \x01(\x03R\x03tax\x12\x1f\n" +
	"\vproceeds_id\x18\x06 \x01(\fR\n" +
	"proceedsId\x12'\n" +
	"\x0fproceeds_amount\x18\a \x01(\x03R\x0eproceedsAmount\"\xa5\x02\n" +
	"\x10C2SAuctionSearch\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\rR\x04tier\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x03R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x03R\bmaxPrice\x12-\n" +
	"\x04sort\x18\a \x01(\x0e2\x19.thinhthan.v1.AuctionSortR\x04sort\x12\x1f\n" +
	"\vpage_cursor\x18\b \x01(\tR\n" +
	"pageCursor\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\rR\bpageSize\"\xd7\x01\n" +
	"\x10AuctionSearchRow\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\fR\tlistingId\x122\n" +
	"\x04item\x18\x02 \x01(\v2\x1e.thinhthan.v1.ItemInstanceViewR\x04item\x12!\n" +
	"\fprice_common\x18\x03 \x01(\x03R\vpriceCommon\x12.\n" +
	"\x13seller_display_name\x18\x04 \x01(\tR\x11sellerDisplayName\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"\xad\x01\n" +
	"\x16S2CAuctionSearchResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x122\n" +
	"\x04rows\x18\x02 \x03(\v2\x1e.thinhthan.v1.AuctionSearchRowR\x04rows\x12(\n" +
	"\x10next_page_cursor\x18\x03 \x01(\tR\x0enextPageCursor\"^\n" +
	"\x11C2SAuctionReclaim\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12&\n" +
	"\x0fescrow_asset_id\x18\x02 \x01(\fR\rescrowAssetId\"\xb4\x01\n" +
	"\x17S2CAuctionReclaimResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12&\n" +
	"\x0fescrow_asset_id\x18\x02 \x01(\fR\rescrowAssetId\x12:\n" +
	"\breceived\x18\x03 \x01(\v2\x1e.thinhthan.v1.ItemInstanceViewR\breceived\"]\n" +
	"\x17C2SAuctionProceedsClaim\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1f\n" +
	"\vproceeds_id\x18\x02 \x01(\fR\n" +
	"proceedsId\"\x97\x01\n" +
	"\x18S2CAuctionProceedsResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x1f\n" +
	"\vproceeds_id\x18\x02 \x01(\fR\n" +
	"proceedsId\x12#\n" +
	"\ramount_common\x18\x03 \x01(\x03R\famountCommon\"\xe2\x01\n" +
	"\x12AuctionListingView\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\fR\tlistingId\x122\n" +
	"\x04item\x18\x02 \x01(\v2\x1e.thinhthan.v1.ItemInstanceViewR\x04item\x12!\n" +
	"\fprice_common\x18\x03 \x01(\x03R\vpriceCommon\x127\n" +
	"\x05state\x18\x04 \x01(\x0e2!.thinhthan.v1.AuctionListingStateR\x05state\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"\xd3\x01\n" +
	"\x16AuctionEscrowAssetView\x12&\n" +
	"\x0fescrow_asset_id\x18\x01 \x01(\fR\rescrowAssetId\x122\n" +
	"\x04item\x18\x02 \x01(\v2\x1e.thinhthan.v1.ItemInstanceViewR\x04item\x129\n" +
	"\x06reason\x18\x03 \x01(\x0e2!.thinhthan.v1.AuctionEscrowReasonR\x06reason\x12\"\n" +
	"\rauto_claim_at\x18\x04 \x01(\x03R\vautoClaimAt\"\x95\x01\n" +
	"\x13AuctionProceedsView\x12\x1f\n" +
	"\vproceeds_id\x18\x01 \x01(\fR\n" +
	"proceedsId\x12#\n" +
	"\ramount_common\x18\x02 \x01(\x03R\famountCommon\x128\n" +
	"\x05state\x18\x03 \x01(\x0e2\".thinhthan.v1.AuctionProceedsStateR\x05state\"\xdb\x01\n" +
	"\x11S2CAuctionMyState\x12<\n" +
	"\blistings\x18\x01 \x03(\v2 .thinhthan.v1.AuctionListingViewR\blistings\x12I\n" +
	"\rescrow_assets\x18\x02 \x03(\v2$.thinhthan.v1.AuctionEscrowAssetViewR\fescrowAssets\x12=\n" +
	"\bproceeds\x18\x03 \x03(\v2!.thinhthan.v1.AuctionProceedsViewR\bproceeds*\xa1\x02\n" +
	"\x11TradeCancelReason\x12#\n" +
	"\x1fTRADE_CANCEL_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTRADE_CANCEL_REASON_DECLINED\x10\x01\x12!\n" +
	"\x1dTRADE_CANCEL_REASON_CANCELLED\x10\x02\x12\x1f\n" +
	"\x1bTRADE_CANCEL_REASON_EXPIRED\x10\x03\x12(\n" +
	"$TRADE_CANCEL_REASON_INACTIVE_TIMEOUT\x10\x04\x12,\n" +
	"(TRADE_CANCEL_REASON_PARTNER_DISCONNECTED\x10\x05\x12)\n" +
	"%TRADE_CANCEL_REASON_VALIDATION_FAILED\x10\x06*\x90\x01\n" +
	"\x0fTradeOfferState\x12!\n" +
	"\x1dTRADE_OFFER_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRADE_OFFER_STATE_OPEN\x10\x01\x12\x1c\n" +
	"\x18TRADE_OFFER_STATE_LOCKED\x10\x02\x12 \n" +
	"\x1cTRADE_OFFER_STATE_COMMITTING\x10\x03*}\n" +
	"\vAuctionSort\x12\x1c\n" +
	"\x18AUCTION_SORT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AUCTION_SORT_PRICE_ASC\x10\x01\x12\x1b\n" +
	"\x17AUCTION_SORT_PRICE_DESC\x10\x02\x12\x17\n" +
	"\x13AUCTION_SORT_NEWEST\x10\x03*\xea\x01\n" +
	"\x13AuctionListingState\x12%\n" +
	"!AUCTION_LISTING_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAUCTION_LISTING_STATE_ACTIVE\x10\x01\x12\"\n" +
	"\x1eAUCTION_LISTING_STATE_SETTLING\x10\x02\x12\x1e\n" +
	"\x1aAUCTION_LISTING_STATE_SOLD\x10\x03\x12#\n" +
	"\x1fAUCTION_LISTING_STATE_CANCELLED\x10\x04\x12!\n" +
	"\x1dAUCTION_LISTING_STATE_EXPIRED\x10\x05*\x84\x01\n" +
	"\x13AuctionEscrowReason\x12%\n" +
	"!AUCTION_ESCROW_REASON_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fAUCTION_ESCROW_REASON_CANCELLED\x10\x01\x12!\n" +
	"\x1dAUCTION_ESCROW_REASON_EXPIRED\x10\x02*\x86\x01\n" +
	"\x14AuctionProceedsState\x12&\n" +
	"\"AUCTION_PROCEEDS_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eAUCTION_PROCEEDS_STATE_PENDING\x10\x01\x12\"\n" +
	"\x1eAUCTION_PROCEEDS_STATE_CLAIMED\x10\x02BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_market_proto_rawDescOnce sync.Once
	file_thinhthan_v1_market_proto_rawDescData []byte
)

func file_thinhthan_v1_market_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_market_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_market_proto_rawDesc), len(file_thinhthan_v1_market_proto_rawDesc)))
	})
	return file_thinhthan_v1_market_proto_rawDescData
}

var file_thinhthan_v1_market_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_thinhthan_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_thinhthan_v1_market_proto_goTypes = []any{
	(TradeCancelReason)(0),           // 0: thinhthan.v1.TradeCancelReason
	(TradeOfferState)(0),             // 1: thinhthan.v1.TradeOfferState
	(AuctionSort)(0),                 // 2: thinhthan.v1.AuctionSort
	(AuctionListingState)(0),         // 3: thinhthan.v1.AuctionListingState
	(AuctionEscrowReason)(0),         // 4: thinhthan.v1.AuctionEscrowReason
	(AuctionProceedsState)(0),        // 5: thinhthan.v1.AuctionProceedsState
	(*C2STradeInvite)(nil),           // 6: thinhthan.v1.C2STradeInvite
	(*S2CTradeInvite)(nil),           // 7: thinhthan.v1.S2CTradeInvite
	(*C2STradeAccept)(nil),           // 8: thinhthan.v1.C2STradeAccept
	(*C2STradeCancel)(nil),           // 9: thinhthan.v1.C2STradeCancel
	(*S2CTradeCancelled)(nil),        // 10: thinhthan.v1.S2CTradeCancelled
	(*TradeOfferItem)(nil),           // 11: thinhthan.v1.TradeOfferItem
	(*C2STradeOfferUpdate)(nil),      // 12: thinhthan.v1.C2STradeOfferUpdate
	(*TradeSide)(nil),                // 13: thinhthan.v1.TradeSide
	(*S2CTradeOfferState)(nil),       // 14: thinhthan.v1.S2CTradeOfferState
	(*C2STradeConfirm)(nil),          // 15: thinhthan.v1.C2STradeConfirm
	(*C2STradeFinalise)(nil),         // 16: thinhthan.v1.C2STradeFinalise
	(*S2CTradeResult)(nil),           // 17: thinhthan.v1.S2CTradeResult
	(*S2CTradeRequestResult)(nil),    // 18: thinhthan.v1.S2CTradeRequestResult
	(*C2SAuctionList)(nil),           // 19: thinhthan.v1.C2SAuctionList
	(*S2CAuctionListResult)(nil),     // 20: thinhthan.v1.S2CAuctionListResult
	(*C2SAuctionBuy)(nil),            // 21: thinhthan.v1.C2SAuctionBuy
	(*S2CAuctionBuyResult)(nil),      // 22: thinhthan.v1.S2CAuctionBuyResult
	(*C2SAuctionCancelListing)(nil),  // 23: thinhthan.v1.C2SAuctionCancelListing
	(*S2CAuctionCancelResult)(nil),   // 24: thinhthan.v1.S2CAuctionCancelResult
	(*S2CAuctionSold)(nil),           // 25: thinhthan.v1.S2CAuctionSold
	(*C2SAuctionSearch)(nil),         // 26: thinhthan.v1.C2SAuctionSearch
	(*AuctionSearchRow)(nil),         // 27: thinhthan.v1.AuctionSearchRow
	(*S2CAuctionSearchResult)(nil),   // 28: thinhthan.v1.S2CAuctionSearchResult
	(*C2SAuctionReclaim)(nil),        // 29: thinhthan.v1.C2SAuctionReclaim
	(*S2CAuctionReclaimResult)(nil),  // 30: thinhthan.v1.S2CAuctionReclaimResult
	(*C2SAuctionProceedsClaim)(nil),  // 31: thinhthan.v1.C2SAuctionProceedsClaim
	(*S2CAuctionProceedsResult)(nil), // 32: thinhthan.v1.S2CAuctionProceedsResult
	(*AuctionListingView)(nil),       // 33: thinhthan.v1.AuctionListingView
	(*AuctionEscrowAssetView)(nil),   // 34: thinhthan.v1.AuctionEscrowAssetView
	(*AuctionProceedsView)(nil),      // 35: thinhthan.v1.AuctionProceedsView
	(*S2CAuctionMyState)(nil),        // 36: thinhthan.v1.S2CAuctionMyState
	(ErrorCode)(0),                   // 37: thinhthan.v1.ErrorCode
	(*ItemInstanceView)(nil),         // 38: thinhthan.v1.ItemInstanceView
	(*OperationResult)(nil),          // 39: thinhthan.v1.OperationResult
	(*ItemGrant)(nil),                // 40: thinhthan.v1.ItemGrant
}
var file_thinhthan_v1_market_proto_depIdxs = []int32{
	0,  // 0: thinhthan.v1.S2CTradeCancelled.reason:type_name -> thinhthan.v1.TradeCancelReason
	37, // 1: thinhthan.v1.S2CTradeCancelled.error_code:type_name -> thinhthan.v1.ErrorCode
	11, // 2: thinhthan.v1.C2STradeOfferUpdate.items:type_name -> thinhthan.v1.TradeOfferItem
	38, // 3: thinhthan.v1.TradeSide.items:type_name -> thinhthan.v1.ItemInstanceView
	1,  // 4: thinhthan.v1.S2CTradeOfferState.state:type_name -> thinhthan.v1.TradeOfferState
	13, // 5: thinhthan.v1.S2CTradeOfferState.sides:type_name -> thinhthan.v1.TradeSide
	39, // 6: thinhthan.v1.S2CTradeResult.result:type_name -> thinhthan.v1.OperationResult
	40, // 7: thinhthan.v1.S2CTradeResult.received:type_name -> thinhthan.v1.ItemGrant
	39, // 8: thinhthan.v1.S2CTradeRequestResult.result:type_name -> thinhthan.v1.OperationResult
	39, // 9: thinhthan.v1.S2CAuctionListResult.result:type_name -> thinhthan.v1.OperationResult
	39, // 10: thinhthan.v1.S2CAuctionBuyResult.result:type_name -> thinhthan.v1.OperationResult
	38, // 11: thinhthan.v1.S2CAuctionBuyResult.received:type_name -> thinhthan.v1.ItemInstanceView
	39, // 12: thinhthan.v1.S2CAuctionCancelResult.result:type_name -> thinhthan.v1.OperationResult
	2,  // 13: thinhthan.v1.C2SAuctionSearch.sort:type_name -> thinhthan.v1.AuctionSort
	38, // 14: thinhthan.v1.AuctionSearchRow.item:type_name -> thinhthan.v1.ItemInstanceView
	39, // 15: thinhthan.v1.S2CAuctionSearchResult.result:type_name -> thinhthan.v1.OperationResult
	27, // 16: thinhthan.v1.S2CAuctionSearchResult.rows:type_name -> thinhthan.v1.AuctionSearchRow
	39, // 17: thinhthan.v1.S2CAuctionReclaimResult.result:type_name -> thinhthan.v1.OperationResult
	38, // 18: thinhthan.v1.S2CAuctionReclaimResult.received:type_name -> thinhthan.v1.ItemInstanceView
	39, // 19: thinhthan.v1.S2CAuctionProceedsResult.result:type_name -> thinhthan.v1.OperationResult
	38, // 20: thinhthan.v1.AuctionListingView.item:type_name -> thinhthan.v1.ItemInstanceView
	3,  // 21: thinhthan.v1.AuctionListingView.state:type_name -> thinhthan.v1.AuctionListingState
	38, // 22: thinhthan.v1.AuctionEscrowAssetView.item:type_name -> thinhthan.v1.ItemInstanceView
	4,  // 23: thinhthan.v1.AuctionEscrowAssetView.reason:type_name -> thinhthan.v1.AuctionEscrowReason
	5,  // 24: thinhthan.v1.AuctionProceedsView.state:type_name -> thinhthan.v1.AuctionProceedsState
	33, // 25: thinhthan.v1.S2CAuctionMyState.listings:type_name -> thinhthan.v1.AuctionListingView
	34, // 26: thinhthan.v1.S2CAuctionMyState.escrow_assets:type_name -> thinhthan.v1.AuctionEscrowAssetView
	35, // 27: thinhthan.v1.S2CAuctionMyState.proceeds:type_name -> thinhthan.v1.AuctionProceedsView
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_market_proto_init() }
func file_thinhthan_v1_market_proto_init() {
	if File_thinhthan_v1_market_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	file_thinhthan_v1_durable_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_market_proto_rawDesc), len(file_thinhthan_v1_market_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_market_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_market_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_market_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_market_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_market_proto = out.File
	file_thinhthan_v1_market_proto_goTypes = nil
	file_thinhthan_v1_market_proto_depIdxs = nil
}
