// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/movement.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractKind int32

const (
	InteractKind_INTERACT_KIND_UNSPECIFIED  InteractKind = 0
	InteractKind_INTERACT_KIND_TALK         InteractKind = 1
	InteractKind_INTERACT_KIND_PICKUP       InteractKind = 2
	InteractKind_INTERACT_KIND_CHEST        InteractKind = 3
	InteractKind_INTERACT_KIND_CAST         InteractKind = 4
	InteractKind_INTERACT_KIND_HOOK         InteractKind = 5
	InteractKind_INTERACT_KIND_KINDLE       InteractKind = 6
	InteractKind_INTERACT_KIND_COOK         InteractKind = 7
	InteractKind_INTERACT_KIND_BONFIRE_REST InteractKind = 8
	InteractKind_INTERACT_KIND_QUEST_OBJECT InteractKind = 9
	InteractKind_INTERACT_KIND_NPC_SERVICE  InteractKind = 10
	InteractKind_INTERACT_KIND_PORTAL       InteractKind = 11
)

// Enum value maps for InteractKind.
var (
	InteractKind_name = map[int32]string{
		0:  "INTERACT_KIND_UNSPECIFIED",
		1:  "INTERACT_KIND_TALK",
		2:  "INTERACT_KIND_PICKUP",
		3:  "INTERACT_KIND_CHEST",
		4:  "INTERACT_KIND_CAST",
		5:  "INTERACT_KIND_HOOK",
		6:  "INTERACT_KIND_KINDLE",
		7:  "INTERACT_KIND_COOK",
		8:  "INTERACT_KIND_BONFIRE_REST",
		9:  "INTERACT_KIND_QUEST_OBJECT",
		10: "INTERACT_KIND_NPC_SERVICE",
		11: "INTERACT_KIND_PORTAL",
	}
	InteractKind_value = map[string]int32{
		"INTERACT_KIND_UNSPECIFIED":  0,
		"INTERACT_KIND_TALK":         1,
		"INTERACT_KIND_PICKUP":       2,
		"INTERACT_KIND_CHEST":        3,
		"INTERACT_KIND_CAST":         4,
		"INTERACT_KIND_HOOK":         5,
		"INTERACT_KIND_KINDLE":       6,
		"INTERACT_KIND_COOK":         7,
		"INTERACT_KIND_BONFIRE_REST": 8,
		"INTERACT_KIND_QUEST_OBJECT": 9,
		"INTERACT_KIND_NPC_SERVICE":  10,
		"INTERACT_KIND_PORTAL":       11,
	}
)

func (x InteractKind) Enum() *InteractKind {
	p := new(InteractKind)
	*p = x
	return p
}

func (x InteractKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractKind) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[0].Descriptor()
}

func (InteractKind) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[0]
}

func (x InteractKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractKind.Descriptor instead.
func (InteractKind) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{0}
}

type TransferReason int32

const (
	TransferReason_TRANSFER_REASON_UNSPECIFIED    TransferReason = 0
	TransferReason_TRANSFER_REASON_PORTAL         TransferReason = 1
	TransferReason_TRANSFER_REASON_TRAVEL         TransferReason = 2
	TransferReason_TRANSFER_REASON_CHANNEL_SWITCH TransferReason = 3
	TransferReason_TRANSFER_REASON_DUNGEON_ENTER  TransferReason = 4
	TransferReason_TRANSFER_REASON_DUNGEON_LEAVE  TransferReason = 5
	TransferReason_TRANSFER_REASON_RESPAWN        TransferReason = 6
	TransferReason_TRANSFER_REASON_PVP            TransferReason = 7
	TransferReason_TRANSFER_REASON_RECONNECT      TransferReason = 8
	TransferReason_TRANSFER_REASON_FORCED         TransferReason = 9
)

// Enum value maps for TransferReason.
var (
	TransferReason_name = map[int32]string{
		0: "TRANSFER_REASON_UNSPECIFIED",
		1: "TRANSFER_REASON_PORTAL",
		2: "TRANSFER_REASON_TRAVEL",
		3: "TRANSFER_REASON_CHANNEL_SWITCH",
		4: "TRANSFER_REASON_DUNGEON_ENTER",
		5: "TRANSFER_REASON_DUNGEON_LEAVE",
		6: "TRANSFER_REASON_RESPAWN",
		7: "TRANSFER_REASON_PVP",
		8: "TRANSFER_REASON_RECONNECT",
		9: "TRANSFER_REASON_FORCED",
	}
	TransferReason_value = map[string]int32{
		"TRANSFER_REASON_UNSPECIFIED":    0,
		"TRANSFER_REASON_PORTAL":         1,
		"TRANSFER_REASON_TRAVEL":         2,
		"TRANSFER_REASON_CHANNEL_SWITCH": 3,
		"TRANSFER_REASON_DUNGEON_ENTER":  4,
		"TRANSFER_REASON_DUNGEON_LEAVE":  5,
		"TRANSFER_REASON_RESPAWN":        6,
		"TRANSFER_REASON_PVP":            7,
		"TRANSFER_REASON_RECONNECT":      8,
		"TRANSFER_REASON_FORCED":         9,
	}
)

func (x TransferReason) Enum() *TransferReason {
	p := new(TransferReason)
	*p = x
	return p
}

func (x TransferReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[1].Descriptor()
}

func (TransferReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[1]
}

func (x TransferReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferReason.Descriptor instead.
func (TransferReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{1}
}

type MovementCorrectionReason int32

const (
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_UNSPECIFIED  MovementCorrectionReason = 0
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE MovementCorrectionReason = 1
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_KNOCKBACK    MovementCorrectionReason = 2
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_PORTAL       MovementCorrectionReason = 3
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_RESPAWN      MovementCorrectionReason = 4
	MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_FORCED       MovementCorrectionReason = 5
)

// Enum value maps for MovementCorrectionReason.
var (
	MovementCorrectionReason_name = map[int32]string{
		0: "MOVEMENT_CORRECTION_REASON_UNSPECIFIED",
		1: "MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE",
		2: "MOVEMENT_CORRECTION_REASON_KNOCKBACK",
		3: "MOVEMENT_CORRECTION_REASON_PORTAL",
		4: "MOVEMENT_CORRECTION_REASON_RESPAWN",
		5: "MOVEMENT_CORRECTION_REASON_FORCED",
	}
	MovementCorrectionReason_value = map[string]int32{
		"MOVEMENT_CORRECTION_REASON_UNSPECIFIED":  0,
		"MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE": 1,
		"MOVEMENT_CORRECTION_REASON_KNOCKBACK":    2,
		"MOVEMENT_CORRECTION_REASON_PORTAL":       3,
		"MOVEMENT_CORRECTION_REASON_RESPAWN":      4,
		"MOVEMENT_CORRECTION_REASON_FORCED":       5,
	}
)

func (x MovementCorrectionReason) Enum() *MovementCorrectionReason {
	p := new(MovementCorrectionReason)
	*p = x
	return p
}

func (x MovementCorrectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementCorrectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[2].Descriptor()
}

func (MovementCorrectionReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[2]
}

func (x MovementCorrectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementCorrectionReason.Descriptor instead.
func (MovementCorrectionReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{2}
}

type MovementEdgeType int32

const (
	MovementEdgeType_MOVEMENT_EDGE_TYPE_UNSPECIFIED MovementEdgeType = 0
	MovementEdgeType_MOVEMENT_EDGE_TYPE_PRESS       MovementEdgeType = 1
	MovementEdgeType_MOVEMENT_EDGE_TYPE_RELEASE     MovementEdgeType = 2
	MovementEdgeType_MOVEMENT_EDGE_TYPE_FLIP        MovementEdgeType = 3
)

// Enum value maps for MovementEdgeType.
var (
	MovementEdgeType_name = map[int32]string{
		0: "MOVEMENT_EDGE_TYPE_UNSPECIFIED",
		1: "MOVEMENT_EDGE_TYPE_PRESS",
		2: "MOVEMENT_EDGE_TYPE_RELEASE",
		3: "MOVEMENT_EDGE_TYPE_FLIP",
	}
	MovementEdgeType_value = map[string]int32{
		"MOVEMENT_EDGE_TYPE_UNSPECIFIED": 0,
		"MOVEMENT_EDGE_TYPE_PRESS":       1,
		"MOVEMENT_EDGE_TYPE_RELEASE":     2,
		"MOVEMENT_EDGE_TYPE_FLIP":        3,
	}
)

func (x MovementEdgeType) Enum() *MovementEdgeType {
	p := new(MovementEdgeType)
	*p = x
	return p
}

func (x MovementEdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementEdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[3].Descriptor()
}

func (MovementEdgeType) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[3]
}

func (x MovementEdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementEdgeType.Descriptor instead.
func (MovementEdgeType) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{3}
}

type DungeonRunTag int32

const (
	DungeonRunTag_DUNGEON_RUN_TAG_UNSPECIFIED DungeonRunTag = 0
	DungeonRunTag_DUNGEON_RUN_TAG_NORMAL      DungeonRunTag = 1
	DungeonRunTag_DUNGEON_RUN_TAG_ENDGAME_L60 DungeonRunTag = 2
)

// Enum value maps for DungeonRunTag.
var (
	DungeonRunTag_name = map[int32]string{
		0: "DUNGEON_RUN_TAG_UNSPECIFIED",
		1: "DUNGEON_RUN_TAG_NORMAL",
		2: "DUNGEON_RUN_TAG_ENDGAME_L60",
	}
	DungeonRunTag_value = map[string]int32{
		"DUNGEON_RUN_TAG_UNSPECIFIED": 0,
		"DUNGEON_RUN_TAG_NORMAL":      1,
		"DUNGEON_RUN_TAG_ENDGAME_L60": 2,
	}
)

func (x DungeonRunTag) Enum() *DungeonRunTag {
	p := new(DungeonRunTag)
	*p = x
	return p
}

func (x DungeonRunTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonRunTag) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[4].Descriptor()
}

func (DungeonRunTag) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[4]
}

func (x DungeonRunTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonRunTag.Descriptor instead.
func (DungeonRunTag) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{4}
}

type DungeonEntryResponse int32

const (
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_UNSPECIFIED DungeonEntryResponse = 0
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_PENDING     DungeonEntryResponse = 1
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_ACCEPTED    DungeonEntryResponse = 2
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_DECLINED    DungeonEntryResponse = 3
	DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_INELIGIBLE  DungeonEntryResponse = 4
)

// Enum value maps for DungeonEntryResponse.
var (
	DungeonEntryResponse_name = map[int32]string{
		0: "DUNGEON_ENTRY_RESPONSE_UNSPECIFIED",
		1: "DUNGEON_ENTRY_RESPONSE_PENDING",
		2: "DUNGEON_ENTRY_RESPONSE_ACCEPTED",
		3: "DUNGEON_ENTRY_RESPONSE_DECLINED",
		4: "DUNGEON_ENTRY_RESPONSE_INELIGIBLE",
	}
	DungeonEntryResponse_value = map[string]int32{
		"DUNGEON_ENTRY_RESPONSE_UNSPECIFIED": 0,
		"DUNGEON_ENTRY_RESPONSE_PENDING":     1,
		"DUNGEON_ENTRY_RESPONSE_ACCEPTED":    2,
		"DUNGEON_ENTRY_RESPONSE_DECLINED":    3,
		"DUNGEON_ENTRY_RESPONSE_INELIGIBLE":  4,
	}
)

func (x DungeonEntryResponse) Enum() *DungeonEntryResponse {
	p := new(DungeonEntryResponse)
	*p = x
	return p
}

func (x DungeonEntryResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonEntryResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[5].Descriptor()
}

func (DungeonEntryResponse) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[5]
}

func (x DungeonEntryResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonEntryResponse.Descriptor instead.
func (DungeonEntryResponse) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{5}
}

type DungeonEntryOutcome int32

const (
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_UNSPECIFIED DungeonEntryOutcome = 0
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_PENDING     DungeonEntryOutcome = 1
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_CREATED     DungeonEntryOutcome = 2
	DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_CANCELLED   DungeonEntryOutcome = 3
)

// Enum value maps for DungeonEntryOutcome.
var (
	DungeonEntryOutcome_name = map[int32]string{
		0: "DUNGEON_ENTRY_OUTCOME_UNSPECIFIED",
		1: "DUNGEON_ENTRY_OUTCOME_PENDING",
		2: "DUNGEON_ENTRY_OUTCOME_CREATED",
		3: "DUNGEON_ENTRY_OUTCOME_CANCELLED",
	}
	DungeonEntryOutcome_value = map[string]int32{
		"DUNGEON_ENTRY_OUTCOME_UNSPECIFIED": 0,
		"DUNGEON_ENTRY_OUTCOME_PENDING":     1,
		"DUNGEON_ENTRY_OUTCOME_CREATED":     2,
		"DUNGEON_ENTRY_OUTCOME_CANCELLED":   3,
	}
)

func (x DungeonEntryOutcome) Enum() *DungeonEntryOutcome {
	p := new(DungeonEntryOutcome)
	*p = x
	return p
}

func (x DungeonEntryOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonEntryOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[6].Descriptor()
}

func (DungeonEntryOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[6]
}

func (x DungeonEntryOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonEntryOutcome.Descriptor instead.
func (DungeonEntryOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{6}
}

type DungeonEntryDecision int32

const (
	DungeonEntryDecision_DUNGEON_ENTRY_DECISION_UNSPECIFIED DungeonEntryDecision = 0
	DungeonEntryDecision_DUNGEON_ENTRY_DECISION_ACCEPT      DungeonEntryDecision = 1
	DungeonEntryDecision_DUNGEON_ENTRY_DECISION_DECLINE     DungeonEntryDecision = 2
)

// Enum value maps for DungeonEntryDecision.
var (
	DungeonEntryDecision_name = map[int32]string{
		0: "DUNGEON_ENTRY_DECISION_UNSPECIFIED",
		1: "DUNGEON_ENTRY_DECISION_ACCEPT",
		2: "DUNGEON_ENTRY_DECISION_DECLINE",
	}
	DungeonEntryDecision_value = map[string]int32{
		"DUNGEON_ENTRY_DECISION_UNSPECIFIED": 0,
		"DUNGEON_ENTRY_DECISION_ACCEPT":      1,
		"DUNGEON_ENTRY_DECISION_DECLINE":     2,
	}
)

func (x DungeonEntryDecision) Enum() *DungeonEntryDecision {
	p := new(DungeonEntryDecision)
	*p = x
	return p
}

func (x DungeonEntryDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonEntryDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[7].Descriptor()
}

func (DungeonEntryDecision) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[7]
}

func (x DungeonEntryDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonEntryDecision.Descriptor instead.
func (DungeonEntryDecision) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{7}
}

type DungeonLeaveMode int32

const (
	DungeonLeaveMode_DUNGEON_LEAVE_MODE_UNSPECIFIED DungeonLeaveMode = 0
	DungeonLeaveMode_DUNGEON_LEAVE_MODE_EXIT        DungeonLeaveMode = 1
	DungeonLeaveMode_DUNGEON_LEAVE_MODE_ABANDON     DungeonLeaveMode = 2
)

// Enum value maps for DungeonLeaveMode.
var (
	DungeonLeaveMode_name = map[int32]string{
		0: "DUNGEON_LEAVE_MODE_UNSPECIFIED",
		1: "DUNGEON_LEAVE_MODE_EXIT",
		2: "DUNGEON_LEAVE_MODE_ABANDON",
	}
	DungeonLeaveMode_value = map[string]int32{
		"DUNGEON_LEAVE_MODE_UNSPECIFIED": 0,
		"DUNGEON_LEAVE_MODE_EXIT":        1,
		"DUNGEON_LEAVE_MODE_ABANDON":     2,
	}
)

func (x DungeonLeaveMode) Enum() *DungeonLeaveMode {
	p := new(DungeonLeaveMode)
	*p = x
	return p
}

func (x DungeonLeaveMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonLeaveMode) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_movement_proto_enumTypes[8].Descriptor()
}

func (DungeonLeaveMode) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_movement_proto_enumTypes[8]
}

func (x DungeonLeaveMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonLeaveMode.Descriptor instead.
func (DungeonLeaveMode) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{8}
}

type DungeonEntryMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Response      DungeonEntryResponse   `protobuf:"varint,3,opt,name=response,proto3,enum=thinhthan.v1.DungeonEntryResponse" json:"response,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonEntryMember) Reset() {
	*x = DungeonEntryMember{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonEntryMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonEntryMember) ProtoMessage() {}

func (x *DungeonEntryMember) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonEntryMember.ProtoReflect.Descriptor instead.
func (*DungeonEntryMember) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{0}
}

func (x *DungeonEntryMember) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *DungeonEntryMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DungeonEntryMember) GetResponse() DungeonEntryResponse {
	if x != nil {
		return x.Response
	}
	return DungeonEntryResponse_DUNGEON_ENTRY_RESPONSE_UNSPECIFIED
}

func (x *DungeonEntryMember) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// ID 100
type C2SInputState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputFlags    uint32                 `protobuf:"varint,1,opt,name=input_flags,json=inputFlags,proto3" json:"input_flags,omitempty"`         // bitmask
	ClientMonoMs  uint64                 `protobuf:"varint,2,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"` // advisory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SInputState) Reset() {
	*x = C2SInputState{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SInputState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SInputState) ProtoMessage() {}

func (x *C2SInputState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SInputState.ProtoReflect.Descriptor instead.
func (*C2SInputState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{1}
}

func (x *C2SInputState) GetInputFlags() uint32 {
	if x != nil {
		return x.InputFlags
	}
	return 0
}

func (x *C2SInputState) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// ID 101
type C2SJump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs  uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SJump) Reset() {
	*x = C2SJump{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SJump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SJump) ProtoMessage() {}

func (x *C2SJump) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SJump.ProtoReflect.Descriptor instead.
func (*C2SJump) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{2}
}

func (x *C2SJump) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// ID 102
type C2SDropThrough struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs  uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDropThrough) Reset() {
	*x = C2SDropThrough{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDropThrough) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDropThrough) ProtoMessage() {}

func (x *C2SDropThrough) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDropThrough.ProtoReflect.Descriptor instead.
func (*C2SDropThrough) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{3}
}

func (x *C2SDropThrough) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// ID 103
type C2SInteract struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	InteractKind                InteractKind           `protobuf:"varint,1,opt,name=interact_kind,json=interactKind,proto3,enum=thinhthan.v1.InteractKind" json:"interact_kind,omitempty"`
	TargetId                    string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	OperationId                 []byte                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	RecipeId                    *string                `protobuf:"bytes,4,opt,name=recipe_id,json=recipeId,proto3,oneof" json:"recipe_id,omitempty"`
	PublicBossSpawnGenerationId []byte                 `protobuf:"bytes,5,opt,name=public_boss_spawn_generation_id,json=publicBossSpawnGenerationId,proto3,oneof" json:"public_boss_spawn_generation_id,omitempty"` // UUID, 16 bytes
	ServiceId                   *string                `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
	ServiceParam                *string                `protobuf:"bytes,7,opt,name=service_param,json=serviceParam,proto3,oneof" json:"service_param,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *C2SInteract) Reset() {
	*x = C2SInteract{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SInteract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SInteract) ProtoMessage() {}

func (x *C2SInteract) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SInteract.ProtoReflect.Descriptor instead.
func (*C2SInteract) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{4}
}

func (x *C2SInteract) GetInteractKind() InteractKind {
	if x != nil {
		return x.InteractKind
	}
	return InteractKind_INTERACT_KIND_UNSPECIFIED
}

func (x *C2SInteract) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *C2SInteract) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SInteract) GetRecipeId() string {
	if x != nil && x.RecipeId != nil {
		return *x.RecipeId
	}
	return ""
}

func (x *C2SInteract) GetPublicBossSpawnGenerationId() []byte {
	if x != nil {
		return x.PublicBossSpawnGenerationId
	}
	return nil
}

func (x *C2SInteract) GetServiceId() string {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return ""
}

func (x *C2SInteract) GetServiceParam() string {
	if x != nil && x.ServiceParam != nil {
		return *x.ServiceParam
	}
	return ""
}

// ID 104
type C2SPortalUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	PortalId      string                 `protobuf:"bytes,2,opt,name=portal_id,json=portalId,proto3" json:"portal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPortalUse) Reset() {
	*x = C2SPortalUse{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPortalUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPortalUse) ProtoMessage() {}

func (x *C2SPortalUse) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPortalUse.ProtoReflect.Descriptor instead.
func (*C2SPortalUse) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{5}
}

func (x *C2SPortalUse) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SPortalUse) GetPortalId() string {
	if x != nil {
		return x.PortalId
	}
	return ""
}

// ID 105
type S2CTransferPrepare struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // UUID, 16 bytes
	Reason          TransferReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=thinhthan.v1.TransferReason" json:"reason,omitempty"`
	MapId           string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ChannelIndex    uint32                 `protobuf:"varint,4,opt,name=channel_index,json=channelIndex,proto3" json:"channel_index,omitempty"`
	InstanceId      []byte                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // UUID, 16 bytes
	ContentRevision string                 `protobuf:"bytes,6,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	ReadyDeadlineMs uint32                 `protobuf:"varint,7,opt,name=ready_deadline_ms,json=readyDeadlineMs,proto3" json:"ready_deadline_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2CTransferPrepare) Reset() {
	*x = S2CTransferPrepare{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CTransferPrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTransferPrepare) ProtoMessage() {}

func (x *S2CTransferPrepare) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTransferPrepare.ProtoReflect.Descriptor instead.
func (*S2CTransferPrepare) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{6}
}

func (x *S2CTransferPrepare) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *S2CTransferPrepare) GetReason() TransferReason {
	if x != nil {
		return x.Reason
	}
	return TransferReason_TRANSFER_REASON_UNSPECIFIED
}

func (x *S2CTransferPrepare) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *S2CTransferPrepare) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

func (x *S2CTransferPrepare) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *S2CTransferPrepare) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *S2CTransferPrepare) GetReadyDeadlineMs() uint32 {
	if x != nil {
		return x.ReadyDeadlineMs
	}
	return 0
}

// ID 106
type C2SPresentationReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPresentationReady) Reset() {
	*x = C2SPresentationReady{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPresentationReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPresentationReady) ProtoMessage() {}

func (x *C2SPresentationReady) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPresentationReady.ProtoReflect.Descriptor instead.
func (*C2SPresentationReady) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{7}
}

func (x *C2SPresentationReady) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

// ID 107
type S2CMovementCorrection struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	LastProcessedClientSeq uint64                   `protobuf:"varint,1,opt,name=last_processed_client_seq,json=lastProcessedClientSeq,proto3" json:"last_processed_client_seq,omitempty"`
	ServerTick             uint64                   `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	Checkpoint             *MovementCheckpoint      `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Reason                 MovementCorrectionReason `protobuf:"varint,4,opt,name=reason,proto3,enum=thinhthan.v1.MovementCorrectionReason" json:"reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *S2CMovementCorrection) Reset() {
	*x = S2CMovementCorrection{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CMovementCorrection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMovementCorrection) ProtoMessage() {}

func (x *S2CMovementCorrection) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMovementCorrection.ProtoReflect.Descriptor instead.
func (*S2CMovementCorrection) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{8}
}

func (x *S2CMovementCorrection) GetLastProcessedClientSeq() uint64 {
	if x != nil {
		return x.LastProcessedClientSeq
	}
	return 0
}

func (x *S2CMovementCorrection) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2CMovementCorrection) GetCheckpoint() *MovementCheckpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *S2CMovementCorrection) GetReason() MovementCorrectionReason {
	if x != nil {
		return x.Reason
	}
	return MovementCorrectionReason_MOVEMENT_CORRECTION_REASON_UNSPECIFIED
}

// ID 108
type C2SMovementEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeType      MovementEdgeType       `protobuf:"varint,1,opt,name=edge_type,json=edgeType,proto3,enum=thinhthan.v1.MovementEdgeType" json:"edge_type,omitempty"`
	Direction     Facing                 `protobuf:"varint,2,opt,name=direction,proto3,enum=thinhthan.v1.Facing" json:"direction,omitempty"`
	ClientMonoMs  uint64                 `protobuf:"varint,3,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMovementEdge) Reset() {
	*x = C2SMovementEdge{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMovementEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMovementEdge) ProtoMessage() {}

func (x *C2SMovementEdge) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMovementEdge.ProtoReflect.Descriptor instead.
func (*C2SMovementEdge) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{9}
}

func (x *C2SMovementEdge) GetEdgeType() MovementEdgeType {
	if x != nil {
		return x.EdgeType
	}
	return MovementEdgeType_MOVEMENT_EDGE_TYPE_UNSPECIFIED
}

func (x *C2SMovementEdge) GetDirection() Facing {
	if x != nil {
		return x.Direction
	}
	return Facing_FACING_UNSPECIFIED
}

func (x *C2SMovementEdge) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

// ID 109
type C2SChannelSwitch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TargetChannelIndex uint32                 `protobuf:"varint,1,opt,name=target_channel_index,json=targetChannelIndex,proto3" json:"target_channel_index,omitempty"`
	OperationId        []byte                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *C2SChannelSwitch) Reset() {
	*x = C2SChannelSwitch{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SChannelSwitch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChannelSwitch) ProtoMessage() {}

func (x *C2SChannelSwitch) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChannelSwitch.ProtoReflect.Descriptor instead.
func (*C2SChannelSwitch) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{10}
}

func (x *C2SChannelSwitch) GetTargetChannelIndex() uint32 {
	if x != nil {
		return x.TargetChannelIndex
	}
	return 0
}

func (x *C2SChannelSwitch) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

// ID 110
type S2CChannelSwitchResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Result             *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	TargetChannelIndex uint32                 `protobuf:"varint,2,opt,name=target_channel_index,json=targetChannelIndex,proto3" json:"target_channel_index,omitempty"`
	RetryAfterMs       uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2CChannelSwitchResult) Reset() {
	*x = S2CChannelSwitchResult{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CChannelSwitchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChannelSwitchResult) ProtoMessage() {}

func (x *S2CChannelSwitchResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChannelSwitchResult.ProtoReflect.Descriptor instead.
func (*S2CChannelSwitchResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{11}
}

func (x *S2CChannelSwitchResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CChannelSwitchResult) GetTargetChannelIndex() uint32 {
	if x != nil {
		return x.TargetChannelIndex
	}
	return 0
}

func (x *S2CChannelSwitchResult) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// ID 111
type C2SDungeonEnterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	DungeonId     string                 `protobuf:"bytes,2,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	RunTag        DungeonRunTag          `protobuf:"varint,3,opt,name=run_tag,json=runTag,proto3,enum=thinhthan.v1.DungeonRunTag" json:"run_tag,omitempty"`
	EntranceId    string                 `protobuf:"bytes,4,opt,name=entrance_id,json=entranceId,proto3" json:"entrance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDungeonEnterRequest) Reset() {
	*x = C2SDungeonEnterRequest{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDungeonEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDungeonEnterRequest) ProtoMessage() {}

func (x *C2SDungeonEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDungeonEnterRequest.ProtoReflect.Descriptor instead.
func (*C2SDungeonEnterRequest) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{12}
}

func (x *C2SDungeonEnterRequest) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDungeonEnterRequest) GetDungeonId() string {
	if x != nil {
		return x.DungeonId
	}
	return ""
}

func (x *C2SDungeonEnterRequest) GetRunTag() DungeonRunTag {
	if x != nil {
		return x.RunTag
	}
	return DungeonRunTag_DUNGEON_RUN_TAG_UNSPECIFIED
}

func (x *C2SDungeonEnterRequest) GetEntranceId() string {
	if x != nil {
		return x.EntranceId
	}
	return ""
}

// ID 112
type S2CDungeonEntryState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Result               *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                  // answers the recipient's own 111/113/117; empty otherwise
	EntryId              []byte                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"` // UUID, 16 bytes
	DungeonId            string                 `protobuf:"bytes,3,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	RunTag               DungeonRunTag          `protobuf:"varint,4,opt,name=run_tag,json=runTag,proto3,enum=thinhthan.v1.DungeonRunTag" json:"run_tag,omitempty"`
	RequesterCharacterId []byte                 `protobuf:"bytes,5,opt,name=requester_character_id,json=requesterCharacterId,proto3" json:"requester_character_id,omitempty"` // UUID, 16 bytes
	Members              []*DungeonEntryMember  `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	ExpiresInMs          uint32                 `protobuf:"varint,7,opt,name=expires_in_ms,json=expiresInMs,proto3" json:"expires_in_ms,omitempty"`
	Outcome              DungeonEntryOutcome    `protobuf:"varint,8,opt,name=outcome,proto3,enum=thinhthan.v1.DungeonEntryOutcome" json:"outcome,omitempty"`
	CancelReasonCode     ErrorCode              `protobuf:"varint,9,opt,name=cancel_reason_code,json=cancelReasonCode,proto3,enum=thinhthan.v1.ErrorCode" json:"cancel_reason_code,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *S2CDungeonEntryState) Reset() {
	*x = S2CDungeonEntryState{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CDungeonEntryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDungeonEntryState) ProtoMessage() {}

func (x *S2CDungeonEntryState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDungeonEntryState.ProtoReflect.Descriptor instead.
func (*S2CDungeonEntryState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{13}
}

func (x *S2CDungeonEntryState) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CDungeonEntryState) GetEntryId() []byte {
	if x != nil {
		return x.EntryId
	}
	return nil
}

func (x *S2CDungeonEntryState) GetDungeonId() string {
	if x != nil {
		return x.DungeonId
	}
	return ""
}

func (x *S2CDungeonEntryState) GetRunTag() DungeonRunTag {
	if x != nil {
		return x.RunTag
	}
	return DungeonRunTag_DUNGEON_RUN_TAG_UNSPECIFIED
}

func (x *S2CDungeonEntryState) GetRequesterCharacterId() []byte {
	if x != nil {
		return x.RequesterCharacterId
	}
	return nil
}

func (x *S2CDungeonEntryState) GetMembers() []*DungeonEntryMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *S2CDungeonEntryState) GetExpiresInMs() uint32 {
	if x != nil {
		return x.ExpiresInMs
	}
	return 0
}

func (x *S2CDungeonEntryState) GetOutcome() DungeonEntryOutcome {
	if x != nil {
		return x.Outcome
	}
	return DungeonEntryOutcome_DUNGEON_ENTRY_OUTCOME_UNSPECIFIED
}

func (x *S2CDungeonEntryState) GetCancelReasonCode() ErrorCode {
	if x != nil {
		return x.CancelReasonCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// ID 113
type C2SDungeonEntryRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	EntryId       []byte                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`             // UUID, 16 bytes
	Decision      DungeonEntryDecision   `protobuf:"varint,3,opt,name=decision,proto3,enum=thinhthan.v1.DungeonEntryDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDungeonEntryRespond) Reset() {
	*x = C2SDungeonEntryRespond{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDungeonEntryRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDungeonEntryRespond) ProtoMessage() {}

func (x *C2SDungeonEntryRespond) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDungeonEntryRespond.ProtoReflect.Descriptor instead.
func (*C2SDungeonEntryRespond) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{14}
}

func (x *C2SDungeonEntryRespond) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDungeonEntryRespond) GetEntryId() []byte {
	if x != nil {
		return x.EntryId
	}
	return nil
}

func (x *C2SDungeonEntryRespond) GetDecision() DungeonEntryDecision {
	if x != nil {
		return x.Decision
	}
	return DungeonEntryDecision_DUNGEON_ENTRY_DECISION_UNSPECIFIED
}

// ID 114
type C2SDungeonLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	Mode          DungeonLeaveMode       `protobuf:"varint,2,opt,name=mode,proto3,enum=thinhthan.v1.DungeonLeaveMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDungeonLeave) Reset() {
	*x = C2SDungeonLeave{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDungeonLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDungeonLeave) ProtoMessage() {}

func (x *C2SDungeonLeave) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDungeonLeave.ProtoReflect.Descriptor instead.
func (*C2SDungeonLeave) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{15}
}

func (x *C2SDungeonLeave) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDungeonLeave) GetMode() DungeonLeaveMode {
	if x != nil {
		return x.Mode
	}
	return DungeonLeaveMode_DUNGEON_LEAVE_MODE_UNSPECIFIED
}

// ID 115
type S2CDungeonLeaveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Mode          DungeonLeaveMode       `protobuf:"varint,2,opt,name=mode,proto3,enum=thinhthan.v1.DungeonLeaveMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CDungeonLeaveResult) Reset() {
	*x = S2CDungeonLeaveResult{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CDungeonLeaveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDungeonLeaveResult) ProtoMessage() {}

func (x *S2CDungeonLeaveResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDungeonLeaveResult.ProtoReflect.Descriptor instead.
func (*S2CDungeonLeaveResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{16}
}

func (x *S2CDungeonLeaveResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CDungeonLeaveResult) GetMode() DungeonLeaveMode {
	if x != nil {
		return x.Mode
	}
	return DungeonLeaveMode_DUNGEON_LEAVE_MODE_UNSPECIFIED
}

// ID 116
type S2CInteractResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	InteractKind  InteractKind           `protobuf:"varint,2,opt,name=interact_kind,json=interactKind,proto3,enum=thinhthan.v1.InteractKind" json:"interact_kind,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Granted       []*ItemQuantity        `protobuf:"bytes,4,rep,name=granted,proto3" json:"granted,omitempty"`
	CurrencyDelta []*CurrencyDelta       `protobuf:"bytes,5,rep,name=currency_delta,json=currencyDelta,proto3" json:"currency_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CInteractResult) Reset() {
	*x = S2CInteractResult{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CInteractResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CInteractResult) ProtoMessage() {}

func (x *S2CInteractResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CInteractResult.ProtoReflect.Descriptor instead.
func (*S2CInteractResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{17}
}

func (x *S2CInteractResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CInteractResult) GetInteractKind() InteractKind {
	if x != nil {
		return x.InteractKind
	}
	return InteractKind_INTERACT_KIND_UNSPECIFIED
}

func (x *S2CInteractResult) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *S2CInteractResult) GetGranted() []*ItemQuantity {
	if x != nil {
		return x.Granted
	}
	return nil
}

func (x *S2CInteractResult) GetCurrencyDelta() []*CurrencyDelta {
	if x != nil {
		return x.CurrencyDelta
	}
	return nil
}

// ID 117
type C2SDungeonEntryCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	EntryId       []byte                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`             // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDungeonEntryCancel) Reset() {
	*x = C2SDungeonEntryCancel{}
	mi := &file_thinhthan_v1_movement_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDungeonEntryCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDungeonEntryCancel) ProtoMessage() {}

func (x *C2SDungeonEntryCancel) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_movement_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDungeonEntryCancel.ProtoReflect.Descriptor instead.
func (*C2SDungeonEntryCancel) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_movement_proto_rawDescGZIP(), []int{18}
}

func (x *C2SDungeonEntryCancel) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDungeonEntryCancel) GetEntryId() []byte {
	if x != nil {
		return x.EntryId
	}
	return nil
}

var File_thinhthan_v1_movement_proto protoreflect.FileDescriptor

const file_thinhthan_v1_movement_proto_rawDesc = "" +
	"\n" +
	"\x1bthinhthan/v1/movement.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"\xd2\x01\n" +
	"\x12DungeonEntryMember\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12>\n" +
	"\bresponse\x18\x03 \x01(\x0e2\".thinhthan.v1.DungeonEntryResponseR\bresponse\x126\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"V\n" +
	"\rC2SInputState\x12\x1f\n" +
	"\vinput_flags\x18\x01 \x01(\rR\n" +
	"inputFlags\x12$\n" +
	"\x0eclient_mono_ms\x18\x02 \x01(\x04R\fclientMonoMs\"/\n" +
	"\aC2SJump\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\"6\n" +
	"\x0eC2SDropThrough\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\"\x9c\x03\n" +
	"\vC2SInteract\x12?\n" +
	"\rinteract_kind\x18\x01 \x01(\x0e2\x1a.thinhthan.v1.InteractKindR\finteractKind\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\fR\voperationId\x12 \n" +
	"\trecipe_id\x18\x04 \x01(\tH\x00R\brecipeId\x88\x01\x01\x12I\n" +
	"\x1fpublic_boss_spawn_generation_id\x18\x05 \x01(\fH\x01R\x1bpublicBossSpawnGenerationId\x88\x01\x01\x12\"\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tH\x02R\tserviceId\x88\x01\x01\x12(\n" +
	"\rservice_param\x18\a \x01(\tH\x03R\fserviceParam\x88\x01\x01B\f\n" +
	"\n" +
	"_recipe_idB\"\n" +
	" _public_boss_spawn_generation_idB\r\n" +
	"\v_service_idB\x10\n" +
	"\x0e_service_param\"N\n" +
	"\fC2SPortalUse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1b\n" +
	"\tportal_id\x18\x02 \x01(\tR\bportalId\"\x9f\x02\n" +
	"\x12S2CTransferPrepare\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x124\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1c.thinhthan.v1.TransferReasonR\x06reason\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12#\n" +
	"\rchannel_index\x18\x04 \x01(\rR\fchannelIndex\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\fR\n" +
	"instanceId\x12)\n" +
	"\x10content_revision\x18\x06 \x01(\tR\x0fcontentRevision\x12*\n" +
	"\x11ready_deadline_ms\x18\a \x01(\rR\x0freadyDeadlineMs\"7\n" +
	"\x14C2SPresentationReady\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\"\xf5\x01\n" +
	"\x15S2CMovementCorrection\x129\n" +
	"\x19last_processed_client_seq\x18\x01 \x01(\x04R\x16lastProcessedClientSeq\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12@\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\v2 .thinhthan.v1.MovementCheckpointR\n" +
	"checkpoint\x12>\n" +
	"\x06reason\x18\x04 \x01(\x0e2&.thinhthan.v1.MovementCorrectionReasonR\x06reason\"\xa8\x01\n" +
	"\x0fC2SMovementEdge\x12;\n" +
	"\tedge_type\x18\x01 \x01(\x0e2\x1e.thinhthan.v1.MovementEdgeTypeR\bedgeType\x122\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x14.thinhthan.v1.FacingR\tdirection\x12$\n" +
	"\x0eclient_mono_ms\x18\x03 \x01(\x04R\fclientMonoMs\"g\n" +
	"\x10C2SChannelSwitch\x120\n" +
	"\x14target_channel_index\x18\x01 \x01(\rR\x12targetChannelIndex\x12!\n" +
	"\foperation_id\x18\x02 \x01(\fR\voperationId\"\xa7\x01\n" +
	"\x16S2CChannelSwitchResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x120\n" +
	"\x14target_channel_index\x18\x02 \x01(\rR\x12targetChannelIndex\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\"\xb1\x01\n" +
	"\x16C2SDungeonEnterRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1d\n" +
	"\n" +
	"dungeon_id\x18\x02 \x01(\tR\tdungeonId\x124\n" +
	"\arun_tag\x18\x03 \x01(\x0e2\x1b.thinhthan.v1.DungeonRunTagR\x06runTag\x12\x1f\n" +
	"\ventrance_id\x18\x04 \x01(\tR\n" +
	"entranceId\"\xd7\x03\n" +
	"\x14S2CDungeonEntryState\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\fR\aentryId\x12\x1d\n" +
	"\n" +
	"dungeon_id\x18\x03 \x01(\tR\tdungeonId\x124\n" +
	"\arun_tag\x18\x04 \x01(\x0e2\x1b.thinhthan.v1.DungeonRunTagR\x06runTag\x124\n" +
	"\x16requester_character_id\x18\x05 \x01(\fR\x14requesterCharacterId\x12:\n" +
	"\amembers\x18\x06 \x03(\v2 .thinhthan.v1.DungeonEntryMemberR\amembers\x12\"\n" +
	"\rexpires_in_ms\x18\a \x01(\rR\vexpiresInMs\x12;\n" +
	"\aoutcome\x18\b \x01(\x0e2!.thinhthan.v1.DungeonEntryOutcomeR\aoutcome\x12E\n" +
	"\x12cancel_reason_code\x18\t \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\x10cancelReasonCode\"\x96\x01\n" +
	"\x16C2SDungeonEntryRespond\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\fR\aentryId\x12>\n" +
	"\bdecision\x18\x03 \x01(\x0e2\".thinhthan.v1.DungeonEntryDecisionR\bdecision\"h\n" +
	"\x0fC2SDungeonLeave\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x122\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1e.thinhthan.v1.DungeonLeaveModeR\x04mode\"\x82\x01\n" +
	"\x15S2CDungeonLeaveResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x122\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1e.thinhthan.v1.DungeonLeaveModeR\x04mode\"\xa2\x02\n" +
	"\x11S2CInteractResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12?\n" +
	"\rinteract_kind\x18\x02 \x01(\x0e2\x1a.thinhthan.v1.InteractKindR\finteractKind\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x124\n" +
	"\agranted\x18\x04 \x03(\v2\x1a.thinhthan.v1.ItemQuantityR\agranted\x12B\n" +
	"\x0ecurrency_delta\x18\x05 \x03(\v2\x1b.thinhthan.v1.CurrencyDeltaR\rcurrencyDelta\"U\n" +
	"\x15C2SDungeonEntryCancel\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\fR\aentryId*\xd3\x02\n" +
	"\fInteractKind\x12\x1d\n" +
	"\x19INTERACT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INTERACT_KIND_TALK\x10\x01\x12\x18\n" +
	"\x14INTERACT_KIND_PICKUP\x10\x02\x12\x17\n" +
	"\x13INTERACT_KIND_CHEST\x10\x03\x12\x16\n" +
	"\x12INTERACT_KIND_CAST\x10\x04\x12\x16\n" +
	"\x12INTERACT_KIND_HOOK\x10\x05\x12\x18\n" +
	"\x14INTERACT_KIND_KINDLE\x10\x06\x12\x16\n" +
	"\x12INTERACT_KIND_COOK\x10\a\x12\x1e\n" +
	"\x1aINTERACT_KIND_BONFIRE_REST\x10\b\x12\x1e\n" +
	"\x1aINTERACT_KIND_QUEST_OBJECT\x10\t\x12\x1d\n" +
	"\x19INTERACT_KIND_NPC_SERVICE\x10\n" +
	"\x12\x18\n" +
	"\x14INTERACT_KIND_PORTAL\x10\v*\xc4\x02\n" +
	"\x0eTransferReason\x12\x1f\n" +
	"\x1bTRANSFER_REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSFER_REASON_PORTAL\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_REASON_TRAVEL\x10\x02\x12\"\n" +
	"\x1eTRANSFER_REASON_CHANNEL_SWITCH\x10\x03\x12!\n" +
	"\x1dTRANSFER_REASON_DUNGEON_ENTER\x10\x04\x12!\n" +
	"\x1dTRANSFER_REASON_DUNGEON_LEAVE\x10\x05\x12\x1b\n" +
	"\x17TRANSFER_REASON_RESPAWN\x10\x06\x12\x17\n" +
	"\x13TRANSFER_REASON_PVP\x10\a\x12\x1d\n" +
	"\x19TRANSFER_REASON_RECONNECT\x10\b\x12\x1a\n" +
	"\x16TRANSFER_REASON_FORCED\x10\t*\x93\x02\n" +
	"\x18MovementCorrectionReason\x12*\n" +
	"&MOVEMENT_CORRECTION_REASON_UNSPECIFIED\x10\x00\x12+\n" +
	"'MOVEMENT_CORRECTION_REASON_ILLEGAL_MOVE\x10\x01\x12(\n" +
	"$MOVEMENT_CORRECTION_REASON_KNOCKBACK\x10\x02\x12%\n" +
	"!MOVEMENT_CORRECTION_REASON_PORTAL\x10\x03\x12&\n" +
	"\"MOVEMENT_CORRECTION_REASON_RESPAWN\x10\x04\x12%\n" +
	"!MOVEMENT_CORRECTION_REASON_FORCED\x10\x05*\x91\x01\n" +
	"\x10MovementEdgeType\x12\"\n" +
	"\x1eMOVEMENT_EDGE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MOVEMENT_EDGE_TYPE_PRESS\x10\x01\x12\x1e\n" +
	"\x1aMOVEMENT_EDGE_TYPE_RELEASE\x10\x02\x12\x1b\n" +
	"\x17MOVEMENT_EDGE_TYPE_FLIP\x10\x03*m\n" +
	"\rDungeonRunTag\x12\x1f\n" +
	"\x1bDUNGEON_RUN_TAG_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DUNGEON_RUN_TAG_NORMAL\x10\x01\x12\x1f\n" +
	"\x1bDUNGEON_RUN_TAG_ENDGAME_L60\x10\x02*\xd3\x01\n" +
	"\x14DungeonEntryResponse\x12&\n" +
	"\"DUNGEON_ENTRY_RESPONSE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDUNGEON_ENTRY_RESPONSE_PENDING\x10\x01\x12#\n" +
	"\x1fDUNGEON_ENTRY_RESPONSE_ACCEPTED\x10\x02\x12#\n" +
	"\x1fDUNGEON_ENTRY_RESPONSE_DECLINED\x10\x03\x12%\n" +
	"!DUNGEON_ENTRY_RESPONSE_INELIGIBLE\x10\x04*\xa7\x01\n" +
	"\x13DungeonEntryOutcome\x12%\n" +
	"!DUNGEON_ENTRY_OUTCOME_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDUNGEON_ENTRY_OUTCOME_PENDING\x10\x01\x12!\n" +
	"\x1dDUNGEON_ENTRY_OUTCOME_CREATED\x10\x02\x12#\n" +
	"\x1fDUNGEON_ENTRY_OUTCOME_CANCELLED\x10\x03*\x85\x01\n" +
	"\x14DungeonEntryDecision\x12&\n" +
	"\"DUNGEON_ENTRY_DECISION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDUNGEON_ENTRY_DECISION_ACCEPT\x10\x01\x12\"\n" +
	"\x1eDUNGEON_ENTRY_DECISION_DECLINE\x10\x02*s\n" +
	"\x10DungeonLeaveMode\x12\"\n" +
	"\x1eDUNGEON_LEAVE_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DUNGEON_LEAVE_MODE_EXIT\x10\x01\x12\x1e\n" +
	"\x1aDUNGEON_LEAVE_MODE_ABANDON\x10\x02BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_movement_proto_rawDescOnce sync.Once
	file_thinhthan_v1_movement_proto_rawDescData []byte
)

func file_thinhthan_v1_movement_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_movement_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_movement_proto_rawDesc), len(file_thinhthan_v1_movement_proto_rawDesc)))
	})
	return file_thinhthan_v1_movement_proto_rawDescData
}

var file_thinhthan_v1_movement_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_thinhthan_v1_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_thinhthan_v1_movement_proto_goTypes = []any{
	(InteractKind)(0),              // 0: thinhthan.v1.InteractKind
	(TransferReason)(0),            // 1: thinhthan.v1.TransferReason
	(MovementCorrectionReason)(0),  // 2: thinhthan.v1.MovementCorrectionReason
	(MovementEdgeType)(0),          // 3: thinhthan.v1.MovementEdgeType
	(DungeonRunTag)(0),             // 4: thinhthan.v1.DungeonRunTag
	(DungeonEntryResponse)(0),      // 5: thinhthan.v1.DungeonEntryResponse
	(DungeonEntryOutcome)(0),       // 6: thinhthan.v1.DungeonEntryOutcome
	(DungeonEntryDecision)(0),      // 7: thinhthan.v1.DungeonEntryDecision
	(DungeonLeaveMode)(0),          // 8: thinhthan.v1.DungeonLeaveMode
	(*DungeonEntryMember)(nil),     // 9: thinhthan.v1.DungeonEntryMember
	(*C2SInputState)(nil),          // 10: thinhthan.v1.C2SInputState
	(*C2SJump)(nil),                // 11: thinhthan.v1.C2SJump
	(*C2SDropThrough)(nil),         // 12: thinhthan.v1.C2SDropThrough
	(*C2SInteract)(nil),            // 13: thinhthan.v1.C2SInteract
	(*C2SPortalUse)(nil),           // 14: thinhthan.v1.C2SPortalUse
	(*S2CTransferPrepare)(nil),     // 15: thinhthan.v1.S2CTransferPrepare
	(*C2SPresentationReady)(nil),   // 16: thinhthan.v1.C2SPresentationReady
	(*S2CMovementCorrection)(nil),  // 17: thinhthan.v1.S2CMovementCorrection
	(*C2SMovementEdge)(nil),        // 18: thinhthan.v1.C2SMovementEdge
	(*C2SChannelSwitch)(nil),       // 19: thinhthan.v1.C2SChannelSwitch
	(*S2CChannelSwitchResult)(nil), // 20: thinhthan.v1.S2CChannelSwitchResult
	(*C2SDungeonEnterRequest)(nil), // 21: thinhthan.v1.C2SDungeonEnterRequest
	(*S2CDungeonEntryState)(nil),   // 22: thinhthan.v1.S2CDungeonEntryState
	(*C2SDungeonEntryRespond)(nil), // 23: thinhthan.v1.C2SDungeonEntryRespond
	(*C2SDungeonLeave)(nil),        // 24: thinhthan.v1.C2SDungeonLeave
	(*S2CDungeonLeaveResult)(nil),  // 25: thinhthan.v1.S2CDungeonLeaveResult
	(*S2CInteractResult)(nil),      // 26: thinhthan.v1.S2CInteractResult
	(*C2SDungeonEntryCancel)(nil),  // 27: thinhthan.v1.C2SDungeonEntryCancel
	(ErrorCode)(0),                 // 28: thinhthan.v1.ErrorCode
	(*MovementCheckpoint)(nil),     // 29: thinhthan.v1.MovementCheckpoint
	(Facing)(0),                    // 30: thinhthan.v1.Facing
	(*OperationResult)(nil),        // 31: thinhthan.v1.OperationResult
	(*ItemQuantity)(nil),           // 32: thinhthan.v1.ItemQuantity
	(*CurrencyDelta)(nil),          // 33: thinhthan.v1.CurrencyDelta
}
var file_thinhthan_v1_movement_proto_depIdxs = []int32{
	5,  // 0: thinhthan.v1.DungeonEntryMember.response:type_name -> thinhthan.v1.DungeonEntryResponse
	28, // 1: thinhthan.v1.DungeonEntryMember.error_code:type_name -> thinhthan.v1.ErrorCode
	0,  // 2: thinhthan.v1.C2SInteract.interact_kind:type_name -> thinhthan.v1.InteractKind
	1,  // 3: thinhthan.v1.S2CTransferPrepare.reason:type_name -> thinhthan.v1.TransferReason
	29, // 4: thinhthan.v1.S2CMovementCorrection.checkpoint:type_name -> thinhthan.v1.MovementCheckpoint
	2,  // 5: thinhthan.v1.S2CMovementCorrection.reason:type_name -> thinhthan.v1.MovementCorrectionReason
	3,  // 6: thinhthan.v1.C2SMovementEdge.edge_type:type_name -> thinhthan.v1.MovementEdgeType
	30, // 7: thinhthan.v1.C2SMovementEdge.direction:type_name -> thinhthan.v1.Facing
	31, // 8: thinhthan.v1.S2CChannelSwitchResult.result:type_name -> thinhthan.v1.OperationResult
	4,  // 9: thinhthan.v1.C2SDungeonEnterRequest.run_tag:type_name -> thinhthan.v1.DungeonRunTag
	31, // 10: thinhthan.v1.S2CDungeonEntryState.result:type_name -> thinhthan.v1.OperationResult
	4,  // 11: thinhthan.v1.S2CDungeonEntryState.run_tag:type_name -> thinhthan.v1.DungeonRunTag
	9,  // 12: thinhthan.v1.S2CDungeonEntryState.members:type_name -> thinhthan.v1.DungeonEntryMember
	6,  // 13: thinhthan.v1.S2CDungeonEntryState.outcome:type_name -> thinhthan.v1.DungeonEntryOutcome
	28, // 14: thinhthan.v1.S2CDungeonEntryState.cancel_reason_code:type_name -> thinhthan.v1.ErrorCode
	7,  // 15: thinhthan.v1.C2SDungeonEntryRespond.decision:type_name -> thinhthan.v1.DungeonEntryDecision
	8,  // 16: thinhthan.v1.C2SDungeonLeave.mode:type_name -> thinhthan.v1.DungeonLeaveMode
	31, // 17: thinhthan.v1.S2CDungeonLeaveResult.result:type_name -> thinhthan.v1.OperationResult
	8,  // 18: thinhthan.v1.S2CDungeonLeaveResult.mode:type_name -> thinhthan.v1.DungeonLeaveMode
	31, // 19: thinhthan.v1.S2CInteractResult.result:type_name -> thinhthan.v1.OperationResult
	0,  // 20: thinhthan.v1.S2CInteractResult.interact_kind:type_name -> thinhthan.v1.InteractKind
	32, // 21: thinhthan.v1.S2CInteractResult.granted:type_name -> thinhthan.v1.ItemQuantity
	33, // 22: thinhthan.v1.S2CInteractResult.currency_delta:type_name -> thinhthan.v1.CurrencyDelta
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_movement_proto_init() }
func file_thinhthan_v1_movement_proto_init() {
	if File_thinhthan_v1_movement_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	file_thinhthan_v1_movement_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_movement_proto_rawDesc), len(file_thinhthan_v1_movement_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_movement_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_movement_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_movement_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_movement_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_movement_proto = out.File
	file_thinhthan_v1_movement_proto_goTypes = nil
	file_thinhthan_v1_movement_proto_depIdxs = nil
}
