// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/pvp.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Queue-update state for S2C_RANKED_QUEUE_UPDATE.
type QueueUpdateState int32

const (
	QueueUpdateState_QUEUE_UPDATE_STATE_UNSPECIFIED QueueUpdateState = 0
	QueueUpdateState_QUEUE_UPDATE_STATE_QUEUED      QueueUpdateState = 1
	QueueUpdateState_QUEUE_UPDATE_STATE_MATCHED     QueueUpdateState = 2
	QueueUpdateState_QUEUE_UPDATE_STATE_ACCEPTING   QueueUpdateState = 3
	QueueUpdateState_QUEUE_UPDATE_STATE_LEFT        QueueUpdateState = 4
)

// Enum value maps for QueueUpdateState.
var (
	QueueUpdateState_name = map[int32]string{
		0: "QUEUE_UPDATE_STATE_UNSPECIFIED",
		1: "QUEUE_UPDATE_STATE_QUEUED",
		2: "QUEUE_UPDATE_STATE_MATCHED",
		3: "QUEUE_UPDATE_STATE_ACCEPTING",
		4: "QUEUE_UPDATE_STATE_LEFT",
	}
	QueueUpdateState_value = map[string]int32{
		"QUEUE_UPDATE_STATE_UNSPECIFIED": 0,
		"QUEUE_UPDATE_STATE_QUEUED":      1,
		"QUEUE_UPDATE_STATE_MATCHED":     2,
		"QUEUE_UPDATE_STATE_ACCEPTING":   3,
		"QUEUE_UPDATE_STATE_LEFT":        4,
	}
)

func (x QueueUpdateState) Enum() *QueueUpdateState {
	p := new(QueueUpdateState)
	*p = x
	return p
}

func (x QueueUpdateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueUpdateState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[0].Descriptor()
}

func (QueueUpdateState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[0]
}

func (x QueueUpdateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueUpdateState.Descriptor instead.
func (QueueUpdateState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{0}
}

// Match lifecycle shared by pvp.md and guild_war.md.
type MatchState int32

const (
	MatchState_MATCH_STATE_UNSPECIFIED MatchState = 0
	MatchState_MATCH_STATE_QUEUED      MatchState = 1
	MatchState_MATCH_STATE_MATCHED     MatchState = 2
	MatchState_MATCH_STATE_ACCEPTING   MatchState = 3
	MatchState_MATCH_STATE_PREPARING   MatchState = 4
	MatchState_MATCH_STATE_ACTIVE      MatchState = 5
	MatchState_MATCH_STATE_RESOLVING   MatchState = 6
	MatchState_MATCH_STATE_COMPLETED   MatchState = 7
	MatchState_MATCH_STATE_CANCELLED   MatchState = 8
	MatchState_MATCH_STATE_VOID        MatchState = 9
)

// Enum value maps for MatchState.
var (
	MatchState_name = map[int32]string{
		0: "MATCH_STATE_UNSPECIFIED",
		1: "MATCH_STATE_QUEUED",
		2: "MATCH_STATE_MATCHED",
		3: "MATCH_STATE_ACCEPTING",
		4: "MATCH_STATE_PREPARING",
		5: "MATCH_STATE_ACTIVE",
		6: "MATCH_STATE_RESOLVING",
		7: "MATCH_STATE_COMPLETED",
		8: "MATCH_STATE_CANCELLED",
		9: "MATCH_STATE_VOID",
	}
	MatchState_value = map[string]int32{
		"MATCH_STATE_UNSPECIFIED": 0,
		"MATCH_STATE_QUEUED":      1,
		"MATCH_STATE_MATCHED":     2,
		"MATCH_STATE_ACCEPTING":   3,
		"MATCH_STATE_PREPARING":   4,
		"MATCH_STATE_ACTIVE":      5,
		"MATCH_STATE_RESOLVING":   6,
		"MATCH_STATE_COMPLETED":   7,
		"MATCH_STATE_CANCELLED":   8,
		"MATCH_STATE_VOID":        9,
	}
)

func (x MatchState) Enum() *MatchState {
	p := new(MatchState)
	*p = x
	return p
}

func (x MatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[1].Descriptor()
}

func (MatchState) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[1]
}

func (x MatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchState.Descriptor instead.
func (MatchState) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{1}
}

type MatchResult int32

const (
	MatchResult_MATCH_RESULT_UNSPECIFIED MatchResult = 0
	MatchResult_MATCH_RESULT_NONE        MatchResult = 1
	MatchResult_MATCH_RESULT_WIN         MatchResult = 2
	MatchResult_MATCH_RESULT_LOSS        MatchResult = 3
	MatchResult_MATCH_RESULT_DRAW        MatchResult = 4
	MatchResult_MATCH_RESULT_VOID        MatchResult = 5
)

// Enum value maps for MatchResult.
var (
	MatchResult_name = map[int32]string{
		0: "MATCH_RESULT_UNSPECIFIED",
		1: "MATCH_RESULT_NONE",
		2: "MATCH_RESULT_WIN",
		3: "MATCH_RESULT_LOSS",
		4: "MATCH_RESULT_DRAW",
		5: "MATCH_RESULT_VOID",
	}
	MatchResult_value = map[string]int32{
		"MATCH_RESULT_UNSPECIFIED": 0,
		"MATCH_RESULT_NONE":        1,
		"MATCH_RESULT_WIN":         2,
		"MATCH_RESULT_LOSS":        3,
		"MATCH_RESULT_DRAW":        4,
		"MATCH_RESULT_VOID":        5,
	}
)

func (x MatchResult) Enum() *MatchResult {
	p := new(MatchResult)
	*p = x
	return p
}

func (x MatchResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchResult) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[2].Descriptor()
}

func (MatchResult) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[2]
}

func (x MatchResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchResult.Descriptor instead.
func (MatchResult) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{2}
}

type MatchReadyDecision int32

const (
	MatchReadyDecision_MATCH_READY_DECISION_UNSPECIFIED MatchReadyDecision = 0
	MatchReadyDecision_MATCH_READY_DECISION_ACCEPT      MatchReadyDecision = 1
	MatchReadyDecision_MATCH_READY_DECISION_DECLINE     MatchReadyDecision = 2
)

// Enum value maps for MatchReadyDecision.
var (
	MatchReadyDecision_name = map[int32]string{
		0: "MATCH_READY_DECISION_UNSPECIFIED",
		1: "MATCH_READY_DECISION_ACCEPT",
		2: "MATCH_READY_DECISION_DECLINE",
	}
	MatchReadyDecision_value = map[string]int32{
		"MATCH_READY_DECISION_UNSPECIFIED": 0,
		"MATCH_READY_DECISION_ACCEPT":      1,
		"MATCH_READY_DECISION_DECLINE":     2,
	}
)

func (x MatchReadyDecision) Enum() *MatchReadyDecision {
	p := new(MatchReadyDecision)
	*p = x
	return p
}

func (x MatchReadyDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchReadyDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[3].Descriptor()
}

func (MatchReadyDecision) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[3]
}

func (x MatchReadyDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchReadyDecision.Descriptor instead.
func (MatchReadyDecision) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{3}
}

type SparringOutcome int32

const (
	SparringOutcome_SPARRING_OUTCOME_UNSPECIFIED SparringOutcome = 0
	SparringOutcome_SPARRING_OUTCOME_ACCEPTED    SparringOutcome = 1
	SparringOutcome_SPARRING_OUTCOME_DECLINED    SparringOutcome = 2
	SparringOutcome_SPARRING_OUTCOME_EXPIRED     SparringOutcome = 3
	SparringOutcome_SPARRING_OUTCOME_REJECTED    SparringOutcome = 4
)

// Enum value maps for SparringOutcome.
var (
	SparringOutcome_name = map[int32]string{
		0: "SPARRING_OUTCOME_UNSPECIFIED",
		1: "SPARRING_OUTCOME_ACCEPTED",
		2: "SPARRING_OUTCOME_DECLINED",
		3: "SPARRING_OUTCOME_EXPIRED",
		4: "SPARRING_OUTCOME_REJECTED",
	}
	SparringOutcome_value = map[string]int32{
		"SPARRING_OUTCOME_UNSPECIFIED": 0,
		"SPARRING_OUTCOME_ACCEPTED":    1,
		"SPARRING_OUTCOME_DECLINED":    2,
		"SPARRING_OUTCOME_EXPIRED":     3,
		"SPARRING_OUTCOME_REJECTED":    4,
	}
)

func (x SparringOutcome) Enum() *SparringOutcome {
	p := new(SparringOutcome)
	*p = x
	return p
}

func (x SparringOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SparringOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[4].Descriptor()
}

func (SparringOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[4]
}

func (x SparringOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SparringOutcome.Descriptor instead.
func (SparringOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{4}
}

type DuelOutcome int32

const (
	DuelOutcome_DUEL_OUTCOME_UNSPECIFIED DuelOutcome = 0
	DuelOutcome_DUEL_OUTCOME_ACCEPTED    DuelOutcome = 1
	DuelOutcome_DUEL_OUTCOME_DECLINED    DuelOutcome = 2
	DuelOutcome_DUEL_OUTCOME_CANCELLED   DuelOutcome = 3
	DuelOutcome_DUEL_OUTCOME_EXPIRED     DuelOutcome = 4
	DuelOutcome_DUEL_OUTCOME_REJECTED    DuelOutcome = 5
)

// Enum value maps for DuelOutcome.
var (
	DuelOutcome_name = map[int32]string{
		0: "DUEL_OUTCOME_UNSPECIFIED",
		1: "DUEL_OUTCOME_ACCEPTED",
		2: "DUEL_OUTCOME_DECLINED",
		3: "DUEL_OUTCOME_CANCELLED",
		4: "DUEL_OUTCOME_EXPIRED",
		5: "DUEL_OUTCOME_REJECTED",
	}
	DuelOutcome_value = map[string]int32{
		"DUEL_OUTCOME_UNSPECIFIED": 0,
		"DUEL_OUTCOME_ACCEPTED":    1,
		"DUEL_OUTCOME_DECLINED":    2,
		"DUEL_OUTCOME_CANCELLED":   3,
		"DUEL_OUTCOME_EXPIRED":     4,
		"DUEL_OUTCOME_REJECTED":    5,
	}
)

func (x DuelOutcome) Enum() *DuelOutcome {
	p := new(DuelOutcome)
	*p = x
	return p
}

func (x DuelOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DuelOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_pvp_proto_enumTypes[5].Descriptor()
}

func (DuelOutcome) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_pvp_proto_enumTypes[5]
}

func (x DuelOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DuelOutcome.Descriptor instead.
func (DuelOutcome) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{5}
}

type MatchMemberView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	Connected     bool                   `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchMemberView) Reset() {
	*x = MatchMemberView{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchMemberView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchMemberView) ProtoMessage() {}

func (x *MatchMemberView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchMemberView.ProtoReflect.Descriptor instead.
func (*MatchMemberView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{0}
}

func (x *MatchMemberView) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *MatchMemberView) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MatchMemberView) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *MatchMemberView) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *MatchMemberView) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type MatchTeamView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamIndex     uint32                 `protobuf:"varint,1,opt,name=team_index,json=teamIndex,proto3" json:"team_index,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Members       []*MatchMemberView     `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTeamView) Reset() {
	*x = MatchTeamView{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTeamView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTeamView) ProtoMessage() {}

func (x *MatchTeamView) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTeamView.ProtoReflect.Descriptor instead.
func (*MatchTeamView) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{1}
}

func (x *MatchTeamView) GetTeamIndex() uint32 {
	if x != nil {
		return x.TeamIndex
	}
	return 0
}

func (x *MatchTeamView) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MatchTeamView) GetMembers() []*MatchMemberView {
	if x != nil {
		return x.Members
	}
	return nil
}

// ID 800
type C2SSparringRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                     // UUID, 16 bytes
	TargetCharacterId []byte                 `protobuf:"bytes,2,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"` // UUID, 16 bytes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *C2SSparringRequest) Reset() {
	*x = C2SSparringRequest{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SSparringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSparringRequest) ProtoMessage() {}

func (x *C2SSparringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSparringRequest.ProtoReflect.Descriptor instead.
func (*C2SSparringRequest) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{2}
}

func (x *C2SSparringRequest) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SSparringRequest) GetTargetCharacterId() []byte {
	if x != nil {
		return x.TargetCharacterId
	}
	return nil
}

// ID 801
type C2SSparringAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SSparringAccept) Reset() {
	*x = C2SSparringAccept{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SSparringAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSparringAccept) ProtoMessage() {}

func (x *C2SSparringAccept) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSparringAccept.ProtoReflect.Descriptor instead.
func (*C2SSparringAccept) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{3}
}

func (x *C2SSparringAccept) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SSparringAccept) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

// ID 812
type C2SSparringDecline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SSparringDecline) Reset() {
	*x = C2SSparringDecline{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SSparringDecline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSparringDecline) ProtoMessage() {}

func (x *C2SSparringDecline) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSparringDecline.ProtoReflect.Descriptor instead.
func (*C2SSparringDecline) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{4}
}

func (x *C2SSparringDecline) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SSparringDecline) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

// ID 811
type S2CSparringChallenge struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId           []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`                                 // UUID, 16 bytes
	ChallengerCharacterId []byte                 `protobuf:"bytes,2,opt,name=challenger_character_id,json=challengerCharacterId,proto3" json:"challenger_character_id,omitempty"` // UUID, 16 bytes
	ChallengerName        string                 `protobuf:"bytes,3,opt,name=challenger_name,json=challengerName,proto3" json:"challenger_name,omitempty"`
	ExpiresInSeconds      uint32                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"` // 60
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *S2CSparringChallenge) Reset() {
	*x = S2CSparringChallenge{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CSparringChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSparringChallenge) ProtoMessage() {}

func (x *S2CSparringChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSparringChallenge.ProtoReflect.Descriptor instead.
func (*S2CSparringChallenge) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{5}
}

func (x *S2CSparringChallenge) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2CSparringChallenge) GetChallengerCharacterId() []byte {
	if x != nil {
		return x.ChallengerCharacterId
	}
	return nil
}

func (x *S2CSparringChallenge) GetChallengerName() string {
	if x != nil {
		return x.ChallengerName
	}
	return ""
}

func (x *S2CSparringChallenge) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// ID 813
type S2CSparringOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID, 16 bytes
	Outcome       SparringOutcome        `protobuf:"varint,2,opt,name=outcome,proto3,enum=thinhthan.v1.SparringOutcome" json:"outcome,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CSparringOutcome) Reset() {
	*x = S2CSparringOutcome{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CSparringOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSparringOutcome) ProtoMessage() {}

func (x *S2CSparringOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSparringOutcome.ProtoReflect.Descriptor instead.
func (*S2CSparringOutcome) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{6}
}

func (x *S2CSparringOutcome) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2CSparringOutcome) GetOutcome() SparringOutcome {
	if x != nil {
		return x.Outcome
	}
	return SparringOutcome_SPARRING_OUTCOME_UNSPECIFIED
}

func (x *S2CSparringOutcome) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// ID 802
type C2SRankedQueueJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	PvpModeId     string                 `protobuf:"bytes,2,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	WithParty     bool                   `protobuf:"varint,3,opt,name=with_party,json=withParty,proto3" json:"with_party,omitempty"` // Arena only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SRankedQueueJoin) Reset() {
	*x = C2SRankedQueueJoin{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SRankedQueueJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRankedQueueJoin) ProtoMessage() {}

func (x *C2SRankedQueueJoin) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRankedQueueJoin.ProtoReflect.Descriptor instead.
func (*C2SRankedQueueJoin) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{7}
}

func (x *C2SRankedQueueJoin) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SRankedQueueJoin) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

func (x *C2SRankedQueueJoin) GetWithParty() bool {
	if x != nil {
		return x.WithParty
	}
	return false
}

// ID 803
type C2SRankedQueueLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	PvpModeId     string                 `protobuf:"bytes,2,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SRankedQueueLeave) Reset() {
	*x = C2SRankedQueueLeave{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SRankedQueueLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRankedQueueLeave) ProtoMessage() {}

func (x *C2SRankedQueueLeave) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRankedQueueLeave.ProtoReflect.Descriptor instead.
func (*C2SRankedQueueLeave) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{8}
}

func (x *C2SRankedQueueLeave) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SRankedQueueLeave) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

// ID 804
type S2CRankedQueueUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PvpModeId       string                 `protobuf:"bytes,1,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	State           QueueUpdateState       `protobuf:"varint,2,opt,name=state,proto3,enum=thinhthan.v1.QueueUpdateState" json:"state,omitempty"`
	QueuedSeconds   uint32                 `protobuf:"varint,3,opt,name=queued_seconds,json=queuedSeconds,proto3" json:"queued_seconds,omitempty"`
	PvpMatchId      []byte                 `protobuf:"bytes,4,opt,name=pvp_match_id,json=pvpMatchId,proto3" json:"pvp_match_id,omitempty"`                 // UUID, 16 bytes; from MATCHED
	ReadyDeadlineMs uint32                 `protobuf:"varint,5,opt,name=ready_deadline_ms,json=readyDeadlineMs,proto3" json:"ready_deadline_ms,omitempty"` // ACCEPTING
	ErrorCode       ErrorCode              `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2CRankedQueueUpdate) Reset() {
	*x = S2CRankedQueueUpdate{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CRankedQueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRankedQueueUpdate) ProtoMessage() {}

func (x *S2CRankedQueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRankedQueueUpdate.ProtoReflect.Descriptor instead.
func (*S2CRankedQueueUpdate) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{9}
}

func (x *S2CRankedQueueUpdate) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

func (x *S2CRankedQueueUpdate) GetState() QueueUpdateState {
	if x != nil {
		return x.State
	}
	return QueueUpdateState_QUEUE_UPDATE_STATE_UNSPECIFIED
}

func (x *S2CRankedQueueUpdate) GetQueuedSeconds() uint32 {
	if x != nil {
		return x.QueuedSeconds
	}
	return 0
}

func (x *S2CRankedQueueUpdate) GetPvpMatchId() []byte {
	if x != nil {
		return x.PvpMatchId
	}
	return nil
}

func (x *S2CRankedQueueUpdate) GetReadyDeadlineMs() uint32 {
	if x != nil {
		return x.ReadyDeadlineMs
	}
	return 0
}

func (x *S2CRankedQueueUpdate) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// ID 805
type C2SMatchReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	MatchId       []byte                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`             // UUID, 16 bytes
	Decision      MatchReadyDecision     `protobuf:"varint,3,opt,name=decision,proto3,enum=thinhthan.v1.MatchReadyDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMatchReady) Reset() {
	*x = C2SMatchReady{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMatchReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMatchReady) ProtoMessage() {}

func (x *C2SMatchReady) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMatchReady.ProtoReflect.Descriptor instead.
func (*C2SMatchReady) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{10}
}

func (x *C2SMatchReady) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SMatchReady) GetMatchId() []byte {
	if x != nil {
		return x.MatchId
	}
	return nil
}

func (x *C2SMatchReady) GetDecision() MatchReadyDecision {
	if x != nil {
		return x.Decision
	}
	return MatchReadyDecision_MATCH_READY_DECISION_UNSPECIFIED
}

// ID 806
type S2CMatchState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchId         []byte                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // UUID, 16 bytes
	PvpModeId       string                 `protobuf:"bytes,2,opt,name=pvp_mode_id,json=pvpModeId,proto3" json:"pvp_mode_id,omitempty"`
	State           MatchState             `protobuf:"varint,3,opt,name=state,proto3,enum=thinhthan.v1.MatchState" json:"state,omitempty"`
	StateDeadlineMs int64                  `protobuf:"varint,4,opt,name=state_deadline_ms,json=stateDeadlineMs,proto3" json:"state_deadline_ms,omitempty"`
	RoundNumber     uint32                 `protobuf:"varint,5,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Teams           []*MatchTeamView       `protobuf:"bytes,6,rep,name=teams,proto3" json:"teams,omitempty"`
	Result          MatchResult            `protobuf:"varint,7,opt,name=result,proto3,enum=thinhthan.v1.MatchResult" json:"result,omitempty"`     // receiver's team
	RatingBefore    int32                  `protobuf:"zigzag32,8,opt,name=rating_before,json=ratingBefore,proto3" json:"rating_before,omitempty"` // ranked only; 0 otherwise
	RatingAfter     int32                  `protobuf:"zigzag32,9,opt,name=rating_after,json=ratingAfter,proto3" json:"rating_after,omitempty"`    // ranked only; 0 otherwise
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2CMatchState) Reset() {
	*x = S2CMatchState{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CMatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMatchState) ProtoMessage() {}

func (x *S2CMatchState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMatchState.ProtoReflect.Descriptor instead.
func (*S2CMatchState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{11}
}

func (x *S2CMatchState) GetMatchId() []byte {
	if x != nil {
		return x.MatchId
	}
	return nil
}

func (x *S2CMatchState) GetPvpModeId() string {
	if x != nil {
		return x.PvpModeId
	}
	return ""
}

func (x *S2CMatchState) GetState() MatchState {
	if x != nil {
		return x.State
	}
	return MatchState_MATCH_STATE_UNSPECIFIED
}

func (x *S2CMatchState) GetStateDeadlineMs() int64 {
	if x != nil {
		return x.StateDeadlineMs
	}
	return 0
}

func (x *S2CMatchState) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *S2CMatchState) GetTeams() []*MatchTeamView {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *S2CMatchState) GetResult() MatchResult {
	if x != nil {
		return x.Result
	}
	return MatchResult_MATCH_RESULT_UNSPECIFIED
}

func (x *S2CMatchState) GetRatingBefore() int32 {
	if x != nil {
		return x.RatingBefore
	}
	return 0
}

func (x *S2CMatchState) GetRatingAfter() int32 {
	if x != nil {
		return x.RatingAfter
	}
	return 0
}

// ID 807
type C2SMatchSurrender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	MatchId       []byte                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`             // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMatchSurrender) Reset() {
	*x = C2SMatchSurrender{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMatchSurrender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMatchSurrender) ProtoMessage() {}

func (x *C2SMatchSurrender) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMatchSurrender.ProtoReflect.Descriptor instead.
func (*C2SMatchSurrender) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{12}
}

func (x *C2SMatchSurrender) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SMatchSurrender) GetMatchId() []byte {
	if x != nil {
		return x.MatchId
	}
	return nil
}

// ID 808
type C2SGuildWarQueueJoin struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OperationId        []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                        // UUID, 16 bytes
	RosterCharacterIds [][]byte               `protobuf:"bytes,2,rep,name=roster_character_ids,json=rosterCharacterIds,proto3" json:"roster_character_ids,omitempty"` // UUID, 16 bytes; exactly 10 distinct
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *C2SGuildWarQueueJoin) Reset() {
	*x = C2SGuildWarQueueJoin{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SGuildWarQueueJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGuildWarQueueJoin) ProtoMessage() {}

func (x *C2SGuildWarQueueJoin) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGuildWarQueueJoin.ProtoReflect.Descriptor instead.
func (*C2SGuildWarQueueJoin) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{13}
}

func (x *C2SGuildWarQueueJoin) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SGuildWarQueueJoin) GetRosterCharacterIds() [][]byte {
	if x != nil {
		return x.RosterCharacterIds
	}
	return nil
}

// ID 809
type C2SGuildWarQueueLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SGuildWarQueueLeave) Reset() {
	*x = C2SGuildWarQueueLeave{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SGuildWarQueueLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGuildWarQueueLeave) ProtoMessage() {}

func (x *C2SGuildWarQueueLeave) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGuildWarQueueLeave.ProtoReflect.Descriptor instead.
func (*C2SGuildWarQueueLeave) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{14}
}

func (x *C2SGuildWarQueueLeave) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

// ID 810
type S2CGuildWarState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GuildId            []byte                 `protobuf:"bytes,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"` // UUID, 16 bytes
	State              MatchState             `protobuf:"varint,2,opt,name=state,proto3,enum=thinhthan.v1.MatchState" json:"state,omitempty"`
	RosterCharacterIds [][]byte               `protobuf:"bytes,3,rep,name=roster_character_ids,json=rosterCharacterIds,proto3" json:"roster_character_ids,omitempty"` // UUID, 16 bytes
	GuildWarMatchId    []byte                 `protobuf:"bytes,4,opt,name=guild_war_match_id,json=guildWarMatchId,proto3" json:"guild_war_match_id,omitempty"`        // UUID, 16 bytes
	ReadyDeadlineMs    uint32                 `protobuf:"varint,5,opt,name=ready_deadline_ms,json=readyDeadlineMs,proto3" json:"ready_deadline_ms,omitempty"`
	ErrorCode          ErrorCode              `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *S2CGuildWarState) Reset() {
	*x = S2CGuildWarState{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CGuildWarState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGuildWarState) ProtoMessage() {}

func (x *S2CGuildWarState) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGuildWarState.ProtoReflect.Descriptor instead.
func (*S2CGuildWarState) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{15}
}

func (x *S2CGuildWarState) GetGuildId() []byte {
	if x != nil {
		return x.GuildId
	}
	return nil
}

func (x *S2CGuildWarState) GetState() MatchState {
	if x != nil {
		return x.State
	}
	return MatchState_MATCH_STATE_UNSPECIFIED
}

func (x *S2CGuildWarState) GetRosterCharacterIds() [][]byte {
	if x != nil {
		return x.RosterCharacterIds
	}
	return nil
}

func (x *S2CGuildWarState) GetGuildWarMatchId() []byte {
	if x != nil {
		return x.GuildWarMatchId
	}
	return nil
}

func (x *S2CGuildWarState) GetReadyDeadlineMs() uint32 {
	if x != nil {
		return x.ReadyDeadlineMs
	}
	return 0
}

func (x *S2CGuildWarState) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// ID 814
type C2SDuelChallenge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                     // UUID, 16 bytes
	TargetCharacterId []byte                 `protobuf:"bytes,2,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"` // UUID, 16 bytes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *C2SDuelChallenge) Reset() {
	*x = C2SDuelChallenge{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDuelChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDuelChallenge) ProtoMessage() {}

func (x *C2SDuelChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDuelChallenge.ProtoReflect.Descriptor instead.
func (*C2SDuelChallenge) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{16}
}

func (x *C2SDuelChallenge) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDuelChallenge) GetTargetCharacterId() []byte {
	if x != nil {
		return x.TargetCharacterId
	}
	return nil
}

// ID 815
type S2CDuelChallenge struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId           []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`                                 // UUID, 16 bytes
	ChallengerCharacterId []byte                 `protobuf:"bytes,2,opt,name=challenger_character_id,json=challengerCharacterId,proto3" json:"challenger_character_id,omitempty"` // UUID, 16 bytes
	ChallengerName        string                 `protobuf:"bytes,3,opt,name=challenger_name,json=challengerName,proto3" json:"challenger_name,omitempty"`
	ExpiresInSeconds      uint32                 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"` // 60
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *S2CDuelChallenge) Reset() {
	*x = S2CDuelChallenge{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CDuelChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDuelChallenge) ProtoMessage() {}

func (x *S2CDuelChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDuelChallenge.ProtoReflect.Descriptor instead.
func (*S2CDuelChallenge) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{17}
}

func (x *S2CDuelChallenge) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2CDuelChallenge) GetChallengerCharacterId() []byte {
	if x != nil {
		return x.ChallengerCharacterId
	}
	return nil
}

func (x *S2CDuelChallenge) GetChallengerName() string {
	if x != nil {
		return x.ChallengerName
	}
	return ""
}

func (x *S2CDuelChallenge) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// ID 816
type C2SDuelRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID, 16 bytes
	Decision      MatchReadyDecision     `protobuf:"varint,3,opt,name=decision,proto3,enum=thinhthan.v1.MatchReadyDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDuelRespond) Reset() {
	*x = C2SDuelRespond{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDuelRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDuelRespond) ProtoMessage() {}

func (x *C2SDuelRespond) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDuelRespond.ProtoReflect.Descriptor instead.
func (*C2SDuelRespond) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{18}
}

func (x *C2SDuelRespond) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDuelRespond) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *C2SDuelRespond) GetDecision() MatchReadyDecision {
	if x != nil {
		return x.Decision
	}
	return MatchReadyDecision_MATCH_READY_DECISION_UNSPECIFIED
}

// ID 817
type C2SDuelCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	ChallengeId   []byte                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SDuelCancel) Reset() {
	*x = C2SDuelCancel{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SDuelCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDuelCancel) ProtoMessage() {}

func (x *C2SDuelCancel) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDuelCancel.ProtoReflect.Descriptor instead.
func (*C2SDuelCancel) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{19}
}

func (x *C2SDuelCancel) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SDuelCancel) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

// ID 818
type S2CDuelOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   []byte                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"` // UUID, 16 bytes
	Outcome       DuelOutcome            `protobuf:"varint,2,opt,name=outcome,proto3,enum=thinhthan.v1.DuelOutcome" json:"outcome,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CDuelOutcome) Reset() {
	*x = S2CDuelOutcome{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CDuelOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDuelOutcome) ProtoMessage() {}

func (x *S2CDuelOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDuelOutcome.ProtoReflect.Descriptor instead.
func (*S2CDuelOutcome) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{20}
}

func (x *S2CDuelOutcome) GetChallengeId() []byte {
	if x != nil {
		return x.ChallengeId
	}
	return nil
}

func (x *S2CDuelOutcome) GetOutcome() DuelOutcome {
	if x != nil {
		return x.Outcome
	}
	return DuelOutcome_DUEL_OUTCOME_UNSPECIFIED
}

func (x *S2CDuelOutcome) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

// ID 819
type S2CPvpResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	RequestMessageId uint32                 `protobuf:"varint,2,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"` // 800|801|802|803|805|807|808|809|812|814|816|817
	ReferenceId      []byte                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`                   // UUID, 16 bytes; challenge_id or match_id, empty when none
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2CPvpResult) Reset() {
	*x = S2CPvpResult{}
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CPvpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPvpResult) ProtoMessage() {}

func (x *S2CPvpResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_pvp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPvpResult.ProtoReflect.Descriptor instead.
func (*S2CPvpResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_pvp_proto_rawDescGZIP(), []int{21}
}

func (x *S2CPvpResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CPvpResult) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2CPvpResult) GetReferenceId() []byte {
	if x != nil {
		return x.ReferenceId
	}
	return nil
}

var File_thinhthan_v1_pvp_proto protoreflect.FileDescriptor

const file_thinhthan_v1_pvp_proto_rawDesc = "" +
	"\n" +
	"\x16thinhthan/v1/pvp.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"\xa6\x01\n" +
	"\x0fMatchMemberView\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1c\n" +
	"\tconnected\x18\x05 \x01(\bR\tconnected\"}\n" +
	"\rMatchTeamView\x12\x1d\n" +
	"\n" +
	"team_index\x18\x01 \x01(\rR\tteamIndex\x12\x14\n" +
	"\x05score\x18\x02 \x01(\rR\x05score\x127\n" +
	"\amembers\x18\x03 \x03(\v2\x1d.thinhthan.v1.MatchMemberViewR\amembers\"g\n" +
	"\x12C2SSparringRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12.\n" +
	"\x13target_character_id\x18\x02 \x01(\fR\x11targetCharacterId\"Y\n" +
	"\x11C2SSparringAccept\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\"Z\n" +
	"\x12C2SSparringDecline\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\"\xc8\x01\n" +
	"\x14S2CSparringChallenge\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x126\n" +
	"\x17challenger_character_id\x18\x02 \x01(\fR\x15challengerCharacterId\x12'\n" +
	"\x0fchallenger_name\x18\x03 \x01(\tR\x0echallengerName\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\rR\x10expiresInSeconds\"\xa8\x01\n" +
	"\x12S2CSparringOutcome\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x127\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x1d.thinhthan.v1.SparringOutcomeR\aoutcome\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"v\n" +
	"\x12C2SRankedQueueJoin\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1e\n" +
	"\vpvp_mode_id\x18\x02 \x01(\tR\tpvpModeId\x12\x1d\n" +
	"\n" +
	"with_party\x18\x03 \x01(\bR\twithParty\"X\n" +
	"\x13C2SRankedQueueLeave\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x1e\n" +
	"\vpvp_mode_id\x18\x02 \x01(\tR\tpvpModeId\"\x99\x02\n" +
	"\x14S2CRankedQueueUpdate\x12\x1e\n" +
	"\vpvp_mode_id\x18\x01 \x01(\tR\tpvpModeId\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.thinhthan.v1.QueueUpdateStateR\x05state\x12%\n" +
	"\x0equeued_seconds\x18\x03 \x01(\rR\rqueuedSeconds\x12 \n" +
	"\fpvp_match_id\x18\x04 \x01(\fR\n" +
	"pvpMatchId\x12*\n" +
	"\x11ready_deadline_ms\x18\x05 \x01(\rR\x0freadyDeadlineMs\x126\n" +
	"\n" +
	"error_code\x18\x06 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"\x8b\x01\n" +
	"\rC2SMatchReady\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\fR\amatchId\x12<\n" +
	"\bdecision\x18\x03 \x01(\x0e2 .thinhthan.v1.MatchReadyDecisionR\bdecision\"\xf7\x02\n" +
	"\rS2CMatchState\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\fR\amatchId\x12\x1e\n" +
	"\vpvp_mode_id\x18\x02 \x01(\tR\tpvpModeId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.thinhthan.v1.MatchStateR\x05state\x12*\n" +
	"\x11state_deadline_ms\x18\x04 \x01(\x03R\x0fstateDeadlineMs\x12!\n" +
	"\fround_number\x18\x05 \x01(\rR\vroundNumber\x121\n" +
	"\x05teams\x18\x06 \x03(\v2\x1b.thinhthan.v1.MatchTeamViewR\x05teams\x121\n" +
	"\x06result\x18\a \x01(\x0e2\x19.thinhthan.v1.MatchResultR\x06result\x12#\n" +
	"\rrating_before\x18\b \x01(\x11R\fratingBefore\x12!\n" +
	"\frating_after\x18\t \x01(\x11R\vratingAfter\"Q\n" +
	"\x11C2SMatchSurrender\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\fR\amatchId\"k\n" +
	"\x14C2SGuildWarQueueJoin\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x120\n" +
	"\x14roster_character_ids\x18\x02 \x03(\fR\x12rosterCharacterIds\":\n" +
	"\x15C2SGuildWarQueueLeave\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\"\xa0\x02\n" +
	"\x10S2CGuildWarState\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\fR\aguildId\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.thinhthan.v1.MatchStateR\x05state\x120\n" +
	"\x14roster_character_ids\x18\x03 \x03(\fR\x12rosterCharacterIds\x12+\n" +
	"\x12guild_war_match_id\x18\x04 \x01(\fR\x0fguildWarMatchId\x12*\n" +
	"\x11ready_deadline_ms\x18\x05 \x01(\rR\x0freadyDeadlineMs\x126\n" +
	"\n" +
	"error_code\x18\x06 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"e\n" +
	"\x10C2SDuelChallenge\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12.\n" +
	"\x13target_character_id\x18\x02 \x01(\fR\x11targetCharacterId\"\xc4\x01\n" +
	"\x10S2CDuelChallenge\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x126\n" +
	"\x17challenger_character_id\x18\x02 \x01(\fR\x15challengerCharacterId\x12'\n" +
	"\x0fchallenger_name\x18\x03 \x01(\tR\x0echallengerName\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\rR\x10expiresInSeconds\"\x94\x01\n" +
	"\x0eC2SDuelRespond\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\x12<\n" +
	"\bdecision\x18\x03 \x01(\x0e2 .thinhthan.v1.MatchReadyDecisionR\bdecision\"U\n" +
	"\rC2SDuelCancel\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\fR\vchallengeId\"\xa0\x01\n" +
	"\x0eS2CDuelOutcome\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\fR\vchallengeId\x123\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x19.thinhthan.v1.DuelOutcomeR\aoutcome\x126\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\"\x96\x01\n" +
	"\fS2CPvpResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12,\n" +
	"\x12request_message_id\x18\x02 \x01(\rR\x10requestMessageId\x12!\n" +
	"\freference_id\x18\x03 \x01(\fR\vreferenceId*\xb4\x01\n" +
	"\x10QueueUpdateState\x12\"\n" +
	"\x1eQUEUE_UPDATE_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19QUEUE_UPDATE_STATE_QUEUED\x10\x01\x12\x1e\n" +
	"\x1aQUEUE_UPDATE_STATE_MATCHED\x10\x02\x12 \n" +
	"\x1cQUEUE_UPDATE_STATE_ACCEPTING\x10\x03\x12\x1b\n" +
	"\x17QUEUE_UPDATE_STATE_LEFT\x10\x04*\x8f\x02\n" +
	"\n" +
	"MatchState\x12\x1b\n" +
	"\x17MATCH_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MATCH_STATE_QUEUED\x10\x01\x12\x17\n" +
	"\x13MATCH_STATE_MATCHED\x10\x02\x12\x19\n" +
	"\x15MATCH_STATE_ACCEPTING\x10\x03\x12\x19\n" +
	"\x15MATCH_STATE_PREPARING\x10\x04\x12\x16\n" +
	"\x12MATCH_STATE_ACTIVE\x10\x05\x12\x19\n" +
	"\x15MATCH_STATE_RESOLVING\x10\x06\x12\x19\n" +
	"\x15MATCH_STATE_COMPLETED\x10\a\x12\x19\n" +
	"\x15MATCH_STATE_CANCELLED\x10\b\x12\x14\n" +
	"\x10MATCH_STATE_VOID\x10\t*\x9d\x01\n" +
	"\vMatchResult\x12\x1c\n" +
	"\x18MATCH_RESULT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MATCH_RESULT_NONE\x10\x01\x12\x14\n" +
	"\x10MATCH_RESULT_WIN\x10\x02\x12\x15\n" +
	"\x11MATCH_RESULT_LOSS\x10\x03\x12\x15\n" +
	"\x11MATCH_RESULT_DRAW\x10\x04\x12\x15\n" +
	"\x11MATCH_RESULT_VOID\x10\x05*}\n" +
	"\x12MatchReadyDecision\x12$\n" +
	" MATCH_READY_DECISION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bMATCH_READY_DECISION_ACCEPT\x10\x01\x12 \n" +
	"\x1cMATCH_READY_DECISION_DECLINE\x10\x02*\xae\x01\n" +
	"\x0fSparringOutcome\x12 \n" +
	"\x1cSPARRING_OUTCOME_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SPARRING_OUTCOME_ACCEPTED\x10\x01\x12\x1d\n" +
	"\x19SPARRING_OUTCOME_DECLINED\x10\x02\x12\x1c\n" +
	"\x18SPARRING_OUTCOME_EXPIRED\x10\x03\x12\x1d\n" +
	"\x19SPARRING_OUTCOME_REJECTED\x10\x04*\xb2\x01\n" +
	"\vDuelOutcome\x12\x1c\n" +
	"\x18DUEL_OUTCOME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DUEL_OUTCOME_ACCEPTED\x10\x01\x12\x19\n" +
	"\x15DUEL_OUTCOME_DECLINED\x10\x02\x12\x1a\n" +
	"\x16DUEL_OUTCOME_CANCELLED\x10\x03\x12\x18\n" +
	"\x14DUEL_OUTCOME_EXPIRED\x10\x04\x12\x19\n" +
	"\x15DUEL_OUTCOME_REJECTED\x10\x05BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_pvp_proto_rawDescOnce sync.Once
	file_thinhthan_v1_pvp_proto_rawDescData []byte
)

func file_thinhthan_v1_pvp_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_pvp_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_pvp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_pvp_proto_rawDesc), len(file_thinhthan_v1_pvp_proto_rawDesc)))
	})
	return file_thinhthan_v1_pvp_proto_rawDescData
}

var file_thinhthan_v1_pvp_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_thinhthan_v1_pvp_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_thinhthan_v1_pvp_proto_goTypes = []any{
	(QueueUpdateState)(0),         // 0: thinhthan.v1.QueueUpdateState
	(MatchState)(0),               // 1: thinhthan.v1.MatchState
	(MatchResult)(0),              // 2: thinhthan.v1.MatchResult
	(MatchReadyDecision)(0),       // 3: thinhthan.v1.MatchReadyDecision
	(SparringOutcome)(0),          // 4: thinhthan.v1.SparringOutcome
	(DuelOutcome)(0),              // 5: thinhthan.v1.DuelOutcome
	(*MatchMemberView)(nil),       // 6: thinhthan.v1.MatchMemberView
	(*MatchTeamView)(nil),         // 7: thinhthan.v1.MatchTeamView
	(*C2SSparringRequest)(nil),    // 8: thinhthan.v1.C2SSparringRequest
	(*C2SSparringAccept)(nil),     // 9: thinhthan.v1.C2SSparringAccept
	(*C2SSparringDecline)(nil),    // 10: thinhthan.v1.C2SSparringDecline
	(*S2CSparringChallenge)(nil),  // 11: thinhthan.v1.S2CSparringChallenge
	(*S2CSparringOutcome)(nil),    // 12: thinhthan.v1.S2CSparringOutcome
	(*C2SRankedQueueJoin)(nil),    // 13: thinhthan.v1.C2SRankedQueueJoin
	(*C2SRankedQueueLeave)(nil),   // 14: thinhthan.v1.C2SRankedQueueLeave
	(*S2CRankedQueueUpdate)(nil),  // 15: thinhthan.v1.S2CRankedQueueUpdate
	(*C2SMatchReady)(nil),         // 16: thinhthan.v1.C2SMatchReady
	(*S2CMatchState)(nil),         // 17: thinhthan.v1.S2CMatchState
	(*C2SMatchSurrender)(nil),     // 18: thinhthan.v1.C2SMatchSurrender
	(*C2SGuildWarQueueJoin)(nil),  // 19: thinhthan.v1.C2SGuildWarQueueJoin
	(*C2SGuildWarQueueLeave)(nil), // 20: thinhthan.v1.C2SGuildWarQueueLeave
	(*S2CGuildWarState)(nil),      // 21: thinhthan.v1.S2CGuildWarState
	(*C2SDuelChallenge)(nil),      // 22: thinhthan.v1.C2SDuelChallenge
	(*S2CDuelChallenge)(nil),      // 23: thinhthan.v1.S2CDuelChallenge
	(*C2SDuelRespond)(nil),        // 24: thinhthan.v1.C2SDuelRespond
	(*C2SDuelCancel)(nil),         // 25: thinhthan.v1.C2SDuelCancel
	(*S2CDuelOutcome)(nil),        // 26: thinhthan.v1.S2CDuelOutcome
	(*S2CPvpResult)(nil),          // 27: thinhthan.v1.S2CPvpResult
	(ErrorCode)(0),                // 28: thinhthan.v1.ErrorCode
	(*OperationResult)(nil),       // 29: thinhthan.v1.OperationResult
}
var file_thinhthan_v1_pvp_proto_depIdxs = []int32{
	6,  // 0: thinhthan.v1.MatchTeamView.members:type_name -> thinhthan.v1.MatchMemberView
	4,  // 1: thinhthan.v1.S2CSparringOutcome.outcome:type_name -> thinhthan.v1.SparringOutcome
	28, // 2: thinhthan.v1.S2CSparringOutcome.error_code:type_name -> thinhthan.v1.ErrorCode
	0,  // 3: thinhthan.v1.S2CRankedQueueUpdate.state:type_name -> thinhthan.v1.QueueUpdateState
	28, // 4: thinhthan.v1.S2CRankedQueueUpdate.error_code:type_name -> thinhthan.v1.ErrorCode
	3,  // 5: thinhthan.v1.C2SMatchReady.decision:type_name -> thinhthan.v1.MatchReadyDecision
	1,  // 6: thinhthan.v1.S2CMatchState.state:type_name -> thinhthan.v1.MatchState
	7,  // 7: thinhthan.v1.S2CMatchState.teams:type_name -> thinhthan.v1.MatchTeamView
	2,  // 8: thinhthan.v1.S2CMatchState.result:type_name -> thinhthan.v1.MatchResult
	1,  // 9: thinhthan.v1.S2CGuildWarState.state:type_name -> thinhthan.v1.MatchState
	28, // 10: thinhthan.v1.S2CGuildWarState.error_code:type_name -> thinhthan.v1.ErrorCode
	3,  // 11: thinhthan.v1.C2SDuelRespond.decision:type_name -> thinhthan.v1.MatchReadyDecision
	5,  // 12: thinhthan.v1.S2CDuelOutcome.outcome:type_name -> thinhthan.v1.DuelOutcome
	28, // 13: thinhthan.v1.S2CDuelOutcome.error_code:type_name -> thinhthan.v1.ErrorCode
	29, // 14: thinhthan.v1.S2CPvpResult.result:type_name -> thinhthan.v1.OperationResult
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_pvp_proto_init() }
func file_thinhthan_v1_pvp_proto_init() {
	if File_thinhthan_v1_pvp_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_pvp_proto_rawDesc), len(file_thinhthan_v1_pvp_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_pvp_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_pvp_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_pvp_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_pvp_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_pvp_proto = out.File
	file_thinhthan_v1_pvp_proto_goTypes = nil
	file_thinhthan_v1_pvp_proto_depIdxs = nil
}
