// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: thinhthan/v1/session.proto

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientPlatform int32

const (
	ClientPlatform_CLIENT_PLATFORM_UNSPECIFIED ClientPlatform = 0
	ClientPlatform_CLIENT_PLATFORM_WINDOWS     ClientPlatform = 1
	ClientPlatform_CLIENT_PLATFORM_ANDROID     ClientPlatform = 2
)

// Enum value maps for ClientPlatform.
var (
	ClientPlatform_name = map[int32]string{
		0: "CLIENT_PLATFORM_UNSPECIFIED",
		1: "CLIENT_PLATFORM_WINDOWS",
		2: "CLIENT_PLATFORM_ANDROID",
	}
	ClientPlatform_value = map[string]int32{
		"CLIENT_PLATFORM_UNSPECIFIED": 0,
		"CLIENT_PLATFORM_WINDOWS":     1,
		"CLIENT_PLATFORM_ANDROID":     2,
	}
)

func (x ClientPlatform) Enum() *ClientPlatform {
	p := new(ClientPlatform)
	*p = x
	return p
}

func (x ClientPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[0].Descriptor()
}

func (ClientPlatform) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[0]
}

func (x ClientPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientPlatform.Descriptor instead.
func (ClientPlatform) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{0}
}

type ClientLocale int32

const (
	ClientLocale_CLIENT_LOCALE_UNSPECIFIED ClientLocale = 0
	ClientLocale_CLIENT_LOCALE_VI_VN       ClientLocale = 1
	ClientLocale_CLIENT_LOCALE_EN_US       ClientLocale = 2
)

// Enum value maps for ClientLocale.
var (
	ClientLocale_name = map[int32]string{
		0: "CLIENT_LOCALE_UNSPECIFIED",
		1: "CLIENT_LOCALE_VI_VN",
		2: "CLIENT_LOCALE_EN_US",
	}
	ClientLocale_value = map[string]int32{
		"CLIENT_LOCALE_UNSPECIFIED": 0,
		"CLIENT_LOCALE_VI_VN":       1,
		"CLIENT_LOCALE_EN_US":       2,
	}
)

func (x ClientLocale) Enum() *ClientLocale {
	p := new(ClientLocale)
	*p = x
	return p
}

func (x ClientLocale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientLocale) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[1].Descriptor()
}

func (ClientLocale) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[1]
}

func (x ClientLocale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientLocale.Descriptor instead.
func (ClientLocale) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{1}
}

type SessionReplacedReason int32

const (
	SessionReplacedReason_SESSION_REPLACED_REASON_UNSPECIFIED   SessionReplacedReason = 0
	SessionReplacedReason_SESSION_REPLACED_REASON_NEWER_SESSION SessionReplacedReason = 1
	SessionReplacedReason_SESSION_REPLACED_REASON_REVOKED       SessionReplacedReason = 2
)

// Enum value maps for SessionReplacedReason.
var (
	SessionReplacedReason_name = map[int32]string{
		0: "SESSION_REPLACED_REASON_UNSPECIFIED",
		1: "SESSION_REPLACED_REASON_NEWER_SESSION",
		2: "SESSION_REPLACED_REASON_REVOKED",
	}
	SessionReplacedReason_value = map[string]int32{
		"SESSION_REPLACED_REASON_UNSPECIFIED":   0,
		"SESSION_REPLACED_REASON_NEWER_SESSION": 1,
		"SESSION_REPLACED_REASON_REVOKED":       2,
	}
)

func (x SessionReplacedReason) Enum() *SessionReplacedReason {
	p := new(SessionReplacedReason)
	*p = x
	return p
}

func (x SessionReplacedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionReplacedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[2].Descriptor()
}

func (SessionReplacedReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[2]
}

func (x SessionReplacedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionReplacedReason.Descriptor instead.
func (SessionReplacedReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{2}
}

type ServerDrainingReason int32

const (
	ServerDrainingReason_SERVER_DRAINING_REASON_UNSPECIFIED ServerDrainingReason = 0
	ServerDrainingReason_SERVER_DRAINING_REASON_MAINTENANCE ServerDrainingReason = 1
)

// Enum value maps for ServerDrainingReason.
var (
	ServerDrainingReason_name = map[int32]string{
		0: "SERVER_DRAINING_REASON_UNSPECIFIED",
		1: "SERVER_DRAINING_REASON_MAINTENANCE",
	}
	ServerDrainingReason_value = map[string]int32{
		"SERVER_DRAINING_REASON_UNSPECIFIED": 0,
		"SERVER_DRAINING_REASON_MAINTENANCE": 1,
	}
)

func (x ServerDrainingReason) Enum() *ServerDrainingReason {
	p := new(ServerDrainingReason)
	*p = x
	return p
}

func (x ServerDrainingReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerDrainingReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[3].Descriptor()
}

func (ServerDrainingReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[3]
}

func (x ServerDrainingReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerDrainingReason.Descriptor instead.
func (ServerDrainingReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{3}
}

type PlacementReason int32

const (
	PlacementReason_PLACEMENT_REASON_UNSPECIFIED     PlacementReason = 0
	PlacementReason_PLACEMENT_REASON_RESPAWN         PlacementReason = 1
	PlacementReason_PLACEMENT_REASON_INSTANCE_RETURN PlacementReason = 2
	PlacementReason_PLACEMENT_REASON_RECONNECT       PlacementReason = 3
	PlacementReason_PLACEMENT_REASON_FIRST_LOGIN     PlacementReason = 4
)

// Enum value maps for PlacementReason.
var (
	PlacementReason_name = map[int32]string{
		0: "PLACEMENT_REASON_UNSPECIFIED",
		1: "PLACEMENT_REASON_RESPAWN",
		2: "PLACEMENT_REASON_INSTANCE_RETURN",
		3: "PLACEMENT_REASON_RECONNECT",
		4: "PLACEMENT_REASON_FIRST_LOGIN",
	}
	PlacementReason_value = map[string]int32{
		"PLACEMENT_REASON_UNSPECIFIED":     0,
		"PLACEMENT_REASON_RESPAWN":         1,
		"PLACEMENT_REASON_INSTANCE_RETURN": 2,
		"PLACEMENT_REASON_RECONNECT":       3,
		"PLACEMENT_REASON_FIRST_LOGIN":     4,
	}
)

func (x PlacementReason) Enum() *PlacementReason {
	p := new(PlacementReason)
	*p = x
	return p
}

func (x PlacementReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementReason) Descriptor() protoreflect.EnumDescriptor {
	return file_thinhthan_v1_session_proto_enumTypes[4].Descriptor()
}

func (PlacementReason) Type() protoreflect.EnumType {
	return &file_thinhthan_v1_session_proto_enumTypes[4]
}

func (x PlacementReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementReason.Descriptor instead.
func (PlacementReason) EnumDescriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{4}
}

// ID 1
type C2SHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*C2SHello_GameplayTicket
	//	*C2SHello_ResumeCredential
	Credential      isC2SHello_Credential `protobuf_oneof:"credential"`
	ClientBuild     uint32                `protobuf:"varint,3,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`
	Platform        ClientPlatform        `protobuf:"varint,4,opt,name=platform,proto3,enum=thinhthan.v1.ClientPlatform" json:"platform,omitempty"`
	ContentRevision string                `protobuf:"bytes,5,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	DeviceId        []byte                `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // UUID, 16 bytes
	Locale          ClientLocale          `protobuf:"varint,7,opt,name=locale,proto3,enum=thinhthan.v1.ClientLocale" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *C2SHello) Reset() {
	*x = C2SHello{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHello) ProtoMessage() {}

func (x *C2SHello) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHello.ProtoReflect.Descriptor instead.
func (*C2SHello) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *C2SHello) GetCredential() isC2SHello_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *C2SHello) GetGameplayTicket() string {
	if x != nil {
		if x, ok := x.Credential.(*C2SHello_GameplayTicket); ok {
			return x.GameplayTicket
		}
	}
	return ""
}

func (x *C2SHello) GetResumeCredential() string {
	if x != nil {
		if x, ok := x.Credential.(*C2SHello_ResumeCredential); ok {
			return x.ResumeCredential
		}
	}
	return ""
}

func (x *C2SHello) GetClientBuild() uint32 {
	if x != nil {
		return x.ClientBuild
	}
	return 0
}

func (x *C2SHello) GetPlatform() ClientPlatform {
	if x != nil {
		return x.Platform
	}
	return ClientPlatform_CLIENT_PLATFORM_UNSPECIFIED
}

func (x *C2SHello) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *C2SHello) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *C2SHello) GetLocale() ClientLocale {
	if x != nil {
		return x.Locale
	}
	return ClientLocale_CLIENT_LOCALE_UNSPECIFIED
}

type isC2SHello_Credential interface {
	isC2SHello_Credential()
}

type C2SHello_GameplayTicket struct {
	GameplayTicket string `protobuf:"bytes,1,opt,name=gameplay_ticket,json=gameplayTicket,proto3,oneof"`
}

type C2SHello_ResumeCredential struct {
	ResumeCredential string `protobuf:"bytes,2,opt,name=resume_credential,json=resumeCredential,proto3,oneof"`
}

func (*C2SHello_GameplayTicket) isC2SHello_Credential() {}

func (*C2SHello_ResumeCredential) isC2SHello_Credential() {}

// ID 2
type S2CHelloOk struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SessionId              []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID, 16 bytes
	SessionEpoch           uint64                 `protobuf:"varint,2,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	AccountId              []byte                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // UUID, 16 bytes
	ServerTimeMs           int64                  `protobuf:"varint,4,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	HeartbeatIntervalMs    uint32                 `protobuf:"varint,5,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"` // 5000
	ConnectionTimeoutMs    uint32                 `protobuf:"varint,6,opt,name=connection_timeout_ms,json=connectionTimeoutMs,proto3" json:"connection_timeout_ms,omitempty"` // 15000
	ResumeCredential       string                 `protobuf:"bytes,7,opt,name=resume_credential,json=resumeCredential,proto3" json:"resume_credential,omitempty"`
	ResumeExpiresAtMs      int64                  `protobuf:"varint,8,opt,name=resume_expires_at_ms,json=resumeExpiresAtMs,proto3" json:"resume_expires_at_ms,omitempty"`
	ProtocolMinor          uint32                 `protobuf:"varint,9,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	ContentRevision        string                 `protobuf:"bytes,10,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	PendingDeletion        bool                   `protobuf:"varint,11,opt,name=pending_deletion,json=pendingDeletion,proto3" json:"pending_deletion,omitempty"`
	ResumedCharacterId     []byte                 `protobuf:"bytes,12,opt,name=resumed_character_id,json=resumedCharacterId,proto3" json:"resumed_character_id,omitempty"`                // UUID, 16 bytes; empty = none
	ResumeRotateIntervalMs uint32                 `protobuf:"varint,13,opt,name=resume_rotate_interval_ms,json=resumeRotateIntervalMs,proto3" json:"resume_rotate_interval_ms,omitempty"` // 300000
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *S2CHelloOk) Reset() {
	*x = S2CHelloOk{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CHelloOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHelloOk) ProtoMessage() {}

func (x *S2CHelloOk) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHelloOk.ProtoReflect.Descriptor instead.
func (*S2CHelloOk) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *S2CHelloOk) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *S2CHelloOk) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *S2CHelloOk) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *S2CHelloOk) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *S2CHelloOk) GetHeartbeatIntervalMs() uint32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *S2CHelloOk) GetConnectionTimeoutMs() uint32 {
	if x != nil {
		return x.ConnectionTimeoutMs
	}
	return 0
}

func (x *S2CHelloOk) GetResumeCredential() string {
	if x != nil {
		return x.ResumeCredential
	}
	return ""
}

func (x *S2CHelloOk) GetResumeExpiresAtMs() int64 {
	if x != nil {
		return x.ResumeExpiresAtMs
	}
	return 0
}

func (x *S2CHelloOk) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *S2CHelloOk) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

func (x *S2CHelloOk) GetPendingDeletion() bool {
	if x != nil {
		return x.PendingDeletion
	}
	return false
}

func (x *S2CHelloOk) GetResumedCharacterId() []byte {
	if x != nil {
		return x.ResumedCharacterId
	}
	return nil
}

func (x *S2CHelloOk) GetResumeRotateIntervalMs() uint32 {
	if x != nil {
		return x.ResumeRotateIntervalMs
	}
	return 0
}

// ID 3
type S2CError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode      ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=thinhthan.v1.ErrorCode" json:"error_code,omitempty"`
	Retryability   Retryability           `protobuf:"varint,2,opt,name=retryability,proto3,enum=thinhthan.v1.Retryability" json:"retryability,omitempty"`
	RetryAfterMs   uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	QueuePosition  uint32                 `protobuf:"varint,4,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	SafeMessageKey string                 `protobuf:"bytes,5,opt,name=safe_message_key,json=safeMessageKey,proto3" json:"safe_message_key,omitempty"`
	CloseAfter     bool                   `protobuf:"varint,6,opt,name=close_after,json=closeAfter,proto3" json:"close_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CError) Reset() {
	*x = S2CError{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CError) ProtoMessage() {}

func (x *S2CError) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CError.ProtoReflect.Descriptor instead.
func (*S2CError) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *S2CError) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *S2CError) GetRetryability() Retryability {
	if x != nil {
		return x.Retryability
	}
	return Retryability_RETRYABILITY_UNSPECIFIED
}

func (x *S2CError) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *S2CError) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *S2CError) GetSafeMessageKey() string {
	if x != nil {
		return x.SafeMessageKey
	}
	return ""
}

func (x *S2CError) GetCloseAfter() bool {
	if x != nil {
		return x.CloseAfter
	}
	return false
}

// ID 4
type C2SHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMonoMs  uint64                 `protobuf:"varint,1,opt,name=client_mono_ms,json=clientMonoMs,proto3" json:"client_mono_ms,omitempty"`
	EchoServerMs  uint64                 `protobuf:"varint,2,opt,name=echo_server_ms,json=echoServerMs,proto3" json:"echo_server_ms,omitempty"` // 0 if none received yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SHeartbeat) Reset() {
	*x = C2SHeartbeat{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHeartbeat) ProtoMessage() {}

func (x *C2SHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHeartbeat.ProtoReflect.Descriptor instead.
func (*C2SHeartbeat) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *C2SHeartbeat) GetClientMonoMs() uint64 {
	if x != nil {
		return x.ClientMonoMs
	}
	return 0
}

func (x *C2SHeartbeat) GetEchoServerMs() uint64 {
	if x != nil {
		return x.EchoServerMs
	}
	return 0
}

// ID 5
type S2CHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerMs      uint64                 `protobuf:"varint,1,opt,name=server_ms,json=serverMs,proto3" json:"server_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CHeartbeat) Reset() {
	*x = S2CHeartbeat{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHeartbeat) ProtoMessage() {}

func (x *S2CHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHeartbeat.ProtoReflect.Descriptor instead.
func (*S2CHeartbeat) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *S2CHeartbeat) GetServerMs() uint64 {
	if x != nil {
		return x.ServerMs
	}
	return 0
}

// ID 6
type C2SCharacterAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SCharacterAttach) Reset() {
	*x = C2SCharacterAttach{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SCharacterAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterAttach) ProtoMessage() {}

func (x *C2SCharacterAttach) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterAttach.ProtoReflect.Descriptor instead.
func (*C2SCharacterAttach) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *C2SCharacterAttach) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

// ID 7
type S2CCharacterAttachOk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharacterId     []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	OwnershipEpoch  uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	MapId           string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ChannelIndex    uint32                 `protobuf:"varint,4,opt,name=channel_index,json=channelIndex,proto3" json:"channel_index,omitempty"`
	InstanceId      []byte                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // UUID, 16 bytes; empty in the normal world
	ContentRevision string                 `protobuf:"bytes,6,opt,name=content_revision,json=contentRevision,proto3" json:"content_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2CCharacterAttachOk) Reset() {
	*x = S2CCharacterAttachOk{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CCharacterAttachOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterAttachOk) ProtoMessage() {}

func (x *S2CCharacterAttachOk) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterAttachOk.ProtoReflect.Descriptor instead.
func (*S2CCharacterAttachOk) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *S2CCharacterAttachOk) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

func (x *S2CCharacterAttachOk) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *S2CCharacterAttachOk) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *S2CCharacterAttachOk) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

func (x *S2CCharacterAttachOk) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *S2CCharacterAttachOk) GetContentRevision() string {
	if x != nil {
		return x.ContentRevision
	}
	return ""
}

// ID 8
type S2CSessionReplaced struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        SessionReplacedReason  `protobuf:"varint,1,opt,name=reason,proto3,enum=thinhthan.v1.SessionReplacedReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CSessionReplaced) Reset() {
	*x = S2CSessionReplaced{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CSessionReplaced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSessionReplaced) ProtoMessage() {}

func (x *S2CSessionReplaced) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSessionReplaced.ProtoReflect.Descriptor instead.
func (*S2CSessionReplaced) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *S2CSessionReplaced) GetReason() SessionReplacedReason {
	if x != nil {
		return x.Reason
	}
	return SessionReplacedReason_SESSION_REPLACED_REASON_UNSPECIFIED
}

// ID 9
type S2CServerDraining struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Reason           ServerDrainingReason   `protobuf:"varint,1,opt,name=reason,proto3,enum=thinhthan.v1.ServerDrainingReason" json:"reason,omitempty"`
	DrainDeadlineMs  int64                  `protobuf:"varint,2,opt,name=drain_deadline_ms,json=drainDeadlineMs,proto3" json:"drain_deadline_ms,omitempty"` // absolute
	ReconnectAfterMs uint32                 `protobuf:"varint,3,opt,name=reconnect_after_ms,json=reconnectAfterMs,proto3" json:"reconnect_after_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2CServerDraining) Reset() {
	*x = S2CServerDraining{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CServerDraining) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CServerDraining) ProtoMessage() {}

func (x *S2CServerDraining) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CServerDraining.ProtoReflect.Descriptor instead.
func (*S2CServerDraining) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *S2CServerDraining) GetReason() ServerDrainingReason {
	if x != nil {
		return x.Reason
	}
	return ServerDrainingReason_SERVER_DRAINING_REASON_UNSPECIFIED
}

func (x *S2CServerDraining) GetDrainDeadlineMs() int64 {
	if x != nil {
		return x.DrainDeadlineMs
	}
	return 0
}

func (x *S2CServerDraining) GetReconnectAfterMs() uint32 {
	if x != nil {
		return x.ReconnectAfterMs
	}
	return 0
}

// ID 10
type C2SCharacterDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SCharacterDetach) Reset() {
	*x = C2SCharacterDetach{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SCharacterDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterDetach) ProtoMessage() {}

func (x *C2SCharacterDetach) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterDetach.ProtoReflect.Descriptor instead.
func (*C2SCharacterDetach) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{9}
}

// ID 11
type S2CCharacterDetachOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   []byte                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // UUID, 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CCharacterDetachOk) Reset() {
	*x = S2CCharacterDetachOk{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CCharacterDetachOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterDetachOk) ProtoMessage() {}

func (x *S2CCharacterDetachOk) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterDetachOk.ProtoReflect.Descriptor instead.
func (*S2CCharacterDetachOk) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *S2CCharacterDetachOk) GetCharacterId() []byte {
	if x != nil {
		return x.CharacterId
	}
	return nil
}

// ID 12
type C2SCharacterCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   []byte                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"` // UUID, 16 bytes
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SCharacterCreate) Reset() {
	*x = C2SCharacterCreate{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SCharacterCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterCreate) ProtoMessage() {}

func (x *C2SCharacterCreate) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterCreate.ProtoReflect.Descriptor instead.
func (*C2SCharacterCreate) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *C2SCharacterCreate) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *C2SCharacterCreate) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *C2SCharacterCreate) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

// ID 13
type S2CCharacterCreateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OperationResult       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Character     *CharacterSummary      `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CCharacterCreateResult) Reset() {
	*x = S2CCharacterCreateResult{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CCharacterCreateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterCreateResult) ProtoMessage() {}

func (x *S2CCharacterCreateResult) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterCreateResult.ProtoReflect.Descriptor instead.
func (*S2CCharacterCreateResult) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *S2CCharacterCreateResult) GetResult() *OperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CCharacterCreateResult) GetCharacter() *CharacterSummary {
	if x != nil {
		return x.Character
	}
	return nil
}

// ID 14
type S2CCharacterList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Characters     []*CharacterSummary    `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	CharacterSlots uint32                 `protobuf:"varint,2,opt,name=character_slots,json=characterSlots,proto3" json:"character_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CCharacterList) Reset() {
	*x = S2CCharacterList{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CCharacterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterList) ProtoMessage() {}

func (x *S2CCharacterList) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterList.ProtoReflect.Descriptor instead.
func (*S2CCharacterList) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *S2CCharacterList) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *S2CCharacterList) GetCharacterSlots() uint32 {
	if x != nil {
		return x.CharacterSlots
	}
	return 0
}

// ID 15
type S2CPlacementPending struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestMessageId uint32                 `protobuf:"varint,1,opt,name=request_message_id,json=requestMessageId,proto3" json:"request_message_id,omitempty"` // 6, 208 or 0
	Reason           PlacementReason        `protobuf:"varint,2,opt,name=reason,proto3,enum=thinhthan.v1.PlacementReason" json:"reason,omitempty"`
	RetryAfterMs     uint32                 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // 5000
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2CPlacementPending) Reset() {
	*x = S2CPlacementPending{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CPlacementPending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CPlacementPending) ProtoMessage() {}

func (x *S2CPlacementPending) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CPlacementPending.ProtoReflect.Descriptor instead.
func (*S2CPlacementPending) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *S2CPlacementPending) GetRequestMessageId() uint32 {
	if x != nil {
		return x.RequestMessageId
	}
	return 0
}

func (x *S2CPlacementPending) GetReason() PlacementReason {
	if x != nil {
		return x.Reason
	}
	return PlacementReason_PLACEMENT_REASON_UNSPECIFIED
}

func (x *S2CPlacementPending) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// ID 16
type S2CResumeCredential struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResumeCredential  string                 `protobuf:"bytes,1,opt,name=resume_credential,json=resumeCredential,proto3" json:"resume_credential,omitempty"`
	ResumeExpiresAtMs int64                  `protobuf:"varint,2,opt,name=resume_expires_at_ms,json=resumeExpiresAtMs,proto3" json:"resume_expires_at_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *S2CResumeCredential) Reset() {
	*x = S2CResumeCredential{}
	mi := &file_thinhthan_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CResumeCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CResumeCredential) ProtoMessage() {}

func (x *S2CResumeCredential) ProtoReflect() protoreflect.Message {
	mi := &file_thinhthan_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CResumeCredential.ProtoReflect.Descriptor instead.
func (*S2CResumeCredential) Descriptor() ([]byte, []int) {
	return file_thinhthan_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *S2CResumeCredential) GetResumeCredential() string {
	if x != nil {
		return x.ResumeCredential
	}
	return ""
}

func (x *S2CResumeCredential) GetResumeExpiresAtMs() int64 {
	if x != nil {
		return x.ResumeExpiresAtMs
	}
	return 0
}

var File_thinhthan_v1_session_proto protoreflect.FileDescriptor

const file_thinhthan_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1athinhthan/v1/session.proto\x12\fthinhthan.v1\x1a\x19thinhthan/v1/common.proto\"\xcb\x02\n" +
	"\bC2SHello\x12)\n" +
	"\x0fgameplay_ticket\x18\x01 \x01(\tH\x00R\x0egameplayTicket\x12-\n" +
	"\x11resume_credential\x18\x02 \x01(\tH\x00R\x10resumeCredential\x12!\n" +
	"\fclient_build\x18\x03 \x01(\rR\vclientBuild\x128\n" +
	"\bplatform\x18\x04 \x01(\x0e2\x1c.thinhthan.v1.ClientPlatformR\bplatform\x12)\n" +
	"\x10content_revision\x18\x05 \x01(\tR\x0fcontentRevision\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\fR\bdeviceId\x122\n" +
	"\x06locale\x18\a \x01(\x0e2\x1a.thinhthan.v1.ClientLocaleR\x06localeB\f\n" +
	"\n" +
	"credential\"\xc5\x04\n" +
	"\n" +
	"S2CHelloOk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12#\n" +
	"\rsession_epoch\x18\x02 \x01(\x04R\fsessionEpoch\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\fR\taccountId\x12$\n" +
	"\x0eserver_time_ms\x18\x04 \x01(\x03R\fserverTimeMs\x122\n" +
	"\x15heartbeat_interval_ms\x18\x05 \x01(\rR\x13heartbeatIntervalMs\x122\n" +
	"\x15connection_timeout_ms\x18\x06 \x01(\rR\x13connectionTimeoutMs\x12+\n" +
	"\x11resume_credential\x18\a \x01(\tR\x10resumeCredential\x12/\n" +
	"\x14resume_expires_at_ms\x18\b \x01(\x03R\x11resumeExpiresAtMs\x12%\n" +
	"\x0eprotocol_minor\x18\t \x01(\rR\rprotocolMinor\x12)\n" +
	"\x10content_revision\x18\n" +
	" \x01(\tR\x0fcontentRevision\x12)\n" +
	"\x10pending_deletion\x18\v \x01(\bR\x0fpendingDeletion\x120\n" +
	"\x14resumed_character_id\x18\f \x01(\fR\x12resumedCharacterId\x129\n" +
	"\x19resume_rotate_interval_ms\x18\r \x01(\rR\x16resumeRotateIntervalMs\"\x9a\x02\n" +
	"\bS2CError\x126\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x17.thinhthan.v1.ErrorCodeR\terrorCode\x12>\n" +
	"\fretryability\x18\x02 \x01(\x0e2\x1a.thinhthan.v1.RetryabilityR\fretryability\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\x12%\n" +
	"\x0equeue_position\x18\x04 \x01(\rR\rqueuePosition\x12(\n" +
	"\x10safe_message_key\x18\x05 \x01(\tR\x0esafeMessageKey\x12\x1f\n" +
	"\vclose_after\x18\x06 \x01(\bR\n" +
	"closeAfter\"Z\n" +
	"\fC2SHeartbeat\x12$\n" +
	"\x0eclient_mono_ms\x18\x01 \x01(\x04R\fclientMonoMs\x12$\n" +
	"\x0eecho_server_ms\x18\x02 \x01(\x04R\fechoServerMs\"+\n" +
	"\fS2CHeartbeat\x12\x1b\n" +
	"\tserver_ms\x18\x01 \x01(\x04R\bserverMs\"7\n" +
	"\x12C2SCharacterAttach\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\"\xea\x01\n" +
	"\x14S2CCharacterAttachOk\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12#\n" +
	"\rchannel_index\x18\x04 \x01(\rR\fchannelIndex\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\fR\n" +
	"instanceId\x12)\n" +
	"\x10content_revision\x18\x06 \x01(\tR\x0fcontentRevision\"Q\n" +
	"\x12S2CSessionReplaced\x12;\n" +
	"\x06reason\x18\x01 \x01(\x0e2#.thinhthan.v1.SessionReplacedReasonR\x06reason\"\xa9\x01\n" +
	"\x11S2CServerDraining\x12:\n" +
	"\x06reason\x18\x01 \x01(\x0e2\".thinhthan.v1.ServerDrainingReasonR\x06reason\x12*\n" +
	"\x11drain_deadline_ms\x18\x02 \x01(\x03R\x0fdrainDeadlineMs\x12,\n" +
	"\x12reconnect_after_ms\x18\x03 \x01(\rR\x10reconnectAfterMs\"\x14\n" +
	"\x12C2SCharacterDetach\"9\n" +
	"\x14S2CCharacterDetachOk\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\fR\vcharacterId\"y\n" +
	"\x12C2SCharacterCreate\x12!\n" +
	"\foperation_id\x18\x01 \x01(\fR\voperationId\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\"\x8f\x01\n" +
	"\x18S2CCharacterCreateResult\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.thinhthan.v1.OperationResultR\x06result\x12<\n" +
	"\tcharacter\x18\x02 \x01(\v2\x1e.thinhthan.v1.CharacterSummaryR\tcharacter\"{\n" +
	"\x10S2CCharacterList\x12>\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1e.thinhthan.v1.CharacterSummaryR\n" +
	"characters\x12'\n" +
	"\x0fcharacter_slots\x18\x02 \x01(\rR\x0echaracterSlots\"\xa0\x01\n" +
	"\x13S2CPlacementPending\x12,\n" +
	"\x12request_message_id\x18\x01 \x01(\rR\x10requestMessageId\x125\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1d.thinhthan.v1.PlacementReasonR\x06reason\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\rR\fretryAfterMs\"s\n" +
	"\x13S2CResumeCredential\x12+\n" +
	"\x11resume_credential\x18\x01 \x01(\tR\x10resumeCredential\x12/\n" +
	"\x14resume_expires_at_ms\x18\x02 \x01(\x03R\x11resumeExpiresAtMs*k\n" +
	"\x0eClientPlatform\x12\x1f\n" +
	"\x1bCLIENT_PLATFORM_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CLIENT_PLATFORM_WINDOWS\x10\x01\x12\x1b\n" +
	"\x17CLIENT_PLATFORM_ANDROID\x10\x02*_\n" +
	"\fClientLocale\x12\x1d\n" +
	"\x19CLIENT_LOCALE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CLIENT_LOCALE_VI_VN\x10\x01\x12\x17\n" +
	"\x13CLIENT_LOCALE_EN_US\x10\x02*\x90\x01\n" +
	"\x15SessionReplacedReason\x12'\n" +
	"#SESSION_REPLACED_REASON_UNSPECIFIED\x10\x00\x12)\n" +
	"%SESSION_REPLACED_REASON_NEWER_SESSION\x10\x01\x12#\n" +
	"\x1fSESSION_REPLACED_REASON_REVOKED\x10\x02*f\n" +
	"\x14ServerDrainingReason\x12&\n" +
	"\"SERVER_DRAINING_REASON_UNSPECIFIED\x10\x00\x12&\n" +
	"\"SERVER_DRAINING_REASON_MAINTENANCE\x10\x01*\xb9\x01\n" +
	"\x0fPlacementReason\x12 \n" +
	"\x1cPLACEMENT_REASON_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PLACEMENT_REASON_RESPAWN\x10\x01\x12$\n" +
	" PLACEMENT_REASON_INSTANCE_RETURN\x10\x02\x12\x1e\n" +
	"\x1aPLACEMENT_REASON_RECONNECT\x10\x03\x12 \n" +
	"\x1cPLACEMENT_REASON_FIRST_LOGIN\x10\x04BCZ)thinhthan/internal/protocol/v1;protocolv1\xaa\x02\x15ThinhThan.Protocol.V1b\x06proto3"

var (
	file_thinhthan_v1_session_proto_rawDescOnce sync.Once
	file_thinhthan_v1_session_proto_rawDescData []byte
)

func file_thinhthan_v1_session_proto_rawDescGZIP() []byte {
	file_thinhthan_v1_session_proto_rawDescOnce.Do(func() {
		file_thinhthan_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thinhthan_v1_session_proto_rawDesc), len(file_thinhthan_v1_session_proto_rawDesc)))
	})
	return file_thinhthan_v1_session_proto_rawDescData
}

var file_thinhthan_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_thinhthan_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_thinhthan_v1_session_proto_goTypes = []any{
	(ClientPlatform)(0),              // 0: thinhthan.v1.ClientPlatform
	(ClientLocale)(0),                // 1: thinhthan.v1.ClientLocale
	(SessionReplacedReason)(0),       // 2: thinhthan.v1.SessionReplacedReason
	(ServerDrainingReason)(0),        // 3: thinhthan.v1.ServerDrainingReason
	(PlacementReason)(0),             // 4: thinhthan.v1.PlacementReason
	(*C2SHello)(nil),                 // 5: thinhthan.v1.C2SHello
	(*S2CHelloOk)(nil),               // 6: thinhthan.v1.S2CHelloOk
	(*S2CError)(nil),                 // 7: thinhthan.v1.S2CError
	(*C2SHeartbeat)(nil),             // 8: thinhthan.v1.C2SHeartbeat
	(*S2CHeartbeat)(nil),             // 9: thinhthan.v1.S2CHeartbeat
	(*C2SCharacterAttach)(nil),       // 10: thinhthan.v1.C2SCharacterAttach
	(*S2CCharacterAttachOk)(nil),     // 11: thinhthan.v1.S2CCharacterAttachOk
	(*S2CSessionReplaced)(nil),       // 12: thinhthan.v1.S2CSessionReplaced
	(*S2CServerDraining)(nil),        // 13: thinhthan.v1.S2CServerDraining
	(*C2SCharacterDetach)(nil),       // 14: thinhthan.v1.C2SCharacterDetach
	(*S2CCharacterDetachOk)(nil),     // 15: thinhthan.v1.S2CCharacterDetachOk
	(*C2SCharacterCreate)(nil),       // 16: thinhthan.v1.C2SCharacterCreate
	(*S2CCharacterCreateResult)(nil), // 17: thinhthan.v1.S2CCharacterCreateResult
	(*S2CCharacterList)(nil),         // 18: thinhthan.v1.S2CCharacterList
	(*S2CPlacementPending)(nil),      // 19: thinhthan.v1.S2CPlacementPending
	(*S2CResumeCredential)(nil),      // 20: thinhthan.v1.S2CResumeCredential
	(ErrorCode)(0),                   // 21: thinhthan.v1.ErrorCode
	(Retryability)(0),                // 22: thinhthan.v1.Retryability
	(*OperationResult)(nil),          // 23: thinhthan.v1.OperationResult
	(*CharacterSummary)(nil),         // 24: thinhthan.v1.CharacterSummary
}
var file_thinhthan_v1_session_proto_depIdxs = []int32{
	0,  // 0: thinhthan.v1.C2SHello.platform:type_name -> thinhthan.v1.ClientPlatform
	1,  // 1: thinhthan.v1.C2SHello.locale:type_name -> thinhthan.v1.ClientLocale
	21, // 2: thinhthan.v1.S2CError.error_code:type_name -> thinhthan.v1.ErrorCode
	22, // 3: thinhthan.v1.S2CError.retryability:type_name -> thinhthan.v1.Retryability
	2,  // 4: thinhthan.v1.S2CSessionReplaced.reason:type_name -> thinhthan.v1.SessionReplacedReason
	3,  // 5: thinhthan.v1.S2CServerDraining.reason:type_name -> thinhthan.v1.ServerDrainingReason
	23, // 6: thinhthan.v1.S2CCharacterCreateResult.result:type_name -> thinhthan.v1.OperationResult
	24, // 7: thinhthan.v1.S2CCharacterCreateResult.character:type_name -> thinhthan.v1.CharacterSummary
	24, // 8: thinhthan.v1.S2CCharacterList.characters:type_name -> thinhthan.v1.CharacterSummary
	4,  // 9: thinhthan.v1.S2CPlacementPending.reason:type_name -> thinhthan.v1.PlacementReason
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_thinhthan_v1_session_proto_init() }
func file_thinhthan_v1_session_proto_init() {
	if File_thinhthan_v1_session_proto != nil {
		return
	}
	file_thinhthan_v1_common_proto_init()
	file_thinhthan_v1_session_proto_msgTypes[0].OneofWrappers = []any{
		(*C2SHello_GameplayTicket)(nil),
		(*C2SHello_ResumeCredential)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thinhthan_v1_session_proto_rawDesc), len(file_thinhthan_v1_session_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thinhthan_v1_session_proto_goTypes,
		DependencyIndexes: file_thinhthan_v1_session_proto_depIdxs,
		EnumInfos:         file_thinhthan_v1_session_proto_enumTypes,
		MessageInfos:      file_thinhthan_v1_session_proto_msgTypes,
	}.Build()
	File_thinhthan_v1_session_proto = out.File
	file_thinhthan_v1_session_proto_goTypes = nil
	file_thinhthan_v1_session_proto_depIdxs = nil
}
