#Requires -Version 7.0
<#
.SYNOPSIS
  thinhthan protobuf codegen (IMP-061). Regenerates committed Go and C# outputs
  from proto/thinhthan/** and prepends the CODE-004 generated C# header.

.DESCRIPTION
  Deterministic, pinned-tool generation:
    - protoc 36.2 (libprotoc 36.2), asserted
    - protoc-gen-go v1.36.12 (server/go.mod pin), asserted
    - pwsh >= 7.6.6, asserted
  Writes only *.pb.go under server/internal/{protocol,durable/journal}/v1 and
  *.cs under client/Assets/Scripts/Protocol. Never deletes or rewrites
  ThinhThan.Protocol.asmdef, csc.rsp, or any .meta.

.PARAMETER Drift
  Regenerate, then fail (exit 1) when `git status --porcelain` over the
  generated paths is non-empty — committed outputs are stale.
#>
[CmdletBinding()]
param(
  [switch]$Drift
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($PSVersionTable.PSVersion -lt [version]'7.6.6') {
  Write-Error "codegen.ps1 requires pwsh >= 7.6.6 (found $($PSVersionTable.PSVersion))"
}

$RepoRoot = (git -C $PSScriptRoot rev-parse --show-toplevel).Trim()
Set-Location $RepoRoot

$PinnedProtocVersion = 'libprotoc 36.2'
$PinnedGenGoVersion = 'v1.36.12'

function Find-Tool {
  param([string[]]$Names, [string[]]$ExtraCandidates)
  foreach ($n in $Names) {
    $c = Get-Command $n -ErrorAction SilentlyContinue
    if ($c) { return $c.Source }
  }
  foreach ($p in $ExtraCandidates) {
    if (Test-Path $p) { return $p }
  }
  return $null
}

$exe = if ($IsWindows) { '.exe' } else { '' }

# --- resolve pinned tools -----------------------------------------------------

$protoc = $env:PROTOC
if (-not $protoc) {
  $protoc = Find-Tool -Names @("protoc$exe", 'protoc') -ExtraCandidates @(
    (Join-Path $HOME ("tools/protoc/bin/protoc" + $exe)),
    (Join-Path $HOME ("tools/protoc/protoc" + $exe))
  )
}
if (-not $protoc) { Write-Error 'protoc not found (expected pinned protoc 36.2 on PATH or ~/tools/protoc/bin)' }
$protocVersion = & $protoc --version
if ($protocVersion -ne $PinnedProtocVersion) {
  Write-Error "protoc version mismatch: expected '$PinnedProtocVersion', got '$protocVersion'"
}

$go = $env:GO
if (-not $go) {
  $go = Find-Tool -Names @('go') -ExtraCandidates @(
    (Join-Path $HOME ("tools/go/bin/go" + $exe)),
    '/usr/local/go/bin/go'
  )
}
if (-not $go) { Write-Error 'go toolchain not found (expected Go 1.27.1)' }

# protoc-gen-go: module pin from server/go.mod installs the exact version.
$gobin = & $go env GOBIN
if (-not $gobin) { $gobin = Join-Path (& $go env GOPATH) 'bin' }
$gengo = Join-Path $gobin ("protoc-gen-go$exe")
if (-not (Test-Path $gengo)) {
  & $go -C server install google.golang.org/protobuf/cmd/protoc-gen-go
  if ($LASTEXITCODE -ne 0) { Write-Error "go install protoc-gen-go failed (exit $LASTEXITCODE)" }
}
$gengoVersion = (& $gengo --version) -replace '^protoc-gen-go(\.exe)?\s+', ''
if ($gengoVersion -ne $PinnedGenGoVersion) {
  Write-Error "protoc-gen-go version mismatch: expected '$PinnedGenGoVersion', got '$gengoVersion'"
}

# --- inputs -------------------------------------------------------------------

$ProtoDir = 'proto'
$networkProtos = @(
  'thinhthan/v1/common.proto',
  'thinhthan/v1/session.proto',
  'thinhthan/v1/movement.proto',
  'thinhthan/v1/combat.proto',
  'thinhthan/v1/durable.proto',
  'thinhthan/v1/content.proto',
  'thinhthan/v1/social.proto',
  'thinhthan/v1/market.proto',
  'thinhthan/v1/pvp.proto'
)
$journalProto = 'thinhthan/internal/v1/durable_journal.proto'

foreach ($p in @($networkProtos + $journalProto)) {
  if (-not (Test-Path (Join-Path $ProtoDir $p))) { Write-Error "missing proto source $ProtoDir/$p" }
}

# --- invocations --------------------------------------------------------------

$env:PATH = "$gobin$([IO.Path]::PathSeparator)$env:PATH"

& $protoc -I $ProtoDir --go_out=server "--go_opt=module=thinhthan" @networkProtos
if ($LASTEXITCODE -ne 0) { Write-Error "protoc Go (network) failed (exit $LASTEXITCODE)" }

& $protoc -I $ProtoDir --go_out=server "--go_opt=module=thinhthan" $journalProto
if ($LASTEXITCODE -ne 0) { Write-Error "protoc Go (journal) failed (exit $LASTEXITCODE)" }

$CsOut = 'client/Assets/Scripts/Protocol'
& $protoc -I $ProtoDir "--csharp_out=$CsOut" @networkProtos
if ($LASTEXITCODE -ne 0) { Write-Error "protoc C# failed (exit $LASTEXITCODE)" }

# --- CODE-004 generated C# header ---------------------------------------------

# Same warning set protoc emits for generated code; prepended before
# the <auto-generated> banner so generation is idempotent.
$header = "#nullable disable`n#pragma warning disable 1591, 0612, 3021, 8981`n"
Get-ChildItem -Path $CsOut -Filter '*.cs' | ForEach-Object {
  $text = [IO.File]::ReadAllText($_.FullName)
  if (-not $text.StartsWith('#nullable disable')) {
    [IO.File]::WriteAllText($_.FullName, $header + $text, (New-Object System.Text.UTF8Encoding($false)))
  }
}

# --- drift mode ---------------------------------------------------------------

if ($Drift) {
  $paths = @(
    'server/internal/protocol',
    'server/internal/durable/journal',
    'client/Assets/Scripts/Protocol',
    'proto/testdata/golden'
  )
  $dirty = git status --porcelain -- @paths
  if ($dirty) {
    Write-Error "codegen drift detected — committed generated output is stale:`n$($dirty -join "`n")"
  }
  Write-Host 'codegen drift = 0'
}
